### ISSUE TITLE
It should be possible to delete (remove) a selected object with a hotkey

### ISSUE THREAD

**Issue by LearnCocos2D** [bjorn/tiled#1023]
Currently neither Backspace nor Delete works to remove/delete a selected object, regardless of whether the object is selected on the layer or via the objects list.

That makes deleting an object always requiring an extra right-click + menu command and if you're not too careful you may end up duplicating the object instead.

**Comment by bjorn** [comment]
I believe this is a bug affecting only OS X, but it is quite a serious one that definitely needs to be looked into. I thought I had already addressed it in change 2474397c63d86e3791ae4631862452c3bc5da527, but apparently that workaround does not always work (or no longer works).

**Comment by bjorn** [comment]
I think this issue was partially fixed by upgrading to Qt 5.5, which made the "Delete" key work and short up in the menu at the Delete action. With the above change, instead the "Backspace" key is visible in the menu (as it seems to be in other OS X applications, like Notes), but the Delete and Ctrl+D keys still work for deletion as well.

This resolves the main issue, but I'll have to do some general cleanup because there are more places in Tiled dealing with deletion.
