### ISSUE TITLE
Smarter behavior when dropping files on Tiled

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1031]
Currently, there's two things that can happen when dropping files on Tiled:
- When you drop them on the Tilesets view, it will open the New Tileset dialog so you can add them as a tileset (the assumption is that you're dropping images).
- When you drop files anywhere else, Tiled will try to open the files as maps (even if you're dropping images).

It would be smarter to detect whether the dropped files are maps or images (or external tilesets...), and treat them accordingly by either adding them as tilesets or opening them as maps.

Where it gets a little strange is when the user is dropping files from different categories at the same time... I'm not sure exactly what to do then.

**Comment by lutrinae** [comment]
Was this implemented? (dragging a png into the main interface and having it automatically add as a tileset or prompt the user asking them what they want to do) or has this since regressed? 

I just started using Tiled today for Gather.Town and was confused how to get tiles into the app.  Dragging a png throws the error "Error opening 'C:/.../image.png': Unrecognized file format." I tried File -> Open first to no avail,  but eventually found Map -> Add External Tileset.

**Comment by eishiya** [comment]
You still can't drop images onto the main interface, no. This issue was just about dropping images onto Image Collections to add them to the collection, and dragging external tileset files into the tilesets dock to add them to the map, both of which still work.

There's a separate issue for creating new tilesets from dragged images: #3107
