### ISSUE TITLE
Object size not set when using "Insert Tile" button

### ISSUE THREAD

**Issue by Uhfgood** [bjorn/tiled#1039]
I'm running version 0.11.0 in Windows 7 (Home Premium) and basically I will go to an object layer, select the "Insert Tile" button.  Then go to one of my tilesets, select a tile, and then place the object on the map.  At this point I click on the "Select Objects" button and then select my newly created object.  The size is set to 0 instead of the size of my tile.  This caused an issue in my game because it read 0 for tile width and height.

**Comment by bjorn** [comment]
Up until Tiled 0.11, it was not possible to resize tile objects and their size should be considered the same as the size of their tile. It basically should not have been visible in the UI, and actually this attribute was not used (and not written to the TMX file) for tile objects.

Resizing of tile objects is supported since Tiled 0.12, and it does set the initial width/height attributes of the object to match the tile size. This is reflected in the Properties view and the width/height attributes are now also written to the TMX file.

If Tiled 0.12 encounters a map file with tile objects that have their size set to 0, it will automatically initialize their size to match the size of their tile. So basically the default width/height of a tile object is not 0, but the tile size. I realized now that this is something I should still document, and this default could be relied on in the future to allow for writing smaller map files when the tile objects are not resized (which I expect to be the most common case).
