### ISSUE TITLE
Collision objects have the same id

### ISSUE THREAD

**Issue by IMMZ** [bjorn/tiled#1052]
Cannot sure certainly if it is bug but I think id - is usually unique identifier by which we can differ objects one from the other.
1) Open Collision editor
2) Draw two objects (Should we even allow to draw two objects? Haven't worked with physics yet, maybe more experienced gamedevs could answer for this question)
3) Generated tmx contains two objects with same id.

In my case objects on the screenshot below generates next *tmx content ![Screenshot](http://oi59.tinypic.com/16260eb.jpg)

```xml
<tileset firstgid="151" name="animation" tilewidth="73" tileheight="67" tilecount="15">
  <image source="animation.png" width="365" height="201"/>
  <tile id="0">
   <properties>
    <property name="anim_id" value="1"/>
   </properties>
   <objectgroup draworder="index">
    <object id="0" x="1.25" y="28.75">
     <polyline points="0,0 1.25,-5.25 14.25,-7.25 26.25,1 41.25,-4 58.75,-17.75 62.25,-12.75 52.25,-5 57.25,11.25 70.25,13.5 60,17 64,22.25 54.75,20.75 44.5,29 35.75,29.25 29.75,25 23,30.25 16.5,23 20.75,18.5 12.75,12.75 13,0.25 0,0"/>
    </object>
    <object id="0" x="38.25" y="30.5" width="15.5" height="15.5">
     <ellipse/>
    </object>
   </objectgroup>
```

**Comment by bjorn** [comment]
Hmm, that is because these object IDs are map-unique and as such managed (counted up) by the `Tiled::Map` instance. However, the object layer used to store the collision objects for a tile is not technically part of the map.

I guess it's not a critical problem, but the current behavior is not nice. Either we should fix those IDs somehow, or we should prevent them from being written out.

**Comment by T1mL3arn** [comment]
Can you fix it please? I want to use automatic unique id's for the collision layer objects. Now I write custom properties and track the id's manually for each object in collision layer! Moreover, I can't use my map parser (because it depends on id's) for collision layer without ugly tricks and hacks.

**Comment by bjorn** [comment]
@T1mL3arn Ah, that sounds nasty! I'll see if I can have a look at it soon.
