### ISSUE TITLE
Side bar pane collapses

### ISSUE THREAD

**Issue by genericptr** [bjorn/tiled#1055]
At seemingly random times while changing tabs or activating the application the side bar pane collapses like shown in the screenshot and I have to resize it manually to see any of the controls. I'm using Tiled on OS X 10.10.3 but this has been going on since 10.9 or earlier.

Any fix to this? Thanks.

<img width="367" alt="screen shot 2015-08-17 at 7 45 15 am" src="https://cloud.githubusercontent.com/assets/10937186/9306921/8b2210e0-44b8-11e5-88e4-5b55ae8271c1.png">

**Comment by bjorn** [comment]
Hmm, that is a strange problem and I've never heard of it before, nor did I see it happening myself. Of course, that doesn't help you get rid of it unfortunately.

You could really help by trying to narrow down the "at seemingly random times" thing to something more reproducible. Just to make sure, since you're mentioning only OS X versions, did you try different Tiled versions, or at least the latest one?

**Comment by genericptr** [comment]
I just tried to reproduce it like I have in the past and this time I figured it out. At least with 0.12.3 if I have the tileset grid view (not sure what it's called) scrolled down any amount then change tabs the side bar resizes. Can you reproduce this?

**Comment by bjorn** [comment]
@genericptr Thanks, that worked! Now indeed this is quite an annoying issue... will see when I get around to it.

**Comment by Crowbeak** [comment]
I'm having the same problem and have been meaning to post a bug report for the past couple of days.
