### ISSUE TITLE
Tileset path includes junk in JSON export

### ISSUE THREAD

**Issue by Crowbeak** [bjorn/tiled#1056]
![default](https://cloud.githubusercontent.com/assets/3011907/9345212/a9b6ea52-4649-11e5-9394-f8cb1dfc452d.png)

This happens when the JSON files are exported to a different directory than the Tiled map files are in. This is true for both the Mac and Windows versions.

**Comment by bjorn** [comment]
That is not junk, it's a relative file reference to the tileset, required for Tiled to know where to find the image when you open this map file.

If you mean the backslash in front of the slash, actually escaping the forward slash is valid in JSON as per http://www.ietf.org/rfc/rfc4627.txt (in the standard it's called a "solidus"). It does not seem required, but any conforming JSON parser should transparently turn this escaped slash into a regular slash character.

**Comment by Crowbeak** [comment]
:/ Any way something could be added to turn this path exporting behavior off? I don't like exporting to the same directory where my working files are because it's messy and hard to move to the actual game directory. I have a copy of the tileset in the working directory and we have one in the game directory; I'd far rather have it export the path relative to the Tiled map file than where the JSON is saved. It's counter-intuitive.

We also coded our own JSON parser beause the files are easy to read and had no way of knowing about that being standard.

**Comment by bjorn** [comment]
Adding an option to turn it off would be more work than for you to ignore everything up and including the last `/` character. Also, it would likely confuse people since that would cause Tiled to save JSON files that it won't be able to read back anymore.

Is there a reason why you're not using only JSON files, but rather using TMX and using JSON only as export? If this is because of external tilesets not being supported by the JSON format, then you could switch to JSON-only once Tiled 0.14 is out. :-)

**Comment by Crowbeak** [comment]
I can see why you would want to avoid confusing people. As for why I'm not using JSON for the working files, it's mostly habit. In many programs, you lose functionality by using a format other than that of the program, so I work in native file formats and export as necessary. I therefore just assume that's the case. If that's not true for Tiled, then I'm happy enough switching. It doesn't really matter what the file format is to me as long as functionality is unaffected. And since I don't know what an external tile set is I'm probably not using it. xD

**Comment by bjorn** [comment]
Of course you're entirely right to be careful with not using native formats. Tiled's JSON format is an exception in that I make an effort to have it support all of Tiled's features. But still there is an increased change of issues I have to admit, due to it getting less testing. Up to you if you want to switch. :-)

**Comment by Crowbeak** [comment]
Duly noted. Thanks!
