### ISSUE TITLE
Reach a level of funding where I can afford to work two days/week on Tiled

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1064]
The current support received [on Patreon](https://www.patreon.com/bjorn) and from sponsors allows me to work one full day per week on Tiled, which I've been doing every Monday since the start of June. It has allowed me to make quite some progress, and I'm very much enjoying to spend more time on Tiled.

Now I'd like to reach sufficient funding to work two full days per week on Tiled, but this seems challenging. The growth of new patrons has dropped significantly after reaching the first goal. I wonder why and what I can do to help it grow faster again. With Tiled being downloaded over 700 times/day on average, I don't think it's due to a lack of users.

There's several ideas:
- [x] Add a once-per-install popup to Tiled to tell people they can support further development, to make sure at least everybody is aware.
- [x] Set up a [Bountysource Salt](https://salt.bountysource.com/) page as an alternative to Patron, which allows login with GitHub and Twitter in addition to Facebook (the only social network supported by Patreon).
- [x] Provide more transparency about the combined budget and what I've been able to work on.

More ideas based on comments:
- [ ] Show more activity on the website. Possibly feature games made with Tiled and tutorials.
- [x] Add an auto-updater to Tiled to make sure people are aware of active development.
- [ ] Contact successful game developers that are known to have used Tiled about supporting further development.
- [x] Make the weekly development update sent to Patrons public.
- [ ] Get the Tiled support in various popular engines/frameworks updated to make new features in Tiled useful to more people.

Any other suggestions are welcome.

**Comment by Seanba** [comment]
I'm also surprised you're not getting closer to being fully funded (at the
5k level even). I know indie / hobby game developers work on the cheap but
even a buck or two a month from something like 10% of your users should get
you there.

The problem with once-per-install popups is that it's at the very beginning
if your relationship with Tiled (outside of upgrading). I'd nag users much
more than that, like every 10 times or so they save their TMX file or
something -- provided you give them a way to register as a patron and close
the nag out.

*Other ideas:*

   - More content on the Tiled blog. Spotlights of titles made by Tiled and
   tutorials and such. Something to give the impression that Tiled is active.
   (Or course, this is time consuming.)
   - An auto-updater built into Tiled will make people aware of ongoing
   development
   - Hit up the big guys making games with Tiled (Shovel Knight, for
   instance) and ask them to be a sponsor. IMHO, the developers that are
   successful with Tiled should consider $50-100 a month.

**Comment by bjorn** [comment]
@Seanba Thanks a lot for your thoughts and the additional suggestions!

My plan with the popup would be to show it after Tiled has been used at least a week for example. I don't want to nag people too much though, so if it's repeated then this will be explicit like through a "Remind me later" button and there would not be a registration process for patrons.

I definitely agree that there needs to be more showing of activity, and for sure an auto-updater would be a great help here. The website could indeed also show more activity. The blog seems like not the best place unless I would integrate it better into the site (currently nobody goes there and I am considering to deprecate it). Alternatively the activity could be shown on the forum. One problem is that right now, I'm showing my activity basically only to people who are already patrons, through the weekly update they get as a reward.

Talking to developers of successful games that used Tiled is probably a good idea, I'm just incredibly scared of coming over as a beggar. But I can plug their game in return so I should definitely get into contact.

**Comment by kheftel** [comment]
What if you also publish your development updates that get sent as Patreon emails to the blog? Does tiled have a twitter account? updates could go there too.

**Comment by bjorn** [comment]
@kheftel That would make them less personal and no longer an exclusive reward for patrons. But maybe the extra visibility is more important of course.

Actually in the early days of the Tiled forum last year I [wrote some weekly updates](http://forum.mapeditor.org/t/week-42-development-update/14), but I quickly ran out of things to write about. Of course the situation is different now that I have already a full day/week on Tiled, so I could try to pick this up again.

**Comment by kheftel** [comment]
It seems to me that exposing them to the world would be more like "hey, look at the cool stuff i'm doing that you're missing out on!", but I could be wrong........  of course it's up to you, just my $.02.

FWIW, if I were the dev of shovel knight, and you came to me, I'd be really interested in sponsorship, seeing how integral a tool Tiled is.

**Comment by atbigelow** [comment]
To chime in, I think visibility might be a good thing to work on initially. While I do like getting the weekly status updates for being a patron, if showing this information via public blog post and shared on social media is helpful, I'd rather that.

I tweeted the Yacht Club guys a few months ago about the patreon and they seemed excited about it. But it's not necessarily my place to go asking them more.

I think it might be worth it to also get Tiled support updated in the various engines out there. If people know how easily they could integrate Tiled into their projects, and that it would be possible for their money to directly impact a feature they care about, they might be more willing to send money.

**Comment by kheftel** [comment]
I personally, as a patron, don't care if the patrons-only emails go out to a wider audience. The more the merrier, get the word out, any publicity is good publicity! Of course, I'm only contributing $1/month so feel free to defer to higher-paying patrons ;).

**Comment by caiolopez** [comment]
Wasn't Axiom Verge also made using Tiled? That's huge.
My ideas:
a recommended contribution for successful games -- could be a one time payment after a quota is met;
a winrar-esque nag screen asking for people to donate (Wikipedia does that).

**Comment by bjorn** [comment]
@caiolopez Axiom Verge looks like an awesome game and was indeed made using Tiled (https://twitter.com/AxiomVerge/status/609639873209745408). Thanks for mentioning it!

@atbigelow, @kheftel I'll certainly be making the development updates public from now on. Thanks for sharing your opinions on that as patrons!

> I tweeted the Yacht Club guys a few months ago about the patreon and they seemed excited about it. But it's not necessarily my place to go asking them more.

@atbigelow Thanks for doing that! I'll think about how to approach them. They've been awesome in including me in the credits of their game, which also shows on [mobygames](http://www.mobygames.com/game/windows/shovel-knight/credits), where I now have [two titles associated with me](http://www.mobygames.com/developer/sheet/view/developerId,502039/). :-)

**Comment by sdrib** [comment]
How about pre-releases, earlier releases for Patreon/Bountysource users?

**Comment by bjorn** [comment]
@sdrib Hmm, but there's already the daily builds taking the latest developments to everyone who wants it on Windows, OS X, Fedora and Ubuntu. I don't think it's reasonably possible to limit this to just patrons, besides these builds help get early feedback about issues.

**Comment by nobody-special666** [comment]
Tiled is a wonderful start for a tool, and thank you for making it.

Tiled is still missing too many basic usability features:
Try using it to make an actual game and you immediately run into it's limitations:

-you can't align tiles and set tile offsets in case the tile image doesn't match the tile size
 this issue has been raised several times.
-you can't reorganize tiles (reorder, group/hierarchy tiles) once they've been added
-no multi-layer copy/paste
-no ability to create+edit tile brushes
-libtiled dependency on Qt. It should use standard c++ so it's cross-platform and people
 can just copy the code into their project/static link. 
 Nobody wants to make their game depend on Qt, so everybody needs to write their
 own parser to read+write the map files.
-no project support for managing all/shared resources: maps, tiles, brushes, etc.
-Tiled needs plugin support so developers can generate maps with code
 instead of drawing everything by hand.

You have developers willing to trade their personal time instead of donating money
to help make Tiled better for everyone, but you are neglecting them.
Pull requests sit for months with no feedback as to why you won't accept the patches, 
or help to make the minor tweaks needed to add said patches.
I don't know how many others there are like me who just maintain their own fork of Tiled,
with the features they need hacked in.

That's just my opinion, I may be wrong.
I wish you much success.

**Comment by Ablu** [comment]
@nobody-special666 that is a pretty harsh rating of the situation...

> Tiled is still missing too many basic usability features:
Before I am going to comment on the specific comments you made let me put this:
Tiled is being used in many games with a great success. One cannot deny that.


> -libtiled dependency on Qt. It should use standard c++ so it's cross-platform and people
> can just copy the code into their project/static link.
> Nobody wants to make their game depend on Qt, so everybody needs to write their
> own parser to read+write the map files.

I see no point in trying to create one map parsing library to rule all possible uses... People use Tiled for all kind of engines. Each has its specific limitation / requirements. A single library to serve them all would be impossible I think. Also I do not think that the majority of games created with Tiled are even based on C.
Also there already is a huge list of libraries supporting the Tiled map format here: http://doc.mapeditor.org/reference/support-for-tmx-maps/. Sure. Many are very limited... But for the most common use cases there is a library which serves you well.


> -Tiled needs plugin support so developers can generate maps with code
> instead of drawing everything by hand.

I think a plugin support for the sole reason to generate an entire map is probably the least interesting reason. I think the plugin support should rather aim to make certain engine specific editing routines faster/safer.

> You have developers willing to trade their personal time instead of donating money
> to help make Tiled better for everyone, but you are neglecting them.

As somebody who follows the Tiled development closely I can say that this is simply plain **wrong**. I think @bjorn is doing an awesome job accepting and helping with contributions to Tiled.


> Pull requests sit for months with no feedback as to why you won't accept the patches,
> or help to make the minor tweaks needed to add said patches.

If you look through the list of open pullrequests you can quickly see why those are open. The simple reason is that most people start a feature but do not finish it... and as a developer you should know that finishing somebody else code (usually the hard part is still left to solve) takes you a fair amount of time. Also note that even if you do not see comments on the pullrequest directly that does not mean that there is no feedback on the pullrequest. Sometimes stuff gets discussed on IRC directly.
So TLDR: Usually the pullrequests are simply not done yet and it still takes a significant amount of work to finish them.
@bjorn already picked up multiple pullrequests from contributors which were not done and polished them up (see the map object resizing for example). So far this is the first time that I am seeing somebody complaining about something getting ignored without a reason.



> I don't know how many others there are like me who just maintain their own fork of Tiled,
> with the features they need hacked in.

A few certainly do. But still they profit from the countless hours of effort which went into this piece of software. It is open source! You would not have been able to profit that much from a closed source paid software.

You of course listed some very valid points where Tiled has room for improvement. But most of those points are not easy to fix up to a level that they are ready to be included into a high quality software like Tiled in order to be useful for everyone. But well thats the whole point why Tiled needs more funding. Then those issues can finally be addressed somewhen.

Please excuse any typing errors or unintended harsh words. I am not a native speaker.

Regards,
Erik

**Comment by sdrib** [comment]
I agree with @Ablu here above.

It's easier to list features than to build them.

**Comment by nobody-special666** [comment]
Sorry, if I came across as harsh.
I am not attempting to imply that Bjorn is mismanaging the project or discrediting
the amazing accomplishment that Tiled is, 
or disagreeing that it's the best free map editor around so far.

Yes, I agree not all of these features are easy to add.

He asked for feedback why he's not reaching his funding goal.
I believe that is because Tiled still needs lots of work. I may be wrong.
Those were my gripes with Tiled and I listed them, maybe your alternatives are better.

I think helping developers get up to speed and coding standards required
to get their features in faster will build the community and ultimately the popularity+funding of the project.
I'm not talking about sitting on the side-lines requesting that other people do all the work.
It sounds like we all have the same motive, contributing to open-source for everyone.
That's all I'm saying.

I don't have any short-term ideas to increase funding.

**Comment by bjorn** [comment]
> You have developers willing to trade their personal time instead of donating money
> to help make Tiled better for everyone, but you are neglecting them.

I'm really sorry you feel this way and I realize there's a pull request from you waiting for more feedback among them. Yet, if you look at the numbers there remain only 17 pull requests open while I have closed/merged 266. And as @Ablu said, most of the ones that remain open still need work before they can be merged.

Were it not for the money coming in each month through Patreon, I would have needed to pretty much stop Tiled development at version 0.11. Instead, 2015 is already the most active year of development ever in terms of commit count, with still three months to go. Eventually, I will also get to the things you care about, but for now my focus is to finish as many loose ends as possible before adding more features. You can see the things I intend to deal with first in the [Tiled 1.0 milestone](https://github.com/bjorn/tiled/milestones/Tiled%201.0).

> He asked for feedback why he's not reaching his funding goal.
> I believe that is because Tiled still needs lots of work. I may be wrong.

You're certainly right that Tiled still needs lots of work, but I hope you are wrong that this is the reason I haven't reached my second funding goal yet.

> I think helping developers get up to speed and coding standards required to get their features in faster will build the community and ultimately the popularity+funding of the project.

I've spent countless of hours giving feedback on pull requests and over 100 people have contributed to the current version of Tiled. Of course I'd like to do even more, but for that I need time. Right now I have one day a week, and I try to spend it as effectively as possible.

**Comment by bjorn** [comment]
Hey, I made it to 2 days/week quite a while ago but it seems I forgot to close this issue. :-)

In the end, I think I made it to the goal thanks to several people stepping in to support me with $200/month to get certain features in (the priority request reward). The requests became most of the major new features in Tiled 1.2. In addition there are quite a few $100/month banner sponsors. When support from such larger patrons dropped significantly last year, [a short fundraiser](https://www.mapeditor.org/2018/05/16/help-fund-tiled-development.html) helped to stay on track, mostly thanks to increased support from existing patrons as well as many new ones.

Thanks to all of you for the feedback and support you have provided! I'll close this issue now, though there are things mentioned that are still worth doing. I'll see about opening separate issues for those.
