### ISSUE TITLE
Flexible column count for image collection tilesets

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1090]
For image collection tilesets, the tileset view is arbitrarily locked to 5 columns. This is because there is no tileset image to base the column count on.

I think the proper way to handle this case would be to adjust the column count to the width of the tileset view.

**Comment by bjorn** [comment]
While having a dynamic column count would be a nice option, I'll solve this issue by making the static column count configurable for now. Keeping it static can be preferable because it makes it easier to find tiles and to keep related tiles together - see https://github.com/bjorn/tiled/issues/1118#issuecomment-150494803.

**Comment by griest024** [comment]
@bjorn 

Whenever the tileset is opened, the view is 5 columns, no matter the actual column value in the file. It would be nice if Tiled respected the saved column value since the layout of my tileset is intended for 8 columns.

Should I open a new issue for this?

I'm using `json` files if that makes a difference.

**Comment by bjorn** [comment]
> I'm using json files if that makes a difference.

It appears you have found a bug, since it works for TMX / TSX files, but not for JSON files. I'll fix it up.

**Comment by bjorn** [comment]
@griest024 Fixed in 6ef5fa656f3fa576635dc6b80b6a5daacb15f390. I'm not sure when this will be included in a release, but I'll consider pushing an updated snapshot by the end of the day.

**Comment by griest024** [comment]
@bjorn thanks
