### ISSUE TITLE
Integration of Zopfli

### ISSUE THREAD

**Issue by alphaonex86** [bjorn/tiled#1093]
Hello,

Into the compression can you add Zopfli compression, the difference of size/compression time is huge than zlib BUT keep the same format as zlib.
Need plan put in thread.

Cheers,

**Comment by bjorn** [comment]
Hmm, [Wikipedia](https://en.wikipedia.org/wiki/Zopfli) says "Under default settings, the output of Zopfli is typically 3–8% smaller than zlib's maximum compression, but takes around 80 times longer." That's a huge speed penalty for such a small difference.

Of course it could be integrated into Tiled as an option, but since the format is still DEFLATE, you could also write your own tool that reads a map file and writes it back after recompressing the layer data with Zopfli. But if you care so much about file size, there's probably many other ways to save a lot more than by changing the compression algorithm (for example not using XML).

**Comment by alphaonex86** [comment]
Here is more of order of 30-70% with my own tool, I need do more test to confirm.

**Comment by bjorn** [comment]
> Here is more of order of 30-70% with my own tool, I need do more test to confirm.

Are you comparing to zlib's maximum compression or to its default compression level?

**Comment by alphaonex86** [comment]
comparing the -9, I will send the link when my tool is finish. Allow better overall compression of the whole file decrease the entropy.

**Comment by alphaonex86** [comment]
https://github.com/alphaonex86/CatchChallenger/tree/version-2/tools/tmxTileLayerCompressor

http://www.first-world.info/comment-augementer-votre-compression-sans-toucher-au-format-de-compression.html
Well, it's great at base64 level, regular at xml level 3-13%: average 5%, useless at my datapack level: too many image/tile, the size decrease have nearly no effect.

But I remain favorable at zopfli the integration to large map, for final release of tmx and it's easy to integrate into the editor it will a great change, and as you see the change are not very intrusive.

**Comment by bjorn** [comment]
Not intrusive but with very little benefit. Did you also measure what improvement we could have by using `Z_BEST_COMPRESSION` instead of `Z_DEFAULT_COMPRESSION`? This seems to still be quite fast so may be an option to do by default.

Otherwise, results would be much better if we added support for liblzma to Tiled, right?

Also, if you care so much about the final file size, you'll gain much more by doing a complete file compression before deploying, using whatever algorithm you fancy. Why would you spend so much effort trimming 5% off your tile layer data sections, when you can get much better results by just compressing the entire file?

**Comment by alphaonex86** [comment]
Yes, Z_BEST_COMPRESSION is better than Z_DEFAULT_COMPRESSION.
With lzma no, depends of the size compressed, with size < 500Byte, in general zlib have better ratio (and speed), > 5000Bytes lzma is clearly better. But yes, lzma is better in most case.
Because the compressed block is more difficult to recompress (wost with other algo) and introduce entropy.
Yes, entire file compression and ever multiple file at time compression is better (I transmit as tar.xz all the file). But to be accessible to stimulate the content editing I store the tmx directly into a folder

**Comment by bjorn** [comment]
@alphaonex86 Is this issue still relevant now that we have support for Zstandard and configurable compression levels?

**Comment by alphaonex86** [comment]
Hi, for me it's not relevant now due to support for Zstandard and configurable compression levels.
