### ISSUE TITLE
Add list of "used tilesets" to <layer> element in TMX

### ISSUE THREAD

**Issue by LearnCocos2D** [bjorn/tiled#1094]
Currently, a TMX reader does not know about which tileset's tiles are used on a given layer. In order to figure that out, the reader has to enumerate all tiles once and perform the necessary tileset lookup based on each tile's GID. Each tileset is then added to a set to avoid duplicate entries. Typically you'll end up with just one tileset though, so the whole enumeration is unnecessary and will only increase load time.

For rendering you may need to know which tilesets are used on a tile layer, for instance when the goal is to perform batch drawing (draw all tiles of the same tileset at once). But also to figure out the size of tiles on a tile layer, as this may be different from the grid size. 

The latter issue is what I need it for. In order to prevent rendering artifacts it may be necessary to scale up tiles every so slightly. And for that I need to know the size of the tiles on a tile layer, as well as whether all tiles share the same tileset (and verify that all tiles on the layer share the same tile size).

It would be nice to have a "list of used tilesets" recorded in the layer element in TMX files. This could be a simple list of tileset names or their "first GID" - either way would make getting the tileset references straightforward.

Example:

```
 <layer name="Tile Layer 1" width="40" height="40" usedtilesets="1,256,3987">
```

I take it that tileset names are not guaranteed to be unique so they couldn't be used for this kind of list.

**Comment by bjorn** [comment]
I would really prefer not to do this. For me it was already a stretch to add `tilecount` to the `tileset` elements, since such information is entirely redundant. It is the same here.

You've already described a solution to this problem yourself. Generally, a map reader already has to perform the tileset lookup for each gid (unless the tile information is indexed by gid, which would be good for speed), and I think keeping track of the set of tilesets on each layer is hardly going to make a difference. If it does make a big difference, please demonstrate it by showing measurements.

**Comment by bjorn** [comment]
Closing this for now.
