### ISSUE TITLE
Hexagonal cursor is showing up as Isometric

### ISSUE THREAD

**Issue by karai17** [bjorn/tiled#1097]
![image](https://cloud.githubusercontent.com/assets/590332/10125329/44238102-6546-11e5-9f96-27e21b0606a4.png)

**Comment by karai17** [comment]
The grid also shows up as isometric.

**Comment by bjorn** [comment]
This happens because your "Tile Side Length" map property is set to 0 (which is unfortunately the default), so with one pair of sides at length 0, the shape will be just a rhombus.

I think I should change the New Map dialog to feature this field when setting up a hexagonal map, and putting a better default in there.
