### ISSUE TITLE
Terrain feature doesn't work well with transparency-based tilesets

### ISSUE THREAD

**Issue by DaVince** [bjorn/tiled#1111]
Okay, so most of my tileset is based on the fact that there's a bottom layer and a top layer. This means that a lot of the tiles have transparency as such:

![terrainissue1](https://cloud.githubusercontent.com/assets/105533/10315365/2bbbacf0-6c5a-11e5-96c0-fe365a1e1ba3.png)

This becomes a problem with the Terrain feature, as I will demonstrate. Here are my rock and valley terrain definitions:

![terrainissue2](https://cloud.githubusercontent.com/assets/105533/10315363/2bbb2730-6c5a-11e5-82e0-5e8384e8e9f9.png)

![terrainissue3](https://cloud.githubusercontent.com/assets/105533/10315362/2bbaba0c-6c5a-11e5-8777-a29af2387fe1.png)

The issue is specifically with this transparent middle tile in the valley terrain definition:

![terrainissue4](https://cloud.githubusercontent.com/assets/105533/10315364/2bbbb722-6c5a-11e5-9a68-2a12072b0303.png)

I found you HAVE to select a middle tile for terrain to work at all. The issue is, the middle tile in this case should actually be *no tile*, because it's a fully transparent area. But since you *have* to define a middle area for the terrain to work, I've selected this middle tile which is completely transparent.

And then Tiled messes up. I can use the *valley* terrain just fine to erase the rock formations (although it will leave behind that transparent block in the areas I've drawn). But I can't place any *rock* terrain because it searches for that one transparent tile and that one transparent tile isn't anywhere on a clean map. The result is that the terrain brush draws like this when I try drawing *rock* terrain:

![terrainissue5](https://cloud.githubusercontent.com/assets/105533/10315539/38e6008c-6c5b-11e5-94c7-4ec6a08784ee.png)

I can only properly draw with the rock terrain when I fill the map up completely with the transparent tile outlined in red above. Obviously, that's not what I want; I want it to be able to work with an undefined/no tile.

**Comment by bjorn** [comment]
I think your main problem is that there is no terrain-aware eraser tool. You should not need to define this "valley" terrain at all because it's not a terrain, it's just nothingness.

So rather than selecting this type of terrain in order to remove pieces of rock, you need a way to replace the rock by nothingness and still correct the transitions as appropriate. This could for example be done by either adding some erasing mode to the terrain tool or supporting terrain transitions in the eraser tool. The former would be easier to implement, but I wonder how this mode should be made accessible in the interface.

**Comment by DaVince** [comment]
Hmm, you're right. I overcomplicated the issue.

Would the right mouse button be an option? Or otherwise an "erase terrain" button next to the "terrain" button. Those would make the most sense if you ask me.

**Comment by bjorn** [comment]
They're good suggestions, but the right mouse button is currently taken for capturing the terrain type from the map and another eraser tool seems like a bit much on the tool bar. Another option I'm considering is to have a "no terrain / erase terrain" entry in the Terrains window.

**Comment by bjorn** [comment]
And, I guess I should consider allowing to capture "no terrain" using the right mouse button.

**Comment by DaVince** [comment]
Yeah, that does sound like the best way to go.

**Comment by kheftel** [comment]
wow, I just found out from reading this that you can capture a terrain with the right mouse button! That's cool!

**Comment by Red-Eagle-LXIX** [comment]
You can create a terrain rule that will work with that tile set without having to pre-populate the map.
![image6](https://cloud.githubusercontent.com/assets/16145736/11581382/2acd1076-9a0f-11e5-8d85-10a53a6951fe.jpg)

**Comment by Red-Eagle-LXIX** [comment]
You can get both carving and outer edges to work, but you have to define your tile differently.
See the above definition and then add this one:
![image7](https://cloud.githubusercontent.com/assets/16145736/11582053/b451b114-9a17-11e5-928d-75ec96bd545e.jpg)

The way the terrain tool works just needs definitions it likes.  :)

**Comment by bjorn** [comment]
Closing this with the above commit, which now makes it possible to capture "no terrain" as well as selecting this via a new "erase terrain" button in the Terrains view, and paint with this to effectively have a terrain-aware eraser.

The main difference with the eraser is that it won't touch tiles that have no terrain defined, because they have no terrain to be "erased".
