### ISSUE TITLE
Convert/Export Tile Collection to Tileset

### ISSUE THREAD

**Issue by karai17** [bjorn/tiled#1115]
Tile Collections are the bane of my existence. As a Tiled library developer, I had to make the decision to not support Tile Collections due to their inability to be batch drawn, at least in my engine of choice. LOVE's Sprite Batches take in a single image or canvas and allow you to use Quads to grab pieces of that texture to add to the Batch. Using Sprite Batches improves my draw performance by several orders of magnitude.

Now, normally I wouldn't make this feature request and did indeed plan to write a plugin that gathers up tiles and draws them to a temporary texture to be used in batching, but Tiled already has image export support, and the ability to organize tiles from a Tile Collection into a neat little grid.

My proposal is for the ability to convert a Tile Collection to a Tileset and prompt the user to save the Tileset image somewhere.

**Comment by bjorn** [comment]
There are already many tools available for converting a tile collection to a tileset. Most well known is probably [TexturePacker](https://www.codeandweb.com/texturepacker), but tools like this also ship with engines like Urho3D ([SpritePacker](https://github.com/urho3d/Urho3D/tree/master/Source/Tools/SpritePacker)) and libgdx (also called [TexturePacker](https://github.com/libgdx/libgdx/wiki/Texture-packer)).

I'm somewhat reluctant to spend time developing another one as part of Tiled and consider this an optimization outside of Tiled's scope, since it can be perfectly applied without any changes to Tiled.

I think all you would need to do for optimizing the rendering of such maps, is to provide a way for the users of your library to specify how to obtain the texture information for each tile. Then he could hook in some packed texture lookup as an alternative to direct access to the original tile images.

**Comment by EdenIndustries** [comment]
If I can just weigh in with my two cents here, Tile Collections are a wonderous, amazing addition to Tiled for me, due to two issues that they fix with the tilesets based on an image that caused me endless grief while shipping Citizens of Earth:
1) Unless you plan things 100% perfectly, using tilesets based on an image will mean you're wasting memory. Will every single level that uses a given tileset need all of the tiles? Have you arranged things in the most perfectly optimized way such that every tileset is the precisely correct size to enable batch rendering with no changes needed (i.e. you don't later have to expand the canvas size to add more tiles)? Unless these things are true, you're wasting memory. Sure, maybe not a huge deal on PC's and home consoles. But a VERY big deal on 3DS/Vita/mobile. With the Collection of Image tilesets, you use only what memory you absolutely need to, and not a byte more. Beautiful. And while you are right that you lose batch rendering savings, I haven't noticed an appreciable runtime change, even on lower-end systems like the 3DS. So I'd probably have to side with Bjorn and recommend the optimization of your render engine.
2) It's impossible to do linear filtering of tiles if you want to zoom in/out when they're packed right up against each other in a single image since the edges of tiles will bleed into the other ones. Every solution I've tried to fix this (having spaces between the tiles with automatically generated padding of the edges of the border pixels being the most notable one) either produced wasted memory in the tileset (as above, a solution I couldn't accept), non-power-of-2 textures (which don't work on anything except the PS4 and most PC's), or problems tiling (also not so hot, obviously). But I will consent that there may be a solution out there that I just haven't thought of.

So I guess there is an optimal case where things are arranged perfectly (fixing issue 1), and you've come up with a solution to issue 2, but otherwise for me the Collection of Tiles tilesets are a wonderous, beautiful feature!

**Comment by karai17** [comment]
I'm surprised you don't notice rendering slow downs when drawing many tiles
individually over several layers as opposed to very few batch draw calls.
Implementing batching and draw range culling improved my render performance
by upwards of 7500x during my benchmarks. The engine I use runs on OpenGL
2.1 which has notable overhead compared to console graphics APIs which
might contain optimizations for you in the background.

**Comment by EdenIndustries** [comment]
Well what are the actual OpenGL calls being used? There's a vast performance difference just based on how you use OpenGL.

**Comment by karai17** [comment]
That I am unsure of, that is part of the engine which I know little about
the innards.

**Comment by kheftel** [comment]
in my experience using Starling (and thus OpenGL) for mobile games on android/ios, rendering a 20x20-40x40 map of 32x32px tiles was unacceptably slow until I implemented texture batching and drew an entire layer in one batch.  If I were using collection of images tilesets (which I don't, I use regular tilesets because then the batch is already created), I would definitely run the individual images through TexturePacker before including them in a game, if I expected to get acceptable performance.

**Comment by EdenIndustries** [comment]
Yeah my gut instinct might be that it's not using OpenGL in a very optimized way. SDL is also quite bad at it. In my experience, engines that implement an OpenGL renderer often do it in a way that sacrifices performance for ease of use. Which can be a hassle in the long-run. As a more personal example, I decided to write my own OpenGL rendered since I was unhappy with SDL's capabilities, but my first attempt was also HORRIBLE in terms of efficiency. But it's gotten much better over the years :)

**Comment by karai17** [comment]
Aye, LOVE uses SDL.

**Comment by EdenIndustries** [comment]
Ah that would probably explain it. So, I guess my recommendation would be don't use LOVE or SDL :). But yeah that is a difficult recommendation I suppose. Just to toss it out there, these days I'm interested in sharing our engine with other indie devs (if the circumstances are right, I'm not inclined to just open source it or anything). Depending on your interests and needs, perhaps I can help you out with a more efficient engine. Feel free to email me about it if you're interested.

**Comment by karai17** [comment]
I thank you for the offer but I am fairly invested in LOVE at this point.
Coding games in Lua is just too great, and I have built a large toolset
tailored for Lua and LOVE.

**Comment by EdenIndustries** [comment]
Fair enough, well best of luck with it!

**Comment by bjorn** [comment]
> Yeah my gut instinct might be that it's not using OpenGL in a very optimized way. SDL is also quite bad at it.

Important to note: SDL had a 2D rendering API that can use OpenGL as an optional backend. That is of course not the most optiomal way to use OpenGL, but you can also use raw OpenGL commands after creating window with SDL.

> Aye, LOVE uses SDL.

Yes, but surely it uses the OpenGL API directly?

> Ah that would probably explain it. So, I guess my recommendation would be don't use LOVE or SDL :).

I think this is a bad recommendation to make, at least when done solely on the assumption that it would make OpenGL usage slow. SDL has its strength in providing cross-platform direct access to OpenGL, plus input handling and many other things required by games. LOVE has its strength in providing easy to use game development primitives for a fast and very flexible programming language. Of course there are alternatives, but there are usually other reasons to choose one over the other than performance.

@EdenIndustries It was great to read that the image collection tilesets are such an asset to your workflow, btw. I'm really glad to hear that!

I will just add that of course it makes sense to batch together draw calls, if draw calls are a performance concern in your game. I just want to stress again that this optimization can be made, also for image collection tilesets, without the help of Tiled. Be it by using a tool like TexturePacker that I mentioned earlier, or by placing images in an atlas at runtime (which is the approach taken by the Qt Scene Graph). Either way it does not require a special export of the map, because the image names are enough to determine what to render.

I'll close this issue now, because implementing this feature request properly would be quite a project, which would duplicate existing efforts and it's not currently part of the scope of Tiled.

**Comment by EdenIndustries** [comment]
> I think this is a bad recommendation to make, at least when done solely on the assumption that it would make OpenGL usage slow. SDL has its strength in providing cross-platform direct access to OpenGL, plus input handling and many other things required by games. LOVE has its strength in providing easy to use game development primitives for a fast and very flexible programming language. Of course there are alternatives, but there are usually other reasons to choose one over the other than performance.

Right, I should have clarified the recommendation as, "If you are concerned with render peformance, and your render performance is bad in LOVE or SDL, don't use the rendering-specific parts of LOVE or SDL." I still use SDL for input, despite ignoring the rendering parts of it.
