### ISSUE TITLE
Bug with using "Remove Tiles" from a Collection of Images Tileset

### ISSUE THREAD

**Issue by EdenIndustries** [bjorn/tiled#1118]
It seems like removing a tile from a Collection of Images tileset that is shared amongst multiple levels can cause errors. 

Repro steps:

1) Create a level with a single tileset of the Collection of Images type. Place one of each tile in the level. Ensure the tileset is exported. Save the level. Then, save a copy of the level.
2) Ensure only one of these 2 levels is open (i.e. only the original, or its copy)
3) Import this shared tileset and remove at least one tile that's not at the end of the tileset. For the purposes of illustration, let's assume there are 25 tiles in the tileset, and we have chosen to remove the tiles with id's 10 and 11. 
4) Export the tileset. Notice that all tiles formerly with id's greater than 11 have all now shifted 2 id's down, so to speak. The tile that was assigned id 12 is now 10, 13 is now 11, and so forth.
5) Open the other level. Notice that all tiles that were placed with id 10 have been replaced with the tile formerly at id 12, all tiles that were placed with id 11 have been replaced with the tile formerly at id 13, etc.
6) Tiled may also crash while viewing this error.

**Comment by bjorn** [comment]
Hmm, indeed this is a somewhat tricky issue to solve. Well except for point 6, which indicates a somewhat serious bug which should be avoidable.

So there's two ways of avoiding this:

* As a user, you can make sure all maps are loaded at the time of making this change, and save them all after making this change. The new "Save All" action comes in handy for this. Currently the dangerous part is that you may be removing tiles that were actually still used be other maps, since Tiled only checks the currently selected map. This is probably one way of getting it to crash. The main solution here is to make the import step at point 3 unnecessary (issue #242) and check all maps that refer to this external tileset (though it would not be possible to check unopened ones, which is where support for "projects" would come in).

* Don't shift the tiles to fill the gap, but instead just leave a gap in the tile IDs. This way the references of other maps will largely stay intact, apart from references to the actually removed tiles. This would require changing the list of tiles in the tileset to a map of tile ID -> Tile instance. It's a change I've considered but so far have been avoiding.

Opinions on these solutions or suggestions for other approaches are welcome.

**Comment by EdenIndustries** [comment]
>As a user, you can make sure all maps are loaded at the time of making this change, and save them all after making this change. The new "Save All" action comes in handy for this. Currently the dangerous part is that you may be removing tiles that were actually still used be other maps, since Tiled only checks the currently selected map. This is probably one way of getting it to crash. The main solution here is to make the import step at point 3 unnecessary (issue #242) and check all maps that refer to this external tileset (though it would not be possible to check unopened ones, which is where support for "projects" would come in).

Although I agree this would work, I don't think this is really a viable option (unless support for "projects" allows you to check unopened files). In a production setting this seems really hard to ensure, and the consequences of forgetting even a single level are pretty annoying (essentially the level is totally messed up, and you'll have to go back through source control versions to repair it, assuming such versions are available). 

>Don't shift the tiles to fill the gap, but instead just leave a gap in the tile IDs. This way the references of other maps will largely stay intact, apart from references to the actually removed tiles. This would require changing the list of tiles in the tileset to a map of tile ID -> Tile instance. It's a change I've considered but so far have been avoiding.

I like this solution since it all takes place behind the scenes and the user isn't burdened with having to remember a bunch of requirements, as in the first option. I'd be happy to assist with the development of this solution, if that'd help.

**Comment by bjorn** [comment]
> (unless support for "projects" allows you to check unopened files)

It would allow it because it would provide a means for Tiled to know about other maps in your project. But I agree this is a rather unreliable solution.

> I'd be happy to assist with the development of this solution, if that'd help.

I'm currently already doing changes in this area related to dealing with broken tileset links in maps, so I think it would make sense to do such a change as part of that. But when I don't end up doing it just yet, you could give it a try by changing the `QList<Tile*>` of `Tileset` to a `QMap<int, Tile*>` and looking at the consequences.

**Comment by considine** [comment]
Hi, I am just trying to start contributing, after viewing some of the source code and experimenting with the interface. Forgive me for being slightly out of the loop, but what is the benefit of switching from QList to QMap? I understand you are trying to save the maps, but do the key parts do not correspond with other maps? Please let me know so I can try to help

**Comment by bjorn** [comment]
@considine If we use a list rather than a map, then removing tiles from the array causes the other tiles to shift places (affecting the tile IDs) and for shared (external) tilesets this means the tile references of other maps will break. Of course, we could also keep it a list but set some pointers to `nullptr` instead of shifting all the tiles, but after many tile additions and removals this could start wasting memory (unless empty spaces are re-used, but that would mean references in other maps could silently start pointing to different tiles).

**Comment by bjorn** [comment]
So in the above change I think I did most of the work required to close this issue. The tileset now stores a map of tile ID -> Tile instance. It also keeps track of the next available tile ID. When tiles are removed from a tileset, other tiles are now unaffected.

Apart from the issues mentioned in change 1a2de3d, there remains the issue that changes to shared tileset instances can lead to crashes because only the currently active map is checked for references to the removed tiles. This should actually be checked for all maps referring to the tileset being changed, which can include not only other maps but also the active tile stamp and loaded persistent tile stamps. I really wonder what's the best solution there.

**Comment by EdenIndustries** [comment]
Awesome! If/when it's in the master branch I'll put it through some heavy testing. I've got some local code for repositioning tiles within the tileset that'll depend on this too ;)

**Comment by bjorn** [comment]
@EdenIndustries Well, you don't need to wait until it's merged to master. :-)

I'm curious, what will your repositioning code do and how will it work?

**Comment by EdenIndustries** [comment]
@bjorn Yeah I know I don't have to, it's more just that I have enough tasks on my plate at the moment that it felt like a natural time to update :). But I may do it earlier if the moment strikes me!

And then regarding the repositioning code, I basically copy/pasted your move layer code, but applied it to tile images in the tileset. I even took the images and just rotated them and slapped them on the tileset window. Basically you select a group of tiles and can move them left or right. It supports undo/redo, highlighting/moving multiple, etc. It was working great until I discovered this bug relating to removing a tile from the collection (which affected moving them as well).

**Comment by bjorn** [comment]
@EdenIndustries What is your plan with the moving? Without a way to move tiles while not affecting their ID, there will still be the problem of other maps ending up referring to the wrong tiles, right? Do you think that maybe the order of the tiles needs to be separated from their ID?

**Comment by bjorn** [comment]
@EdenIndustries Also, how will this moving work once #1090 is implemented? Would you be in favor of a fixed (configurable) column count for image collection tilesets, or is it alright to wrap them dynamically?

**Comment by EdenIndustries** [comment]
@bjorn Regarding seperating the order of tiles from their IDs, yes that's the plan and what I had begun doing before realzing that I'd probably be better off waiting for this issue to be resolved so that I was operating with a more complete model of how the tileset collection would function. And regarding #1090, I actually think I prefer a fixed column count. That way, after I finish up the tile moving code, we can position tiles within the collection to maximize work flow by placing frequently used tiles together and in meaningful positions relative to one another.

**Comment by EdenIndustries** [comment]
I grabbed the latest build and this seems fixed! And I was able to implement moving the tiles around the tileset. So things are looking pretty great :)

**Comment by bjorn** [comment]
@EdenIndustries That's great to hear! Would you be interested in opening a pull request for the movement feature?

**Comment by EdenIndustries** [comment]
@bjorn Yeah I would be interested in opening a pull request, though my last one didn't go so smoothly and I'd have to pull all the code I have in there for our other custom features that don't make sense in the main branch of Tiled. But I'll see what I can do :)
