### ISSUE TITLE
Lua: Inconsistent property names

### ISSUE THREAD

**Issue by karai17** [bjorn/tiled#1130]
There are several places within the Lua export that have similar values but varying names. Examples include:

* Tile Layers have x/y properties and offsetx/offsety properties.
* Object Groups have no x/y properties but do have offsetx/offsety properties.
* Image Layers have x/y properties but no offsetx/offsety properties.
* Tilesets have a tileoffset property with nested x/y properties.

Here are some of my proposals:

1. From my understanding, the Tile Layer's x/y properties are a hold over from Java Tiled's functionality to trim a layer. I propose renaming these x/y properties to something less ambiguous such as trimx/trimy.
1. Image Layers should rename x/y to offsetx/offsety.
1. Tilesets' tileoffset property should be flattened and renamed to offsetx/offsety.

Some of these would probably fit in with the TMX spec, too.

**Comment by bjorn** [comment]
As a personal reminder, I want to note that this not only needs consistency work in the Lua format, but also internally. The "Move Image" tool, that is currently only active for the image layer, could also be used for editing the offset of tile layers and object layers once it changes the same set of internal properties.

**Comment by bjorn** [comment]
I won't change the tile offset thing, because while it may make sense for consistency, currently the Lua, JSON and TMX formats all store tile offset in this way and I don't want to change all of them. It's just because it's a rather insignificant change while still negatively affecting many people when changed.

The layer offset was somewhat different, since the feature was so new and unifying it with the other layers internally in Tiled also had clear advantages.
