### ISSUE TITLE
[Request] Hold Space to drag  

### ISSUE THREAD

**Issue by McFarts** [bjorn/tiled#1142]
Hey guys, my suggestion is to let us hold down the space button and drag around the map. This would help so much when creating as compared to using the scroll bars, especially for large maps.  Think of Photoshop and how when u zoom in, you can hold space and then drag wherever.

Hope this gets implemented! And if it's already a feature, I apologize still learning the ropes

**Comment by bjorn** [comment]
Did you try it? Panning with space bar is supported since years.

**Comment by kheftel** [comment]
one thing I've noticed is if the main map window doesn't have focus, the
space bar is not detected.  This requires a click on the map to activate,
which sometimes then draws a tile you didn't want to, if your last click
was selecting a tile from the tileset.  Minor inconvenience but a common
use-case - you decide you need a different tile, so you select it from the
tileset, and then try to scroll somewhere else on the map to draw it, but
it doesn't work until you click, which draws the new tile where you
possibly don't want it....

**Comment by bjorn** [comment]
@kheftel Hmm, good point, I didn't know or had forgotten that the map view needs focus, which is indeed annoying since it's sometimes impossible to focus it without changing something. Well, apart from using the middle mouse button, then you may as well just pan with the middle mouse button.

I'll probably end up changing it around so that you need to hold Space and then left-click to pan, instead of just needing to press Space. I based the current behavior on GIMP, but I think most other applications work with Space + left-click.

**Comment by kheftel** [comment]
space + click would be more intuitive for me, since Photoshop and all adobe
products tend to do that.

Didn't realize the current behavior was modeled after GIMP, since I don't
often use it (since I already have a creative cloud membership for work, I
might as well use it...).

That would be awesome, since the tileset window doesn't respond to space
anyway.

**Comment by McFarts** [comment]
Hmm, when I do space and click it toggles the visibility of my layer. 

Edit: Oh @kheftel  is right, I had to place a tile before I could drag (or have the map active) my bad.

I suggest something maybe similar to Photoshop where you can drag in a 360 degree around the map instead of just being limited to the scrollbars, that would be so smooth.  

I'll close this since the feature is already implemented at the basic level, apologizes
