### ISSUE TITLE
Visualization problem with Tile Stamps

### ISSUE THREAD

**Issue by EdenIndustries** [bjorn/tiled#1146]
I've recently been playing around with the Persistent Tile Stamps you added in 0.13.0, and while they are very cool one thing I noticed is that the visualization of the tile image in the tile stamp window seems to only use the 32x32 pixels from the lower-left portion of the tile. This can make knowing what you have in the tile stamp pretty difficult.

**Comment by bjorn** [comment]
Hmm, I can't reproduce this with Tiled 0.14.2, but it seems broken on the master branch. I'll have to check what broke that and make sure to fix it. Thanks for the report!

**Comment by bjorn** [comment]
Arg, this is more complicated that I expected because Tiled no longer keeps track of which tiles exactly are used on a map, so it no longer known when a map is larger than its grid due to tiles extending outside of it.

So to implement this, the thumbnail renderer will need to go over all tiles used on the map to take into account any larger ones.
