### ISSUE TITLE
Comodo antivirus picks up tmxviewer as malware on windows.

### ISSUE THREAD

**Issue by Mast3rPlan** [bjorn/tiled#1180]
Happens with the version of January 17th 2016
Link to virustotal report: https://www.virustotal.com/en/file/833e207156ee1746da4633150fea8b4250a1ce29c8332376fce45956b5e06e56/analysis/1453214738/

**Comment by bjorn** [comment]
Most likely a false positive, since the builds happen on a controlled environment at [AppVeyor](http://www.appveyor.com/) and only one other virus scanners found an issue and it's a different one, probably also a false positive.

You can help by submitting the false positive here:

https://www.comodo.com/home/internet-security/submit.php

Thanks!

**Comment by Mast3rPlan** [comment]
I assumed so, I have submitted the binary at the url you provided.

**Comment by bjorn** [comment]
Awesome, thanks again!

**Comment by Mast3rPlan** [comment]
I received the following email:
```
Hi,

This is to inform you that false-positive with
<tmxviewer.exe> (SHA1: <f34b38540cf410a4fe57bee01ca9fb38bea0033c>)
has been fixed.
You can update to AV database Version <23994> of  Comodo Internet Security Version<8.2.0.4792> and confirm it.
```

**Comment by bjorn** [comment]
Nice!
