### ISSUE TITLE
The JSON map doesn't store the right image ID of a tileset

### ISSUE THREAD

**Issue by JohnCarmack** [bjorn/tiled#1208]
Hi everyone,

i'm using tiledmap exported to JSON that i can read correctly, but now i'm using a tileset that contains a some 16x16 sprites that i put in my map in tiledmap editor. Now, i can read a map where a tileset contains only one sprite but if my tileset contains several sprites it's impossible to read. Indeed, tileset has "firstgid" information and in the data array it stores data like this "data":[1203, 0,..etc]" to know if we draw a precise tileset but we do not have the information of which tile is draw, the first ? the second ? and so on...Because it's drawing the entire tileset, here's the problem. Is there a way of knowing which tile's ID is draw on the map of a tileset ? Maybe this information is not given in JSON map format

Thanks.

**Comment by TheoConfidor** [comment]
This sort of feature would be very useful. Perhaps it could be possible to customize the Id of each tile and have that custom string exported in place of the default id when exporting to JSON.

**Comment by bjorn** [comment]
> This sort of feature would be very useful. Perhaps it could be possible to customize the Id of each tile and have that custom string exported in place of the default id when exporting to JSON.

That has nothing to do with the problem @JohnCarmack is talking about. I don't see what would be the benefit of customizing the ID of each tile. If you would allow that, you can no longer store tile flipping information in the IDs. Also, you'd have to make sure no duplicate IDs are used, otherwise a map can't be read back in properly anymore.

What @JohnCarmack is asking about, is how to go from a local tile index like "10" to a location on the tileset. For this, one first needs to calculate the number of tile columns in the tileset. Then, you can calculate the row/column of the tile on the tileset, from which you can derive the area of the image to draw:

```c++
int columnCount = (tilesetWidth - margin + spacing) / (tileWidth + spacing);
int column = tileIndex % columnCount;
int row = tileIndex / columnCount;
int tileX = margin + column * (tileWidth + spacing);
int tileY = margin + row * (tileHeight + spacing);
```

Since I now finally got around to answering this, I'll close this issue. This should be included in the TMX reference, though.
