### ISSUE TITLE
Eraser tool on empty cell makes map changed.

### ISSUE THREAD

**Issue by IMMZ** [bjorn/tiled#1209]
I think map shouldn't be shown changed when we erase already empty cell.
Steps to reproduce:
1) Create any empty map 10x10 (or any other size)
2) Take an eraser tool and click on any cell you want.
Current behaviour: map is shown changed ('*' character near the map's name).
Expected: map is not changed.

**Comment by bjorn** [comment]
Well, I might agree, but only if we decide that any tool that tries to apply some kind of modification that does not end up changing anything should somehow avoid adding an undo command until the map is actually changing. But I wonder a little about how doable that is in practice. Also, I doubt it would be more intuitive since if you don't always get an undo command, then you can undo only operations that actually changed something.

Imagine if your text editor would silently ignore operations that didn't end up changing the actual text, like pasting a piece of text into a selection that was already the same, or typing the same character that's already there while in overwrite mode. I don't know of any text editor that works this way.

If you use the eraser in GIMP, it also doesn't wait with creating an undo command until you hit an actual pixel.

So all in all, I think the current behavior is quite reasonable. Do you have any examples of tools that work otherwise?

**Comment by IMMZ** [comment]
I have no any examples in other programs and I agree with you as with more experienced user of graphic tools. I think this issue could be closed now.

**Comment by bjorn** [comment]
Alright. :-)
