### ISSUE TITLE
HUGE BUG - Does NOT Support Unity 5.3

### ISSUE THREAD

**Issue by xtilly5000** [bjorn/tiled#1216]
While in unity 5.3 it said its not supported. Support Unity 5.3 plz

**Comment by Seanba** [comment]
A couple of things:

1. Tiled is a self-contained application unrelated to Unity
2. I suspect you're talking about Tiled2Unity, which I authored, but this is the wrong place for that discussion.
3. If you are talking about Tiled2Unity it does indeed work in Unity 5.3
4. "it said its not supported" -- who are the "it" and "its" you are referring to? Not supported how? Please copy and paste the specific error you're talking about.
5. If you are using Unity's Web Player as your build target then switch it to something else (like PC, Mac & Linux). Unity has deprecated the Web Player and it is no longer being supported. (The error messages printed by the Tiled2Unity scripts in Unity will have pointed that out already). 

If you're experiencing a different problem with Tiled2Unity then you can email me, leave a comment on my blog, or a comment on Tiled2Unity's github page. Otherwise you'll need to identify what technology you are using to export Tiled maps into Unity and bring it up with those folks.

Best,
Sean

**Comment by bjorn** [comment]
Thanks @Seanba for explaining things. Since no further information seems to be forthcoming, I'll close this issue now.
