### ISSUE TITLE
Script editor/large custom properties for Lua?

### ISSUE THREAD

**Issue by genericptr** [bjorn/tiled#1226]
I've added support for Lua to my game but I don't see any good way to add scripts to the maps in Tiled because the object properties I have been using only support single lines of text.

Any chance of making a way to insert Lua scripts into Tiled? Multiple lines of text could mess up the XML exporting though since properties are saved as tag attributes but that could be changed I guess. A little button to the right of the text field or another "script object" tool with its own inspector could work. Seems like a pretty common request though so maybe this has been asked before.

Thanks for considering.

**Comment by bjorn** [comment]
Yep, that's already been requested many times and is covered by issue #205.

It's definitely something I'll try to get around to soon!



> Multiple lines of text could mess up the XML exporting though since properties are saved as tag attributes but that could be changed I guess.

This is already solved since Tiled will save multi-line properties as text between `<property name="...">` and `</property>` elements. The tricky bit is that most 3rd party TMX parsers probably don't support this yet since so far it has been impossible to create such property values without manually editing a map file.

**Comment by bjorn** [comment]
Note that even if Tiled supports editing of multi-line property values, it will never be a good script editor. So for anything that is more than a dozen lines you'll probably want to refer to external files rather than having the scripts embedded in the map file.

**Comment by genericptr** [comment]
Thanks for the reply. Maybe just a little button to edit in an external editor would be easiest and the most powerful for users. Keeping the association between between map objects and scripts is what's most important anyways. The solution we use now is setting an ID field on the object and then having to reference that in an external file which makes for some confusing relationships that are hard to keep track of.

**Comment by bjorn** [comment]
> Maybe just a little button to edit in an external editor would be easiest and the most powerful for users.

I'll indeed have to add such a button for custom properties of "file reference" type.

> The solution we use now is setting an ID field on the object and then having to reference that in an external file which makes for some confusing relationships that are hard to keep track of.

Rather than using a custom ID field, did you consider using the built-in object IDs or the name field? Using the built-in ID field avoids needing to explicitly set this property, but it's still not easy to find objects by their ID. Using the name field should make objects a lot easier to find (by labels or in the Objects view).

**Comment by genericptr** [comment]
Thanks, I didn't see there was a name property that had that feature, that makes things easier for sure. The main problem I think people are trying to solve is storage of the scripts (even more so than editing) so we don't need to implement an additional loading system from some other format.
