### ISSUE TITLE
Should Not Add Duplicate Tilesets (or atleast warn and ask)

### ISSUE THREAD

**Issue by reapazor** [bjorn/tiled#1227]
When adding images to a tileset, if the file is identical to an already existing item it should warn per item (add anyway, ignore, cancel) 

There may be use cases for duplicates of the same tiles, however at times when you are dumping out parsed tilesets and adding in large number of images, having duplicates be created is frustrated.

**Comment by lazybotter** [comment]
Good shout! There should be a warning to overwrite the file.

**Comment by bjorn** [comment]
@lazybotter As far as I understand this isn't about overwriting anything (Tiled should already warn about overwriting in all relevant cases, so please let me know if it isn't somewhere).

This issue is rather about Image Collection tilesets, where it does rarely make sense to add the same image twice to the collection. Since this is almost never what you want, it does indeed make sense to check against this case. I wonder if we can't just silently ignore this, even.

**Comment by reapazor** [comment]
:) Indeed i get no error/warning when adding image.png to an existing collection with image.png in it already.
