### ISSUE TITLE
Compiling under Ubuntu: '/usr/bin/ld: cannot find -lGL'

### ISSUE THREAD

**Issue by 190n** [bjorn/tiled#1229]
I'm trying to compile Tiled under Ubuntu 15.10. I've installed all the dependencies, but when I run `make`, it outputs this error:

```
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:248: recipe for target '../../lib/libtiled.so.1.0.0' failed
make[2]: *** [../../lib/libtiled.so.1.0.0] Error 1
make[2]: Leaving directory '/home/ben/Downloads/tiled-0.15.2/src/libtiled'
Makefile:48: recipe for target 'sub-libtiled-make_first-ordered' failed
make[1]: *** [sub-libtiled-make_first-ordered] Error 2
make[1]: Leaving directory '/home/ben/Downloads/tiled-0.15.2/src'
Makefile:43: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 2
```

Does anyone know how to fix this?

**Comment by bjorn** [comment]
That means it can't find the OpenGL library. I think which one you need [may depend on your video driver](http://packages.ubuntu.com/search?searchon=contents&keywords=libGL.so&mode=exactfilename&suite=wily&arch=any), but normally `libgl1-mesa-dev` should work fine.

Since I'm not sure if this package will work for people using NVidia drivers for example, I don't know how best to include this in the `README.md` file.

**Comment by 190n** [comment]
This was on my laptop, which has an AMD graphics card. The drivers package is `fglrx`. There was another package called `fglrx-dev` which I installed, but it didn't help. I'll try `libgl1-mesa-dev`.

I also get this same issue on my desktop, which has an Nvidia graphics card. But my desktop runs Debian. I'll try installing [libgl1-nvidia-glx](https://packages.debian.org/search?searchon=contents&keywords=libGL.so&mode=filename&suite=stable&arch=amd64).

**Comment by 190n** [comment]
So, I just updated the drivers on my desktop and it works now. I haven't had a chance to try anything on my laptop yet.

**Comment by bjorn** [comment]
Linking to libGL should no longer be required since 3fb30ab01bbf4ae4a559172cdf977d65b8217859.
