### ISSUE TITLE
JSON export does not include "encoding" property for CSV tile layers

### ISSUE THREAD

**Issue by parasyte** [bjorn/tiled#1246]
See: https://github.com/melonjs/melonJS/issues/788

When exporting a map (to JSON) that uses the "XML" tile layer format, the layer is converted to CSV, but the `encoding` property is undefined. Similarly, when exporting a map that uses the "CSV" tile layer format, the `encoding` property is still missing. The property only appears when using the Base64 formats.

This breaks our map loader, because it expects the default encoding (when the property is undefined) to be XML. @obiot provided a state table in the linked ticket; only TMX/CSV defines the `encoding` property.

**Comment by bjorn** [comment]
The "XML" and "CSV" encodings make no sense in the JSON export, so when the user picks it anyway it is ignored and the default JSON array representation is used instead.

I don't consider it a bug that the JSON export doesn't include an `"encoding": "csv"` field. CSV is what it looks like and what Tiled uses to describe this, but it's just a JSON array so no real CSV-parsing is involved as is the case when CSV is used in the TMX format. So actually writing out the property like that would also break your code, since it would cause `decodeCSV` to be called on an array object.

I think your issue is that you've got "xml" as the default for both TMX and JSON maps, whereas in fact "none" should be the default for JSON maps.

**Comment by parasyte** [comment]
We attempt to normalize XML to JSON (the latter is natively usable without actual parsing). I agree that we have to change the default layer encoding, though.

Good point you mention about layer data in JSON; there is no additional parsing required. `encoding == undefined` does actually make sense. I didn't even notice it was just an array. You're right, there's no bug.

**Comment by obiot** [comment]
wait, I don't really agree here, if you look at the below, the issue is that the default should be the same for both format then, which is not the case.

> I think your issue is that you've got "xml" as the default for both TMX and JSON maps
correct
> , whereas in fact "none" should be the default for JSON maps.
but what is the default for TMX then? if you take "none" as the default, then here below for TMX `encoding` should be set to `XML1, and then `encoding` should be set to `none` for the second case (CSV)

TMX Export  :
* XML:
    '`encoding = undefined `

    `<data> <tile gid="12"/>  <tile gid="12"/>   <tile gid="12"/> ... </data>`
* CSV :
    '`encoding="csv"`

    `"data":[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, ... 12])`

JSON Export 
* XML : 
    '`encoding = undefined `

     `"data":[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, ... 12])`
* CSV : 
     '`encoding = undefined `

     `"data":[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, ... 12])`

**Comment by parasyte** [comment]
@obiot The point is there's no parsing required for JSON. The data isn't encoded in any way.

BTW, the TMX/CSV example you've provided is incorrect (it shows a JSON array, not a CVS string). Parsing is required for both TMX examples.
