### ISSUE TITLE
Cannot set tileset columns.

### ISSUE THREAD

**Issue by Nsheppard01** [bjorn/tiled#1249]
Attempting to load this png file as a tileset does not give me all the sprites.

![mimihex](https://cloud.githubusercontent.com/assets/7131421/14569769/93bcb966-02f5-11e6-8a4a-9ea44ea519a8.png)

The column number is greyed out and fixed at an incorrect value, and it's not even displaying all of the sprites in each column.

![screenshot - 04152016 - 10 36 39 am](https://cloud.githubusercontent.com/assets/7131421/14569900/60caaf8a-02f6-11e6-87e1-20995bf35735.png)

Trying to edit the file to have a different amount of columns does  not fix anything. Before I had 5 columns and it was fixing itself to 4.

Is this a bug or am I doing something wrong?

**Comment by bjorn** [comment]
It's because if you set your tile width to 16 pixels, the last column is incomplete. After 3 16-pixel wide columns, the last column is only 15 pixels and Tiled will not include partial tiles in the set.

Of course, your tiles aren't partial at all, but they're not 16 pixels wide. They are 15 pixels wide, with a one pixel spacing. So the tileset should work just fine if you specify 15 px for tile width, and 1 px for spacing.

**Comment by Nsheppard01** [comment]
Ahh that fixes the column issue, but the bottom row is still rendered as
white boxes. So what's wrong there?

**Comment by Nsheppard01** [comment]
Fixed it by removing gaps and making sure each sprite has a consistent
bounding box.
