### ISSUE TITLE
Object properties.

### ISSUE THREAD

**Issue by AndyGFX** [bjorn/tiled#1260]
Hi,

predefined object properties assigned to object, which are not changed (grey text) in properties window, are not saved to file.

Best regards,
O.

**Comment by bjorn** [comment]
This is intentional, since doing so would result in a lot of needless duplication of information.

If you need this information, you will need to parse also the `objecttypes.xml` file and find the properties there. You can tell Tiled to place this file inside of your project directory, to make this easier. If you're using [Tiled2Unity](http://www.seanba.com/tiled2unity), it has an option to copy this information during the conversion.

**Comment by AndyGFX** [comment]
Hi,

I untederstand when we talk about tile properties, but properties on object
in scene in Object layer, when is not set different value as is defined via
Obejct types Editor, then is not saved do tmx file. Then I can't find/parse
value, because is missing in tmx. For reading tmx I have used TiledSharp.

O.

**Comment by bjorn** [comment]
The same applies. Just imagine you have an "Entity" object type, and it has a dozen or so possible properties with certain default values. Normally, your engine already knows the default values, and including them in the map file for each entity would result in a lot of repeating information that bloats the file. Hence, only when the value is explicitly set it will be written out.

If it happens that you need your engine to read out the default values, that's a perfectly fine use-case as well, but like I said before, you will then need to include the `objecttypes.xml` file in your project and read it in addition to reading the map file.

**Comment by AndyGFX** [comment]
I have to read objecttype.xml too for default properties on entity.
Thank.

Andy.

**Comment by cra0zy** [comment]
Just gonna throw my 2 cents into the mix, I think it would be much more useful to always save the value instead of having the default value for the object, but to also have some special file that can store default values like android resource file: http://developer.android.com/guide/topics/resources/string-resource.html
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="hello">Hello!</string>
</resources>
```

**Comment by bjorn** [comment]
@cra0zy I'm not sure I understand what you mean. I explained above why properties are not saved when their values are not changed from the default. If you need to anyway know the default values entered in Tiled, you can read them from the `objecttypes.xml` file. What does the Android resource file add to this?

**Comment by cra0zy** [comment]
Basically what it does is when you are setting Text property of a button, you can either use a normal string, or a predefined one.

Side note, can you make objecttype.xml work per map? The way it's setup now it's impossible to determine the default value from just .tmx file, but if .tmx file pointed to it's objecttype.xml file that would be so very useful.

**Comment by kheftel** [comment]
I actually have no idea where objecttype.xml is located, if I needed to include it in a game. Where does one find this file?

**Comment by cra0zy** [comment]
Config folder for Tiled, or you can export it from object types editor.

**Comment by kheftel** [comment]
thanks!

**Comment by bjorn** [comment]
I guess [the documentation](http://doc.mapeditor.org/manual/custom-properties/#predefining-properties) could be a little more specific on that point.
