### ISSUE TITLE
Add Tiled Version to Export Data

### ISSUE THREAD

**Issue by GymbylCoding** [bjorn/tiled#1262]
A simple but nice feature would be if we could get the Tiled version from the exported data, thereby allowing framework writers (like me) to decide how to interpret the map data without resorting to old/new feature sorting.

**Comment by bjorn** [comment]
I'm working towards the Tiled 1.0 release, from which point onwards the "version" attribute written to the TMX file will match with the Tiled version. So hopefully the problem solves itself by then.

This question for the version comes up more often though. In Tiled itself I have so far not found a need for doing any version checks. I'm interested to hear in which situations exactly the version information would be useful. Is this the `x/y` vs. `offsetx/offsety` change on image layers?

**Comment by GymbylCoding** [comment]
I don't have any issues right now, but 0.16's new property types feature brought it to my mind. With version info, the framework writer could support older features like export formats without `propertytypes` but also the new version, or write to primarily support the new version without dropping support for the old. Checking for if `propertytypes` exists, while doable, is an approach that grates against my perfectionist soul ;). Regardless, adding version info is a good move forwards; I've had bad experiences updating an app with a new save data version and having to rely on idiosyncrasies of my previous implementations to decide how to convert the data to the new format.

**Comment by bjorn** [comment]
Alright, though in the case of `propertytypes`, even when only supporting recent exports it's still necessary to handle the case where this thing doesn't exist, since it only gets written if there are any properties at all.

In general you're right that being able to rely on a version can make things cleaner. However, that is usually only necessary in cases where backwards compatibility is broken, which so far didn't really happen to the TMX format I think.

**Comment by karai17** [comment]
Backwards compatibility did affect the Lua export with the property types. Before that was added, all properties were strings so I would search for a string-literal true when dealing with some things. After the update, people making new maps would (rightfully) use the boolean type for properties, and my loader would fail since it was still looking for strings.

I recently updated to search for booleans, and I don't personally care about backwards compatibility, but I can fully understand why this would be requested.

Interestingly, the Lua export *does* have the Tiled version in it, so I am surprised to hear that the TMX does not.

**Comment by bjorn** [comment]
> Backwards compatibility did affect the Lua export with the property types. Before that was added, all properties were strings so I would search for a string-literal true when dealing with some things. After the update, people making new maps would (rightfully) use the boolean type for properties, and my loader would fail since it was still looking for strings.

While loaders often need changes to adapt to newer versions, this is not an example demonstrating why adding the Tiled version would be actually useful, since your new code does not need to check the version before it can deal with the possibility of boolean property values correctly. I was wondering about cases where checking the version would actually be necessary, and at least in Tiled I have so far not needed the version.

That said, a `tiledversion` attribute was added to the TMX and JSON formats in Tiled 1.0.1 (though it may not be very useful, since snapshot builds use the data as version).

Also, of course we reached 1.0, and eventually 1.1, but it seems I once again forgot to increase the file format version... Fixed that now in change 9a65af2ecf6651fa131a59e3b9128397216a8a1c, and with change e6688c42e3ad4ae2f75840064e24509acd7d4f58 the version information will be included in tileset files as well (these changes may be included in Tiled 1.1.7 if there is going to be one, and in Tiled 1.2 otherwise).
