### ISSUE TITLE
Compiler fails at line 91 of qtlocalpeer.cpp

### ISSUE THREAD

**Issue by winstonliu** [bjorn/tiled#1265]
Windows compiler fails with `Cannot access private member declared in class	'QString'`.

Fix is to change line 91 of `\src\qtsingleapplication\src\qtlocalpeer.cpp` to `QLibrary lib(QLatin1String("kernel32"))`.

**Comment by theshadowx** [comment]
it's because the flag QT_NO_CAST_FROM_ASCII is set.

**Comment by bjorn** [comment]
Ah, this define is only set for Tiled by the qmake project and not by the Qbs project which I'm generally using. This should of course be consistent to avoid issues like this.

Also, it would be good to make sure building with qmake on Windows is actually tested somewhere, like on AppVeyor.

**Comment by bjorn** [comment]
Now that qmake is officially no longer supported on Windows, this is issue is indeed irrelevant. That's because this line of code is Windows-specific, and when using Qbs the `qtsingleapplication` sub-project is compiled as a static library rather than being directly included in the `tiled` project, so the define `QT_NO_CAST_FROM_ASCII` does not apply to it even after change 7b7c8d39d42a5a6c92ae5f90e862fe750363772d.

**Comment by JesseTG** [comment]
> Now that qmake is officially no longer supported on Windows

Wait, what!?  Says who?

**Comment by bjorn** [comment]
> Wait, what!? Says who?

I guess one can't be specific enough. What I mean is that qmake is no longer supported _for building Tiled on Windows_. And that's because I say so. :-)

The reason is that I consider it a waste of time to maintain two build systems, and the Qbs project is proving to be a lot easier to maintain and extend with more features than qmake. For example, it can build the MSI installer and since today also a 7-zip distributable archive, and it can optionally link against WinSparkle and it can easily build solutions like `qtsingleapplication` as static libraries with separated compile-time options and it processes some files like `tiled.rc.in` to add version information. I could somehow hack all that also into the qmake project, but Tiled doesn't gain anything from it.

Yet, the qmake project needs to stay around for now, since I still use it on OS X and qmake is more readily available on Linux. Just on Windows it has now been deprecated for Tiled.

**Comment by JesseTG** [comment]
*Oh*, I thought you meant QMake itself was no longer supported on Windows.  My bad.
