### ISSUE TITLE
Shape Drawing for Tiles

### ISSUE THREAD

**Issue by Ashedragon** [bjorn/tiled#1272]
The ability to fill a large rectangular or circular area with a particular tile would be very helpful. Instead of simply having to draw around the space you want and then fill it with the bucket tool, you would hold the mouse down and draw from one point to the desired point and it would fill in the created shape with the tile(s) selected.

**Comment by bjorn** [comment]
I definitely agree, but we need to find a way to fit this into the UI somewhere. Currently, you can draw lines by holding Shift and circles by holding Shift+Control. To that should probably be added rectangles, filled rectangles and filled circles. But there aren't enough modifier keys for that, and of course it's bad to hide this functionality there.

I'm considering Photoshop-style expandable drawers, so that one "shape drawing tool" could be implemented that can switch mode by either using shortcuts or expanding the drawer and choosing the desired shape.

**Comment by kheftel** [comment]
Wow, I just tried it, and shift+cmd/ctrl DOES draw tiles in circles!

I keep finding new features in this program as time goes on :). It's like easter eggs.

**Comment by vortexofdoom** [comment]
What if the same modifiers used with the fill tool instead of stamp did the filled rectangles+circles?

**Comment by bjorn** [comment]
> What if the same modifiers used with the fill tool instead of stamp did the filled rectangles+circles?

Hmm, well Shift is already taken in the fill tool, which makes it fill the selected area rather than finding an area of same-tiles. Besides that, I really think explicit and more visible tools is better in general than hiding such functionality under the very limited set of modifier keys.

**Comment by leonidax** [comment]
I think a brush and filling tool ( bucket tool ) would be nice to have and wang tiles could be part of the feature what do you think @bjorn?

**Comment by bjorn** [comment]
@leonidax I'm not sure yet how to integrate things like the bucket fill tool and other rectangle/circle filling tools with things like Wang Tiles and Terrain Tiles. It would be nice if it could be integrated as some kind of post-processing step, so that these tools will be able to support both while keeping the algorithms cleanly separated from the basic filling logic.

**Comment by bjorn** [comment]
I just noticed a rectangular fill was also requested as issue #268.
