### ISSUE TITLE
The shortcut for the eraser doesn't work in Dutch

### ISSUE THREAD

**Issue by DaanHaaz** [bjorn/tiled#1280]
The shortcut key (W) for the eraser doesn't work when your language is set to Dutch.
Tiled: Version 2016.05.17
OS: Ubuntu 14.04

**Comment by bjorn** [comment]
Hmm, same for S. It's because W and S became ambiguous shortcuts when the Magic (W)and and the (S)elect Same Tile tools were added. I think I should just drop my attempts at customizing these shortcuts to Dutch and go with the English ones, which is also better for the [keyboard shortcuts reference](https://github.com/bjorn/tiled/wiki/Keyboard-Shortcuts).

**Comment by bjorn** [comment]
Thanks for reporting the issue, btw! It has been broken for quite a while...

Daily builds will get fixed up once this is merged down to master.
