### ISSUE TITLE
Tiled for OS X download on itch.io

### ISSUE THREAD

**Issue by bitinn** [bjorn/tiled#1285]
is pointing to the source code release instead of dmg? for latest release at least.

**Comment by bjorn** [comment]
Thanks for reporting! I've fixed this issue now.

Something is wrong with itch.io when deleting download links. It seems to fail to shift the links below it upwards as expected, leading to everything getting mislabeled like described in #1287. I should report this to @leafo.

**Comment by leafo** [comment]
deleting download links? or deleting actual uploads?

**Comment by bjorn** [comment]
@leafo It's about download links. When you got them set up like this for example:
```
Link Title 1 -> http://link1
Link Title 2 -> http://link2
Link Title 3 -> http://link3
```
And then press the Delete button on the first one, you end up with:
```
Link Title 2 -> http://link1
Link Title 3 -> http://link2
```
The first few times it happened I thought I had made a copy/paste error or something. And unfortunately I failed to notice this problem when removing some download links a few days back and was wondering why the Tiled download counts went up so much, until this issue was reported and I realized it was because people had to attempt other links to get the version they needed, heh.

**Comment by bjorn** [comment]
@leafo I just played around a bit and noticed the Move Up / Move Down actions are similarly not working properly in the case of external files.
