### ISSUE TITLE
How to get tile properties?

### ISSUE THREAD

**Issue by cantbelievethis** [bjorn/tiled#1314]
{ "height":1000,
 "layers":[
        {
         "data": [0, 4000, 0,0,0,0....]
},
{
"data": [0, 0, 0,0,0,0....]
}]
  }

I'm setting up some tiles as "blocked:true", so you can't walk through them. Imagine my surprise when I find out 4000 is not 4000 in "tileproperties":{} but 116.

**Comment by cantbelievethis** [comment]
After digging a bit I am now under the impression that for every tile I want to check properties on, instead of something that could be done as easy as map.tileset.tileproperties[map.layers.data[tileToCheck]], I must do the following:
1) Process ALL tilesets of the map, even if they aren't used, even if they are a hundred.
2) Calculate what tileset is this specific tile using.
3) Calculate the place of the tileset this specific tile belongs to. First tileset has first gid, second tileset has both first and second, third has first, second and third...)
4) Get number of pixels of each tileset
5) Divide number of pixels by tilewidth so we get individual tiles quantity
6) Add up the tiles quantity of every tileset before the current tileset. So if the tile I want to check is located in tileset 20, I must add up the total tile number of tilesets 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19 and 20, and only then I will be able to tell the position of the tile I'm checking.

All this for a single tile check? That's so bad it can't be true. I'm sure I'm missing something here.

**Comment by cantbelievethis** [comment]
Ok, so if someone stumbles upon this, here's what you gotta do:

1) Process all tilesets of the map, even if they aren't going to be used now, even if they are a hundred.
2) Identify which tileset this specific tile belongs to.
3) Substract the id of the tile to the "firstgid" of that tileset and check if it exists in tileproperties.

Frankly I moved to another tool, but maybe someone finds this useful.

**Comment by bjorn** [comment]
Well, I think it's a strange reason to move to another tool (which one, actually?).

For what it's worth, this process is documented on the [TMX Map Format](http://doc.mapeditor.org/reference/tmx-map-format/#data) page, even with example code. In particular, the thing you make sound so complicated resolves to the following bit of code:

```c++
// Resolve the tile
for (int i = tileset_count - 1; i >= 0; --i) {
    Tileset *tileset = tilesets[i];

    if (tileset->first_gid() <= global_tile_id) {
        tiles[y][x] = tileset->tileAt(global_tile_id - tileset->first_gid());
        break;
    }
}
```

Alternatively, some people would go through the list of tilesets and set up a mapping from global tile ID to the tile instance, so that the above is reduced to a single lookup in that map. That is fast even if you indeed have a hundred tilesets in your map (in which case, the most important part is to not load the images for the unused ones).
