### ISSUE TITLE
Terrain Information does not update after changing tileset width

### ISSUE THREAD

**Issue by marcelvdmade** [bjorn/tiled#1315]
As the title says. Now that the tile editor works with adjusting tileset width, I tried it out, but it messes up the terrain definition. These need to be re-defined after a tileset width change.

**Comment by bjorn** [comment]
Ouch, I completely missed that. :-(

I'll try to look at this soon.

**Comment by bjorn** [comment]
Hmm, this issue is even more serious than just terrain information getting messed up. Actually, all information stored with the tiles is affected, so also collision shapes, animations and custom properties. Animations in addition need to be adjusted internally.

**Comment by bjorn** [comment]
This turned out to be an incredibly complex beast, taking more than half the day to write a proper fix for. Unfortunately, the fix won't work very well for external tilesets, since they don't have their own undo stack and saving operation yet (work on that is ongoing on the `wip/tilesetdocument` branch).

In any case, with embedded tilesets you should be safe now, and I think with careful operation you can also adjust external tilesets (by first making sure all relevant maps are opened in Tiled, then doing the adjustment, and then re-exporting the affected tileset).

Given the complexity of the fix, I've pushed it to `master` rather than the `0.16` branch. To try it in advance of the Tiled 0.17 release, you will need to compile Tiled yourself or install a snapshot build (I've updated the `snapshot` branch so they should update soon). Please do this if you can, and let me know if it worked!
