### ISSUE TITLE
Bad tile values in Lua export

### ISSUE THREAD

**Issue by gmaletic** [bjorn/tiled#1320]
The Lua export of my TMX file include many values that are outside of my tile map range. The CSV values are fine. 

The attached ZIP archive illustrates this.

![subterranean-tiles-table-16-16](https://cloud.githubusercontent.com/assets/185702/17080748/347ad840-50f0-11e6-9d5c-b38082799c90.png)

[tutorial-2.zip](https://github.com/bjorn/tiled/files/380013/tutorial-2.zip)

**Comment by gmaletic** [comment]
This is Tiled 0.16.2.

**Comment by bjorn** [comment]
This is because the CSV and Lua formats are not writing out tile IDs the same way.

CSV format: The tile IDs start with 0 for the first tile. When some location has no tile, -1 is written out.

Lua format: Supports multiple tilesets. Each tileset has a "firstgid" property, which is the first global ID for the first tile in that tileset. So since your "subterranean-tiles-table-16-16" tileset has a "firstgid" of 1, this means that tile ID 1 on the tile layer is the first tile in that tileset. When some location has no tile, 0 is written out (the global tile IDs are unsigned 32-bit).

**Comment by gmaletic** [comment]
I'm aware of the 1-indexing in Lua, but that's not the problem I'm encountering. Note line 13 in the CSV file:

`15,0,0,0,16,29,15,0,1,0,16,28,52,37,32,39,32,37,46,39,30,44,31,44,29`

…and here it is in the Lua file:

`16, 1, 1, 1, 17, 30, 16, 1, 2, 1, 17, 29, 53, 38, 33, 40, 33, 38, 47, 40, 108, 122, 109, 122, 107,`

108, 122, 109, 122, and 107 are not just "off-by-one"…they're way out of range.
