### ISSUE TITLE
Problem with snapping to pixels in the collision editor

### ISSUE THREAD

**Issue by RareBanjo** [bjorn/tiled#1329]
I am expecting this to be a problem that is happening because I am an idiot and new to the program. But when I edit the collisions for my tiled I holding down CTRL and making a collision either doesn't select anything or select the whole thing. Then when I start at the bottom and drag up to make one it just makes a flat line. I am pretty new and would appreciate some help.

**Comment by bjorn** [comment]
This is because Control snaps to tiles, not to pixels. I realize this isn't very useful, so it's something I should consider improving eventually.

For now, you can enable "Snap to Fine Grid" in the "View" menu to get more finer-grained snapping. If you want it to snap to pixels, you need to set the number fine grid divisions in the Preferences to match the number of pixels on your tiles.
