### ISSUE TITLE
how to export a texture of map, repaint, attatch with the colliders to scale in unity

### ISSUE THREAD

**Issue by 2dduane** [bjorn/tiled#1337]
I did the layout work and want to do some custom texture areas with the level. Is there an easy way to kick out my initial tiled color map, paint it, and then pair it up with the .obj collider within unity?  Thank you

**Comment by bjorn** [comment]
You'll probably want to have a look at [Tiled2Unity](http://www.seanba.com/tiled2unity).

**Comment by 2dduane** [comment]
That's what I'm referring to. How can I do it within tiled.

**Comment by bjorn** [comment]
You can't do it within Tiled, which is why Tiled2Unity was developed. If you mean how to integrate the tool with Tiled, you can use the command system for this. See the following general documentation about this feature:

http://doc.mapeditor.org/manual/using-commands/

There are also more specific instructions for the command-line tool shipping with Tiled2Unity:

http://www.seanba.com/introducing-tiled2unitylite.html
