### ISSUE TITLE
Multiple terrains can't share tiles

### ISSUE THREAD

**Issue by BananaIguana** [bjorn/tiled#1364]
In release version 0.17.0 (using a Mac), I defined a terrain 'B' that uses a tile defined in the terrain 'A'. When assigned in B, it cancels the association in the terrain A.

In my use case, I have two terrains defined which use unique corner pieces but share the same edge pieces. Is it possible to update the terrain tool to share tiles between different terrain settings?

**Comment by bjorn** [comment]
Hmm, this is not possible currently and I don't see a nice way to add it. You would just have to duplicate the shared tiles.

**Comment by omnipoof** [comment]
I'll second this issue since I ran into it in my project.  Having a duplicate tile doesn't solve the issue in my scenario.  I have grass, dirt, path, and water tiles and have three terrains for grass/dirt, grass/path, and grass/water.  I've filled in a layer with grass and then use the terrains to draw in the dirt, path, and water sections.  If I duplicated the grass tile, it makes the grass area filled with one or the other grass tiles which can interfere with the other terrains.

My workaround is to switch back to the tilemap when I'm going to use one of those terrains and associate the grass tile with whatever terrain I'm wanting to use.

**Comment by bjorn** [comment]
> I have grass, dirt, path, and water tiles and have three terrains for grass/dirt, grass/path, and grass/water.

It sounds like you should have 4 terrains: grass, dirt, path, and water. Why have terrains for transitions?

**Comment by omnipoof** [comment]
Sorry, I miscommunicated that; I have six terrains and thus three pairs of terrains that work together to form a dirt area, path area, and water area on top of a grass area.  For example, the grass/water terrain pair is set up as follows:

- Grass-to-Water Terrain: **Solid grass tile**, grass/water tiles (grass side)
- Water-to-Grass Terrain: Solid water tile, grass/water tiles (water side)

Because the grass terrain of each terrain pair requires the solid grass tile in addition to the grass/X tiles, it means that three of my terrains are dependent on the same tile.  Since Tiled currently limits a corner of a tile to only belong to a single terrain, it means I need to re-add the solid grass tile to the particular grass terrain I need to use each time.

**Comment by bjorn** [comment]
@omnipoof I still don't understand the problem. You should only have one "grass" terrain, right? So why would you need to assign different terrains to your solid grass tile? Maybe showing an image would help?

**Comment by omnipoof** [comment]
Sure, here are some screenshots of my terrains:

The Grass-to-Path Terrain:
![image](https://user-images.githubusercontent.com/19640032/58604153-35993500-8248-11e9-924f-0a10895052da.png)

The Path-to-Grass Terrain:
![image](https://user-images.githubusercontent.com/19640032/58604197-55305d80-8248-11e9-8a81-12b9ebc88a8a.png)

The Grass-to-Dirt Terrain:
![image](https://user-images.githubusercontent.com/19640032/58604217-69745a80-8248-11e9-8e50-326aa8eb62e3.png)

The Dirt-to-Grass Terrain:
![image](https://user-images.githubusercontent.com/19640032/58604237-80b34800-8248-11e9-8de5-04160e418ae3.png)

I defined the Grass-to-Dirt and Dirt-to-Grass terrains first, then defined the Grass-to-Path and Path-to-Grass terrains second.  Notice that the Grass-to-Dirt and Dirt-to-Grass terrains do not have the solid grass tile and solid dirt tile like the Grass-to-Path and Path-to-Grass terrains do.  This is because since the Grass-to-Path and Path-to-Grass terrains were defined second, their use of the solid grass tile and solid dirt tile overrode the definition in the previous two terrains.  What would be great to have is the ability to include the solid grass tile and solid dirt tile in multiple terrains at once.

Thanks for your help!

**Comment by bjorn** [comment]
@omnipoof I still do not understand why you have a "Grass-to-Dirt" terrain. In the documentation I wrote about [using the Terrain Tool](https://doc.mapeditor.org/en/stable/manual/using-the-terrain-tool/), you'll see that there should be a terrain type for each terrain, not for each transition. If you would have Grass, Dirt and Path terrains, then it should also be clear that the solid grass tile can't be marked anyway else than with just the Grass terrain.

Now, I'm not sure if your tiles are actually compatible with the way the terrain tool works. The terrain tool requires that each tile has a well-defined terrain type at each of its corners, and that the transition between these terrain types happens between the corners. I don't really see this being the case in your tileset. I also do not understand how the ability to share a solid grass tile would make this scenario work.

**Comment by omnipoof** [comment]
Thanks for the advice!  I went back and recreated the terrains based on each being unique and covering all of the appropriate edges with other terrains:

![image](https://user-images.githubusercontent.com/19640032/59476500-dc173580-8e05-11e9-9dac-a436b9023d13.png)

There still is a scenario where multiple terrains should be able to share tiles, though.  In the image above, the upper left and upper right have tiles that contain both grass and dirt, but the transition those tiles represent are different (I consider the upper left one my path tiles because of the defined edges between grass and dirt and the upper right one my dirt tiles because it's a rougher/"grassier" transition).  In this case, I would want a solid dirt tile in both terrains but when I select the "path" terrain it draws the more defined edges between grass and dirt and when I select the "dirt" terrain it draws the rougher edges between grass and dirt.  Would this be possible?

**Comment by bjorn** [comment]
> In this case, I would want a solid dirt tile in both terrains but when I select the "path" terrain it draws the more defined edges between grass and dirt and when I select the "dirt" terrain it draws the rougher edges between grass and dirt. Would this be possible?

It's not possible because Tiled does not store terrain information on the map. The tool derives from the tiles that are placed the terrain at each location, which would not be possible if a tile is shared between multiple terrains.

I think with the current system we don't get around to duplicating the tile in this case.

With the [Wang tiles](https://doc.mapeditor.org/en/stable/manual/using-wang-tiles/) system it would be possible, because each Wang set can reuse any tiles that are also part of another Wang set, and there's not the above problem because you use only one Wang set at a time. Unfortunately the Wang Brush still needs some work to be broadly usable.

**Comment by omnipoof** [comment]
Ok, that makes sense.  I guess this issue can just be left open in case it ever becomes a bigger priority to implement.  I have sufficient workarounds right now to do what I need to do, so this isn't blocking.  Thanks for your help investigating if this is a possibility!

**Comment by bjorn** [comment]
With #2888 merged there is a way to associate multiple terrains (right now called "Wang colors") with a single tile, as long as you set up multiple Wang sets. The Wang Brush can now do everything the Terrain Brush did, and more.

The tools only work with one Wang set at a time, but it should be possible to cope with that limitation. I'll close this issue now, but feel free to comment if you find any issues.

**Comment by matt-colon** [comment]
Thanks for keeping this on your roadmap!
