### ISSUE TITLE
In what order does Tiled store the order of polygons and rectangles?

### ISSUE THREAD

**Issue by moonshineTheleocat** [bjorn/tiled#1375]
I'm in the process of working on a 2D isometric game with the game logic in a top down fashion. And I need to make a plugin that will export the map Objects that Tiled creates to the proper orthographic space coordinates.

According to Box 2D's documentation, it requires Counter Clockwise vertex rotations for it's polygons. I'm assuming that failure to follow this order will likely result in the normals being reversed.

**Comment by bjorn** [comment]
Tiled stores the points on a polygon from first to last. Whether that is clockwise or counter-clockwise depends on how you create the polygon. Fortunately, the latest version of Box2D no longer cares anymore about the order of the points, since it [figures out the convex hull by itself](http://box2d.org/2013/11/box2d-2-3-0-release/).

What documentation are you reading that still states that vertices need to be provided in counter-clockwise order? It must be three years out of date.

**Comment by moonshineTheleocat** [comment]
Mmm... quite literally from the main website.

**Comment by bjorn** [comment]
Oh well, then it wasn't updated with the information posted in that release announcement. It's anyway quite good news that the library no longer needs the vertices to be ordered, right? :-)

I'll close this issue now.
