### ISSUE TITLE
Need short and consistent --export-format

### ISSUE THREAD

**Issue by buckle2000** [bjorn/tiled#1382]
Currently `--export-format`'s output varies from machine to machine.

Format like `lua` is better than `"Lua files (*.lua)"` because it can be used on a different machine without changing build script.

**Comment by bjorn** [comment]
That's right. Formats should probably have some explicit short name for this, since the file extension is not guaranteed to be unique.

Note that in this particular case, you can just leave out the `--export-format` parameter, because the Lua format will be used automatically based on the file extension.

**Comment by buckle2000** [comment]
In some cases, maps would be exported to lua files but have extension other than `.lua` (maybe `.map`). I know I can rename files but with specified format it is just redundant.

Also, I cannot export lua files with `tengine` plugin turned on.

**Comment by bjorn** [comment]
Good points, and that's also why I agree there should be some kind of short string identifying each format. Unfortunately, the plugin name can't be used either because a single plugin could add multiple formats (currently done by the Python and JSON plugins).

**Comment by josefnpat** [comment]
Originally I came here to mention that `"Lua files (*.lua)"` as an argument is odd and unwieldy, but honestly, I think it's good. It takes the guesswork out of what it's exporting as, especially since the there might be multiple object structures for future Lua exports (e.g. `"Tiled Lua File (*.lua)"` or `"<Possibly very specific framework that's popular but refuses to change> Lua File (*.lua)"`.

The real problem here is that when one runs `tiled --export-formats` it doesn't specifically mention that the string should be what is the list.

For example, 

```bash
seppi@seppi7:~♠ tiled --export-formats
Export formats:
  "CSV files (*.csv)"
  "Lua files (*.lua)"
  "Json map files (*.json)"
  "JavaScript map files (*.js)"
```

I was confused at first why `--export-map lua input.tmx` didn't work. Lua is in the list! (My first guess was the fact that I didn't capitalize "Lua"). On a whim, I tried the string, and was happy to see data popping up from my pipeline.

Maybe it would be nice to explain that the strings shown are the input args, or show a quick example to squash any doubt:

```bash
seppi@seppi7:~♠ tiled --export-formats
Export format arguments:
  "CSV files (*.csv)"
  "Lua files (*.lua)"
  "Json map files (*.json)"
  "JavaScript map files (*.js)"

Example:
tiled --export-map "CSV files (*.csv)" foo.tmx
```

**Comment by bjorn** [comment]
@josefnpat Good suggestion, but the original issue that the format depends on the locale of the machine (since it uses a translated string) still needs to be fixed as well. Hence I would still introduce short strings to identify these formats, And I think it will then be clear enough, for example like:

```
$ tiled --export-formats
Export formats:
  csv
  js
  json
  lua
  te4

Usage:
  tiled --export-map [format] <source> <target>
```
Here `te4` actually also uses the `.lua` extension, but this way it is clearly labeled as the specific format that it is.

**Comment by buckle2000** [comment]
I think plugins should declare format name explicitly.
Something like `lua_tiled_map` is better than `"Lua files (*.lua)"`
