### ISSUE TITLE
overwriting layernames when multiple tilemaps are open

### ISSUE THREAD

**Issue by Clas1** [bjorn/tiled#1396]
when a layer is selected in one map, doubleclicking a layer on another tilemaps leads to overwriting the layername in the first map

**Comment by bjorn** [comment]
Nice catch. It appears to have been a bug in Qt since it only affected builds against Qt 5.7. For earlier Qt versions and for the current `dev` version of Qt, the editor was silently closed without committing a possible rename.

After my patch, if the text was changed before switching maps, then it will lead to a layer rename before the map is switched. I think this behavior is slightly better since it is the same when you focus something else, so I'll leave it be.
