### ISSUE TITLE
Allow specifying the type of a property

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#14]
In some cases it may be nice to know the type of a property. This can also be used to determine an appropriate editor for the property value, once we have a more advanced property editor.

Suggestions for supported types: string (the default), number (floating point), int, bool

Possibly we could even have "file", which would enable a file chooser.

This issue spawned from the discussion at #12

**Comment by LearnCocos2D** [comment]
+1

Currently trying to infer the type of a property from its value. It's a pain to do this in C++ (or C) and will lead to odd behavior:

- bool values have to be specified as "true"/"false" strings because 0/1 will be interpreted as int
- all integer values will be int even if the underlying data type is float and the value just happens to be an int

I don't think we need to differentiate between int/uint and float/double because there exit viable runtime conversions. A uint can safely be stored to an int and then cast back to uint if needed. Float values can be read as double, if needed, but I don't think any user will ever need to enter a value with double precision, float will suffice. As for other uses of strings, their use (path, URL) can easily be inferred from the property key or even where that is not possible, determined by using regex or string search.

So I'd propose to stick to the most common, most basic types in the TMX format for denoting a property's type:

- bool
- int
- float
- string

**Comment by hamilton-lima** [comment]
+1
One simple change would be allow to edit the property in a multiline editor with an extra "..." at the right side of the editor, that would allow lots of scripts possibilities.

**Comment by bjorn** [comment]
> One simple change would be allow to edit the property in a multiline editor with an extra "..." at the right side of the editor, that would allow lots of scripts possibilities.

Multi-line editing is independent of supporting more property types than just strings, but it's definitely something I want to support as well! It is covered by issue #205.

**Comment by hamilton-lima** [comment]
that´s great @bjorn  !

**Comment by bjorn** [comment]
This feature has been implemented and released with Tiled 0.16. I've opened #1278 regarding the addition of a custom file type, which is not available yet.

Also just recently I've implemented #205, adding a multi-line editor for string properties.
