### ISSUE TITLE
Fedora missing  QT 5

### ISSUE THREAD

**Issue by luan-cestari** [bjorn/tiled#1407]
I followed the README.MD (I'm using Fedora latest version) and I tried to run the project. I noticed that tiled.pro specific QT 5.2.0 (or above) but Fedora doesn't have it yet in its repository. May I create a PR to put this information and put a link to QT website?

**Comment by bjorn** [comment]
Fedora is definitely not missing Qt 5.2 or above. What Qt package did you try to install? Maybe @Ablu can help you determine the right package to get (and we should update the `README.md` if `qt-devel` isn't the right package).

However, if you just want to use Tiled you should be able to simply install it using the Fedora `tiled` package management rather than compiling it yourself. See http://rpmfind.net/linux/rpm2html/search.php?query=tiled for what versions should be available for your version of Fedora.

Alternatively, you can install snapshot builds for Fedora from https://copr.fedorainfracloud.org/coprs/ablu/tiled-dailies/

**Comment by Ablu** [comment]
You can run `sudo dnf builddep tiled` to install all the required depdencies for compiling Tiled manually on Fedora.

**Comment by luan-cestari** [comment]
@Ablu @bjorn  Thanks. it works here. I created a PR with the command @Ablu mentioned https://github.com/bjorn/tiled/pull/1409 . Thank you for the help =)
