### ISSUE TITLE
Mass Select Locate File instead of just per entry?

### ISSUE THREAD

**Issue by Archeia** [bjorn/tiled#1412]
Hello~
Is there a way to make locate file reference a folder immediately without having to edit the JSON file? Right now you have to select all of them individually and press Locate File -> Open. Is it possible to highlight all of them and then refer to that folder?

I am talking about this menu:
![2016-12-12_9-54-40](https://cloud.githubusercontent.com/assets/6222499/21085831/3f91e7f2-c051-11e6-96fb-63bdfb548eb6.jpg)

**Comment by bjorn** [comment]
Thanks for opening an issue about this. There is unfortunately no way to do this at the moment. I already have a comment about this in the code, but didn't implement it yet because it's a little tricky.

How exactly would you expect the behavior? In case of multiple selected files, should Tiled just ask for a directory and then match all selected files just by their file name? That would speed up nicely the case of having many files in one directory, though it does not help if you have many files in many directories...

When many directories are involved, it could make sense to search recursively in the selected folder. Though of course, then name collisions start becoming more common. Alternatively, you'd select a base directory and Tiled would somehow take the expected path into account while searching for the files. But you can probably see what I mean with it being a little tricky now.

Feedback welcome, in any case.

**Comment by Archeia** [comment]
Just selecting a folder is OK! Since we have tilesets on a single folder only :D
