### ISSUE TITLE
Change current layer depending on selected objects

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1424]
When the list of selected objects changes and all of them are on a different layer than the current one, it would be helpful to change the current layer. I've noticed this behavior in Inkscape.

**Comment by gardenvarietyse** [comment]
Came here to suggest exactly this!

One issue I have occasionally is, I'll select an object and duplicate it, but oh no, it's on the wrong layer because the selection didn't change. I tend to give them different colors which helps avoid this, but if I didn't I'd probably end up not even noticing every time.

**Comment by bjorn** [comment]
@gardenvarietyse If you duplicate an object, the duplicate ends up on the same layer as the original object, regardless of the currently selected layer. Still, I'm sure we can avoid some confusion by changing the current layer.

I just realized that `ObjectsView::selectionChanged` already implements this behavior, but it only works when objects are selected in the Objects view.
