### ISSUE TITLE
Moving/resizing shape objects is frustrating

### ISSUE THREAD

**Issue by DaanHaaz** [bjorn/tiled#1425]
1.

When creating a rectangle you have to hold ctrl to align to the tilemap. After you created the rectangle, select it, and move it around, you also use ctrl for aligning. But when resizing the rectangle, you have to hold alt. This inconsistency is annoying.

2.

So now I want to resize the rectangle. I click on one of the arrows, I hold alt, and try to move the arrow. But because I wasn't in a "resizing state" yet, it instead moves the rectangle around.

So I would like for alt and ctrl to be switched in the resizing state, and prevent alt from going in to grabbing state when an arrow is selected.

**Comment by bjorn** [comment]
> But when resizing the rectangle, you have to hold alt. This inconsistency is annoying.

The trouble was, Tiled has always had Ctrl for toggling the snapping, but in other applications Ctrl is used to maintain the aspect ratio in the context of resizing. So I really wasn't sure of the best approach.

And Alt is, at least in Inkscape, used to force a drag operation, which can really come in handy but it means Alt is a bad key for "toggle snap" in that context. Otherwise, I might have opted to just move the snap toggle from Ctrl to Alt everywhere.

So right now I'm not sure what to do with this, apart from maybe dropping the toggle key completely and instead adding a shortcut to the "Snap to Grid" action in the View menu (you are aware that you can turn that on/off, so that you don't need to rely on Ctrl/Alt to toggle it, right?). 

> So now I want to resize the rectangle. I click on one of the arrows, I hold alt, and try to move the arrow. But because I wasn't in a "resizing state" yet, it instead moves the rectangle around.

I should definitely make sure that the Alt modifier does not prevent you from using the resize handle.

**Comment by DaanHaaz** [comment]
If you only fix my second problem than that's fine to me. I'll just get used to using alt instead of ctrl for resizing.

**Comment by bjorn** [comment]
> If you only fix my second problem than that's fine to me. I'll just get used to using alt instead of ctrl for resizing.

The above change fixes that, so it will be in a potential 0.18.1 release, and in the snapshots sometime sooner.

Do you have any opinion on dropping the snap toggle and instead having a shortcut for quickly turning snap on/off?

**Comment by DaanHaaz** [comment]
Oops, I wasn't even aware of that feature. That makes things a lot easier haha.

In that case I'd say keep it like this.

**Comment by bjorn** [comment]
Alright. :-)
