### ISSUE TITLE
Tile Collision Editor window won't load (it only shows an image of what was behind it)

### ISSUE THREAD

**Issue by jtara1** [bjorn/tiled#1438]
![image](https://cloud.githubusercontent.com/assets/7478231/22631398/5923c3fc-ebc1-11e6-8f90-ae43a5051b59.png)

OS: Ubuntu 16.04

Tiled Version 0.18.1

```
j@j-desktop:~/Downloads$ screenfetch
                          ./+o+-       j@j-desktop
                  yyyyy- -yyyyyy+      OS: Ubuntu 16.04 xenial
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.4.0-62-generic
           .++ .:/++++++/-.+sss/`      Uptime: 6h 34m
         .:++o:  /++++++++/:--:/-      Packages: 4118
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.3.46
       .:+o:+o/.          `+sssoo+/    Resolution: 4480x1440
  .++/+:+oo+o:`             /sssooo.   DE: KDE5
 /+++//+:`oo+o               /::--:.   WM: KWin
 \+/+o+++`o++o               ++////.   GTK Theme: Breeze [GTK2/3]
  .++.o+++oo+:`             /dddhhh.   Icon Theme: breeze
       .+.o+oo:.          `oddhhhh+    Font: Noto Sans Regular
        \+.++o+o``-````.:ohdhhhhh+     CPU: Intel Core i5-3450 CPU @ 3.5GHz
         `:o+++ `ohhhhhhhhyo++os:      GPU: GeForce GTX 970
           .o:`.syhhhhhhh/.oo++o`      RAM: 6586MiB / 32056MiB
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++. 
```

**Comment by bjorn** [comment]
Hmm, that's strange. Do you have OpenGL enabled in the Preferences and if so, does it help to turn it off?

**Comment by jtara1** [comment]
When I enabled that option, the program just crashes without any message.

**Comment by bjorn** [comment]
Are you using the AppImage file? If so, could you try the snapshot instead of the release? It's built against a newer version of Qt (5.8.0 intead of 5.7.1). Just asking since I think it's unlikely to be a problem in Tiled code...

And if you already tried both AppImage files, maybe try [tiled-daily from the PPA](https://launchpad.net/~mapeditor.org/+archive/ubuntu/tiled), which uses the Qt installed on your system (usually 5.5.1 for Ubuntu 16.04).

**Comment by jtara1** [comment]
Installed it using `apt` and adding the repository from the PPA. Everything works as expected. The OpenGL option and the Collision window.

**Comment by bjorn** [comment]
Great! Can you please also tell me which release you were using before?

And when the problem was in the release AppImage, I'm still curious whether the snapshot AppImage also works. Given that the PPA relies on an ancient Qt, it means the problem may have been introduced in a newer version (or relates to the AppImage packaging, of course).

**Comment by jtara1** [comment]
`Tiled-0.18.1-x86_64.AppImage` is the name of the file I was running. Pretty sure it was the release.

When running the snapshot ('Tiled-2017.01.28-x86_64.AppImage') downloaded from itch.io I have the same crashing problem with OpenGL option enabled and I try to create a new map.
The snapshot has a app image has a working Collision Editor window though.

![image](https://cloud.githubusercontent.com/assets/7478231/22640545/f576a0d0-ec07-11e6-98d1-bea97c8233e4.png)

**Comment by bjorn** [comment]
@jtara1 Alright, great that `Tiled-2017.01.28-x86_64.AppImage` also fixed the problem!

Not sure what's up with OpenGL crashing, but that's a separate issue. Does the PPA tiled-daily version also crash when you enable OpenGL? In any case there is probably little I can do about it, and little benefit to the OpenGL mode anyway. I had just mentioned it as something to try turning off.

**Comment by jtara1** [comment]
In the PPA tiled-daily version, enabling OpenGL does not cause the program to crash at any point.

**Comment by bjorn** [comment]
Ok, so that could be a packaging related issue as well then.
