### ISSUE TITLE
Support for .tga images on linux? 

### ISSUE THREAD

**Issue by roig** [bjorn/tiled#1444]
Hello I can't load a Tileset from a .TGA file, is the format unsupported by tiled? (I'm on linux). Thank you for this great tool :clap:

**Comment by bjorn** [comment]
Hmm, I can't load TGA images on Linux myself either, will need to investigate.

How did you install Tiled?

**Comment by roig** [comment]
I just downloaded the lastest binary from your webpage.

**Comment by bjorn** [comment]
So there were two problems here. First, the version of `linuxdeployqt` I was using had a bug causing it to only ship the SVG image format plugin. After [upgrading that](https://github.com/bjorn/tiled/commit/d3f1996c43d9f40e51e73900372d156bd19609d1) there was still no TGA support though, since that plugin needed to be installed separately as part of the Qt Image Formats package.

Finally, the linuxdeployqt upgrade caused the SVG image format plugin to go missing, so I [needed to do a workaround](https://github.com/bjorn/tiled/commit/d3f1996c43d9f40e51e73900372d156bd19609d1) for that.

But now all should be fine. :-)

**Comment by roig** [comment]
Thank you! 👍
