### ISSUE TITLE
Custom Properties saved to wrong layer with grouping

### ISSUE THREAD

**Issue by Seanba** [bjorn/tiled#1449]
With build 0.18.1545 I see that custom properties are being saved to the wrong layer when using group layers.

To reproduce:

1) Create this hierarchy of layers

>- Group Layer
>>- Object Layer (child of Group Layer)
>- Object Layer (not within a group layer)

2) Add a custom property to the Object Layer that is a child of the Group Layer

3) Save the file

In the TMX file you will see that custom property was saved to the wrong Object Layer (the one not in a group). Also, the property window in Tiled will show the custom property has been added to *both* Object Layers.

**Comment by bjorn** [comment]
Hmm, the problem already happens at step 2. When you click on the Object Layer that is a child of the Group, you actually see the properties of the Object Layer that isn't in the Group. So that is the layer you've set the custom property on, and that's also why it appears to have this property on both Groups.

When I right-click the child Object Layer and choose "Layer Properties...", then I can actually change its properties. So there's probably something wrong with handling the selection change.

**Comment by bjorn** [comment]
Thanks a lot for catching this!
