### ISSUE TITLE
Missing terrain editor button in master

### ISSUE THREAD

**Issue by MarceColl** [bjorn/tiled#1459]
In version `0.18.2` from `master`, fresh from 30 minutes ago the Terrain Editor button from the tilesets toolbar is missing.

 This is from `0.18.1` from the arch repositories
![This](http://i.imgur.com/l9xuGTj.png)
This is from `master`
![This](http://i.imgur.com/YttfQ0i.png)

Also there is a big difference in icon size, probably some dpi changes. My screen is 2560x1600.

**Comment by bjorn** [comment]
All editing operations affecting tilesets have been moved to the tileset editor, since tilesets now have their own undo stack to better support external tilesets. There is an "edit tileset" button you can use to open the tileset editor.

The DPI change is because Tiled no longer explicitly enables automatic scaling of the whole application. It now behaves like Qt applications do by default and tries to adjust to the DPI set for fonts. What DPI are you using and which font size?

**Comment by MarceColl** [comment]
Okay, I see.

The size should be fine. I just didn't know if it was intended. I use very high dpi and small fonts.

Thanks

**Comment by bjorn** [comment]
> The size should be fine. I just didn't know if it was intended. I use very high dpi and small fonts.

To be precise, the default icon size is 16x16, but that is for a DPI of 96. So Tiled uses `QGuiApplication::primaryScreen()->logicalDotsPerInchX() / 96.0` (using the primary screen) to calculate a scaling factor. For me at 160 DPI, this leads to an icon size of 26x26.

If you are indeed using a very high DPI, then something must be going wrong with calculating this scaling factor, since from your screenshot it looks like the icons are simply 16x16. Do you have multiple screens attached? What's your desktop environment and where did you configure your DPI? Maybe you can help debug this problem by setting a breakpoint in `Utils::defaultDpiScale()`.

**Comment by bjorn** [comment]
Btw, in the screenshot where everything was bigger, you can also see lots of painting problems. This is why I decided to try adjusting to the DPI explicitly instead of relying on a global automatic scaling factor. In case you preferred the scaling though, you set `QT_AUTO_SCREEN_SCALE_FACTOR=1` in your environment.

**Comment by MarceColl** [comment]
Sorry, it was a misunderstanding. I am using 96 dpi. It's just a very high dpi for my screen resolution & screen size (2560x1600 on 13") as most people use half that for this setup. So the 16x16 is fine in this case. Used wrong wording.

Thanks for the explanation

**Comment by bjorn** [comment]
> I am using 96 dpi. It's just a very high dpi for my screen resolution & screen size (2560x1600 on 13") as most people use half that for this setup. So the 16x16 is fine in this case. Used wrong wording.

Ok, that explains indeed. I still think you mean 96 is a low DPI for your screen and most people would use double this. Do you have any particular reason for not having your system DPI match that of your screen?

**Comment by MarceColl** [comment]
Yup, fuck me. I mean low. I think in theory I should be useing 170 or something like that.

I just like everything very small. so that a lot fits in the screen.
