### ISSUE TITLE
Being able to search objects

### ISSUE THREAD

**Issue by issy123** [bjorn/tiled#1467]
### Request
It would be nice if we could search objects by it's id,name or type.

### Example

![image](https://cloud.githubusercontent.com/assets/9143253/23588346/a3330bae-01bc-11e7-8d23-39eb7d22fc8f.png)

### Reason

Same as #1462

### Note

It would be nice to add custom attributes too! But maybe I ask too much(yeah yeah I repeat myself ik).

**Comment by bjorn** [comment]
This would be a nice feature, though I would probably prefer the primary search function to take more the form of the Qt Creator "Locate..." (Ctrl+K) feature. The right side of the open documents tab bar seems like a suitable place for something like this.

Of course, that's a little bit more tricky since it involves a bit more complicated input handling. On the other hand, Qt Creator source code can be used as a reference.

**Comment by bjorn** [comment]
It just occurred to me that another option would be to add a filter box on top of the objects view, like I did in the "Tile Stamps" dock. That shouldn't be very hard to implement. The downside is that it provides no real way of filtering on certain properties specifically, but I think you rarely need that.

**Comment by thabetx** [comment]
I started working on this issue. I'm trying to change the base class for ReversingProxyModel from QAbstractProxyModel to QSortFilterProxyModel and implement the filtering function, would like to know if this would be the preferred approach.

**Comment by bjorn** [comment]
@thabetx Nice that you started working on this! Actually turning the `ReversingProxyModel` into a subclass of `QSortFilterProxyModel` is likely not going to work or at least will be a lot more complicated than simply chaining these proxies together. Check out how `MapEditor::layerComboActivated` uses two chained proxy models

**Comment by thabetx** [comment]
Alright, I thought chaining would be more complicated, I will check it out, thank you.

**Comment by thabetx** [comment]
I'm not sure about group names should the search match them?
