### ISSUE TITLE
Be able to select objects behind other objects

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1491]
Currently, the only way to select objects covered entirely by other objects is to either move those other objects out of the way temporarily, or to hide them or their object layer.

It should be possible to select objects below other layers without resorting to such actions.

One suggested solution is to cycle between all objects at a certain location when the user hold the Alt modifier (without moving the mouse, because that would drag the objects). It may also be helpful to be able to see a list of all objects at a certain location in a menu.

Based on [feedback](http://discourse.mapeditor.org/t/feedback-after-a-couple-months-with-tiled/2090) from @eevee and others.

**Comment by issy123** [comment]
A way to do is is by searching an object in the objects view, or show the x and y property (and sort on it), so you know the overlapping objects

**Comment by faulknermano** [comment]
Right now, the selection is based on the bounding box. But I think it would be more intuitive, if by picking the foremost pixel of an object (ignoring those pixels with full transparency or alpha=0) would yield that object selected.

Photoshop has that capability: by holding down the CTRL modifier, with the Move tool selected, it picks the object whose pixel is under the cursor. In addition, Photoshop has a checkbox which will activate this 'select under cursor' function without having to use the CTRL modifier.

The interesting bit is that the Move is separate from Selection, so that you don't nudge objects inadvertently. I often mistakenly nudge an object in Tiled while selecting; it is mitigated by use of grid snapping, though snapping is sometimes not wanted.

Though this issue is about selection, I think manipulation is linked because there are no current ways to select only or transform only. My suggestion would be to adopt a similar functionality to Photoshop because I find it the clearest way of manipulating objects in a 2d space.

**Comment by bjorn** [comment]
> Though this issue is about selection, I think manipulation is linked because there are no current ways to select only or transform only.

Well, there is:

* Shift modifier to force the selection rectangle. No drag operation will be started then, even if you click on an object.
* Alt modifier to force the drag operation. The selection will not change when starting a drag.

Issue #1477 covers ignoring transparent parts of objects.

I'm not sure how much sense it makes to separate the selection and movement tools at this point. Tiled is a bit different from an image editor, and its interaction model in terms of object handling is more based on Inkscape.

**Comment by faulknermano** [comment]
@bjorn, yes I agree; that's cool. Apparently, I did not know about the Shift modifier and I think those two modifiers alone, satisfies my comments. Thanks for this info.i

I'm also glad to know that the transparent pixel issue is at the table. Thanks for your work.

**Comment by bjorn** [comment]
@faulknermano And now these hidden shortcuts are finally [covered by the manual](http://doc.mapeditor.org/manual/objects/#select-objects). :-)
