### ISSUE TITLE
Tile still selected even when the tileset is closed

### ISSUE THREAD

**Issue by ketanhwr** [bjorn/tiled#1502]
I noticed this bug while testing hexagonal tiles. I imported a hexagonal tileset and created a new hexagonal tilemap. Now I also created another tilemap (orthographic) and now after I had drawn some tiles in the hexagonal tilemap, I closed both the tileset and the map, but kept the orthographic tilemap open. The tileset is not visible in the toolbar, but still, I'm able to draw the last selected tile.

**Comment by bjorn** [comment]
Is the tileset added to the map again when you try to paint with it?

I think this happens when there is no other tileset, since the updating of the stamp will happen when another tileset is selected, or when the selected tiles change. Neither of these happen when the last tileset view is removed.

However, the tileset should be automatically added back to the map when you try to use that stamp. In general, there should be no problem with a stamp referring to a tileset that is not currently opened or already in use by the map. Such stamps can also be selected from the "Tile Stamps" view, for example.

**Comment by ketanhwr** [comment]
Apparently, there was another tileset open too, and when I paint with it, the tileset is not added.

**Comment by bjorn** [comment]
@ketanhwr Can you provide exact steps to reproduce the issue?

**Comment by ketanhwr** [comment]
Alright. I'll comment as soon as I recreate the issue.

**Comment by ketanhwr** [comment]
I'm not able to reproduce this error. Might've got confused back then, I'm closing this issue.
