### ISSUE TITLE
Tile colliders create 'unpredictable' key names in JSON export

### ISSUE THREAD

**Issue by adcgx** [bjorn/tiled#1514]
When you create a tile collider and export to JSON, the name of the key which contains the "objectgroup", _is_ the tileID. Example with a tile collider on tileID 2:
`"tiles":
            {
             "2":
                {
                 "objectgroup":
                    {
                     "draworder":"index",
                     "height":0,
                     "name":"",
                     "objects":[
                            {
                             "height":32,
                             "id":1,
                             "name":"",
                             "rotation":0,
                             "type":"closed",
                             "visible":true,
                             "width":32,
                             "x":0,
                             "y":0
                            }],
                     "opacity":1,
                     "type":"objectgroup",
                     "visible":true,
                     "width":0,
                     "x":0,
                     "y":0
                    }
                }
            }`

The problem with this is that many JSON deserializers, f.ex. the one in Unity which I'm using, needs to know the names of the keys in advance; this works fine for everything else, except tile colliders, where the name of the key "2" is unpredictable.

A simple solution could be to make 'tiles' an array of objectgroup's, and have 'objectgroup' contain the tileID as a variable with a predictable name like "tileid" f.ex:

`"tiles":[{
                 "objectgroup":
                    {
                        "tileid":2,
                     "draworder":"index",
                     "height":0,
                     "name":"",
                     "objects":[
                            {
                             "height":32,
                             "id":1,
                             "name":"",
                             "rotation":0,
                             "type":"closed",
                             "visible":true,
                             "width":32,
                             "x":0,
                             "y":0
                            }],
                     "opacity":1,
                     "type":"objectgroup",
                     "visible":true,
                     "width":0,
                     "x":0,
                     "y":0
                    }
            }]`

**Comment by bjorn** [comment]
> A simple solution could be to make 'tiles' an array of objectgroup's, and have 'objectgroup' contain the tileID as a variable with a predictable name like "tileid" f.ex:

Well, since "objectgroup" is not the only information that may be associated with the tile, it would have to look like:

`"tiles":[{ "tileid":2, "objectgroup": { "draworder":"index", "height":0, "name":"", "objects":[ { "height":32, "id":1, "name":"", "rotation":0, "type":"closed", "visible":true, "width":32, "x":0, "y":0 }], "opacity":1, "type":"objectgroup", "visible":true, "width":0, "x":0, "y":0 } }]`

However, I can't change this format without breaking everybody's code, so while I agree that in hindsight, I should not have used the tile IDs as keys (I think I did so because I thought it would make looking up the information associated with a specific tile faster), it isn't something that can just be changed and I would suggest you look for a JSON deserializer that can deal with it.

Personally I think this would be a rather strange missing piece of functionality, because it would mean that you can't even serialize the JSON data back to text, apart from possibly using some internal API, but why the heck would they keep the possibility to iterate a JSON object internal? :-S

**Comment by bjorn** [comment]
If you're talking about https://www.assetstore.unity3d.com/en/#!/content/9420, just look at the first two comments... apparently that library misses this functionality, and because of that people find it "not very useful for common purpose" and even "Useless".

I guess it will have its uses, but at $20, one would expect some solution for this... what with many decent JSON libraries simply available for free.

**Comment by adcgx** [comment]
I'm talking about the [built in JsonUtility class in Unity](https://docs.unity3d.com/ScriptReference/JsonUtility.html) (and yes, it's a pretty bad utility). Guess I'll look for alternatives.
