### ISSUE TITLE
Object layer coordinates features (snap objects to grid, no decimal pixels)

### ISSUE THREAD

**Issue by issy123** [bjorn/tiled#1559]
Hi, Me again :)

Got more features I would love tiled to have!

### Request 1 : Snap objects to grid
It would be nice if we could have a feature where you can snap objects to the tile grid.

### Reason
When you make a game that uses for example 64px by 64px tiles you sometimes want to apply custom properties to a tile.
How this works in tiled is that you add an tile in the object layer,
however this is a flexible tile, it does not have to be like an tile layer.
Snapping an object to the tilegrid would save my life.

### Request 2 : No decimal coordinates/pixels
It would be nice if I can disable having decimals in the x,y coordinates.

### Reason
I get annoyed when aligning objects. When I place two objects next to each other on tiled it looks like they are next to each other, however when I run it in my game they are spread out by a pixel.
This is because object1 has x:11.9 and object2 has x:12.0
This looks like x:12 and x:12 on tiled thus next to each other,
however when I run it, it is x:11 and x:12 (1px off) because it is not using decimals.

**Comment by bjorn** [comment]
> It would be nice if we could have a feature where you can snap objects to the tile grid.

Enable _View > Snap to Grid_ (or starting with Tiled 1.0: _View > Snapping > Snap to Grid_).

> It would be nice if I can disable having decimals in the x,y coordinates.

Using at least Tiled 0.18, enable _View > Snap to Pixels_ (or starting with Tiled 1.0: _View > Snapping > Snap to Pixels_).

Before Tiled 0.18, you could achieve snapping to pixels by instead enabling _View > Snap to Fine Grid_ and configuring the number of fine grid divisions in the preferences to equal the pixel size of your tiles.

> This is because object1 has x:11.9 and object2 has x:12.0
> This looks like x:12 and x:12 on tiled thus next to each other,
> however when I run it, it is x:11 and x:12 (1px off) because it is not using decimals.

You could also fix that by doing rounding instead of truncating. :-)
