### ISSUE TITLE
Add new point to Polyline or Poligon object.

### ISSUE THREAD

**Issue by NinjaFighter** [bjorn/tiled#157]
I cannot figure how to add points to polyline or poligon objects. (is it possible?)
Could be great if I could do a left click, over the line, and selecting an "Add a New Point" option.
Nowadays, I open the TMX file with notepad++ and add points manually when I need that.

**Comment by bjorn** [comment]
Better late than never (in truth, somebody stepped up to sponsor this improvement!): Double-clicking a segment now insert a new point at the clicked location, and you can immediately drag the new point to where you want it. I think it's a great improvement in usability.

The old "Split Segments" menu action remains available, mainly since it allows quickly splitting many segments, if you wanted that.

> I think could be great, if I can select two points only clicking the line, but it is a fairly trivial detail.

That's also implemented now. :-)
