### ISSUE TITLE
Topbar menu invisible in fullscreen

### ISSUE THREAD

**Issue by c64cosmin** [bjorn/tiled#1576]
Using the x64 windows10 snapshot, downloaded today.
When in fullscreen mode, the topbar menu is not displayed.
I can return back to normal windowed mode and the issue disappears.

**Comment by bjorn** [comment]
Hmm, can you show a screenshot? I've never seen this problem and would currently have no idea how to fix it. With "fullscreen mode", you mean when pressing F11 or also when simply maximizing the window?

**Comment by c64cosmin** [comment]
Doing more investigation the issues appears when pressing F11, having OpenGL enabled and there is a map open. Doing a screen shot and then pasting the image looks right(containing the topbar menu) but on the screen there is no topbar menus.
I suspect it's either a problem on how Windows10 handles windows with OpenGL contexts(most probably), or a bug on how Qt handles OpenGL windows.
An borderless, titleless windows might do the trick.

The issue disappears by disabling OpenGL in preferences.

**Comment by not-surt** [comment]
Sound like this is the problem: http://doc.qt.io/qt-5/windows-issues.html#fullscreen-opengl-based-windows

**Comment by bjorn** [comment]
> Sounds like this is the problem: http://doc.qt.io/qt-5/windows-issues.html#fullscreen-opengl-based-windows

Hmm, indeed, thanks for digging that down!

The suggested solution is to do:
```
QWindowsWindowFunctions::setHasBorderInFullScreen(tlwWindow->windowHandle(), true);
```
Though it says that this will add a 1 pixel border around the window to work around the issue. Since that may be annoying for scroll bars, I should probably only do that when OpenGL rendering is enabled.

Generally there isn't much of an advantage to the current OpenGL rendering btw, since it works through the QPainter API and as such it's usually not faster than software rendering.
