### ISSUE TITLE
JSON Tile-Set Format tiles array is needlessly difficult to parse.

### ISSUE THREAD

**Issue by JeremyWildsmith** [bjorn/tiled#1585]
Basically, the way it seems to be structured, the tiles value is an object with a variable number of fields where the field name represents the id of the tile in an array of tiles. Since the ID starts from 0 and grows up, it would make a lot more sense if this was just an array.

This is really awkward to process, you can't really de-serialize this structure into a class without some awkward hacks with a deserialization framework. It's a minor issue, but its very odd.

I understand tilewidth and type is also in the tiles, but this just makes it more difficult to work with. Why not separate them?

Consider the current format:
```
"tiles":
    {
     "0":
        {
         "image":"necro3_0\/5.png",
         "imageheight":32,
         "imagewidth":32
        },
     "1":
        {
         "image":"necro3_0\/4.png",
         "imageheight":32,
         "imagewidth":32
        }
    }
```

Why not:

```
"tiles":
    [
        {
         "image":"necro3_0\/5.png",
         "imageheight":32,
         "imagewidth":32
        },
        {
         "image":"necro3_0\/4.png",
         "imageheight":32,
         "imagewidth":32
        }
    ]
```

**Comment by bjorn** [comment]
Unfortunately when the format was set up this way, I was not aware of the difficulties this would cause when working with some JSON serializers. Of course, changing it now will break all existing readers, but it may be worth it anyway for Tiled 1.1.

However, tile IDs are not necessarily consecutive. When a tile is removed (when using an image collection tileset like in your quoted examples), the IDs of other tiles do not change since that would break tile references. This means the alternative format using an array would need to include the tile IDs in the tile objects.

**Comment by JeremyWildsmith** [comment]
Hey,

Yeah, I just noticed this with the IDs as well. I think it would definitely be better to have the ID as apart of the rest of the object.

I think if Tiled were to move in this direction for 1.1, it may be a good idea to do a quick pass over the rest of the formats as well to make sure they make sense. It's not just about ease of parsing, they'd also just generally become simpler.

I noticed an oddity in the world JSON format as well where not all objects in an array were of the same type. Consider the layers array, where we can have objectgroup and layergroup and tilegroup where type is specified by type field. It may actually be easier to keep this as it is (and it isn't a big issue to work around), but it is definitely worth considering since any serialization framework I've come across treats every element in an array as the same type. (The work-around is to just make one unionized type and processes the deserialized data per the type field)

Luckily, I am working with typescript so everything is pretty flexible and I've been able to get everything to work with typedjson without much trouble, but in a more rigid environment this could turn a simple task into a bit of a head-ache.

Thanks,

Jeremy. Wildsmith

**Comment by bjorn** [comment]
> I think if Tiled were to move in this direction for 1.1, it may be a good idea to do a quick pass over the rest of the formats as well to make sure they make sense. It's not just about ease of parsing, they'd also just generally become simpler.

Yes, in particular the way the properties are stored should be revised as well. They should probably be stored in an array of Property objects, so that each property can include its type instead of relying on the additional "propertytypes" object.

Regarding the polymorphism, I have no idea how one would do that differently, so ideas are welcome. There are 4 different layer types, but their order is relevant so they can't be put into 4 separated lists, unless each layer would store its "index" as a variable, but that would also create a difficult to work with serialization format. The same problem exists for objects, which while not using polymorphism in Tiled source code at the moment, could definitely do so in the future or in other implementations (though I'd probably prefer moving to an entity/component system).

**Comment by saeedakhter** [comment]
+1 on this issue

As a result of this structure "tiles": {  "0":  { ... },  "1"  {...},  ...

It makes it difficult (impossible?) to use Unity3d's JSON deserialization:
https://docs.unity3d.com/Manual/JSONSerialization.html

Unity3d expects to classes decorated with [Serializable] like this:

[Serializable]
public class TiledMap
{
    public string type;
    public int width;
    public int height;
    public string tiledversion;
    public int version;
...

Putting the ID inside the object list would solve the problem:
"tiles":
    [
        {
         "id": 0,
         "image":"necro3_0\/5.png",
         "imageheight":32,
         "imagewidth":32
        },

**Comment by bjorn** [comment]
@saeedakhter Yeah, let's remember to improve the format for Tiled 1.2.

**Comment by saeedakhter** [comment]
I managed to get Tiled building in Qt Creator.  I'm looking at tiled\plugins\json\qjsonparser\json.cpp - I see some QVariant <-> Json code, but I haven't really found the code dictates the JSON format.  Am I in the right place?

**Comment by bjorn** [comment]
@saeedakhter That's the generic JSON parsing code, which translates JSON into a QVariant or a QVariant into JSON. You'll want to look at `maptovariantconverter.cpp` and `varianttomapconverter.cpp` in `src/libtiled`. Thanks for having a look!

**Comment by saeedakhter** [comment]
@bjorn - ok I think I have the basics figured out.  I'm experimenting with new json formats:
https://github.com/saeedakhter/tiled/commit/a507f393cce4cd339eff1f0e92727fede5ab49d0

Before I invest a bunch of time and issue a pull request, I'd like to get your feedback on what I'm thinking:

1) I would rev the file version (2.0?  or maybe 1.2 to match the Tiled version?), on reading an existing file it would detect the version and read both the old format and the new format.

2) On writing it would only write the new format.  (otherwise we would need UI to prompt for which version to write?)

3) tiledproperties would look like this:
 "tileproperties":[
        {
         "Prefrab":"Floor*",
         "SortingLayer":"Floor",
         "tile":1
        }, 
        {
         "Prefrab":"Floor*",
         "SortingLayer":"Floor",
         "tile":2
        }, ...

4) tileproperties would look like this  (I don't feel as strongly about this, I could leave properties alone other than moving the id into a "tile: 1" field).
"tilepropertytypes":[
        {
         "properties":[
                {
                 "name":"Prefrab",
                 "type":"string"
                }, 
                {
                 "name":"SortingLayer",
                 "type":"string"
                }],
         "tile":1
        }, ...

5) what are your thoughts on layers?  I was thinking of breaking up the layer types into separate lists... tileLayers, objectLayers,etc.  I know the layer order is important so each item would need a "order: 0", "order: 1" to get them back into the correct sorted order.

Any other thoughts or requests welcome.

**Comment by bjorn** [comment]
1. I'm a bit torn between using 2.0 and 1.2, since 2.0 would be semantically more correct but 1.2 would match the next Tiled release. I think 1.2 should be fine.

2. Yes, let's just write the new format. If it makes things easier in every way, then I hope the new format will be picked up fast and we won't have too much use for an option to write the old format.

3. No. Since we will store the properties on each tile, there will no longer be a reason for a separate `tileproperties` entry.

4. No. Like at 3, there will no longer be a reaon for `tilepropertytypes` either. The properties will be stored on the tile objects, the same way they are stored everywhere else, but changed to an array:
```json
"properties": [
    { "name": "Prefrab", "value": "Floor*", "type": "string" },
    { "name": "SortingLayer", "value": "Floor", "type": "string" },
]
```

5. Is it really a problem for an array to contain multiple kinds of objects, using polymorphism? At least in this issue, it's specifically about the strange way the tiles are stored and the layers are not mentioned. Also in issue #1822, the Ezm-Loader does not change the way layers are stored. So I think it will be fine to leave that as-is.

**Comment by saeedakhter** [comment]
Sounds reasonable.  I understood your suggestion to be collapse the properties into the tile list like this:

 "tiles":[
        {
         "terrain":[0, 2, 2, 2],
         "tile":0
        }, 
        {
         "properties":[
                {
                 "name":"Prefrab",
                 "type":"string",
                 "value":"Floor*"
                }, 
                {
                 "name":"SortingLayer",
                 "type":"string",
                 "value":"Floor"
                }],
         "terrain":[0, 0, 0, 0],
         "tile":1
        }, 

I've got writing to the new format working, next I'll work on being able to detect and read either the new format or the old format.

https://github.com/saeedakhter/tiled/commit/8f265c221f044abab7ee21961a1b5b72ad104289

**Comment by bjorn** [comment]
@saeedakhter Seems fine overall, though you should probably remove `toVariant(const Properties &properties)`, and adjust `addProperties` to the new format and use that instead.

**Comment by saeedakhter** [comment]
I addressed your initial feedback, I'm able to write the new format and read both the old format and the new format.  However, I'm doing some testing before I issue a pull request.

https://github.com/saeedakhter/tiled/commits/master
