### ISSUE TITLE
Changing font on new text object resets pixelsize value.

### ISSUE THREAD

**Issue by Rakoonic** [bjorn/tiled#1596]
As title says. pixelsize is often reset to 1, although text object continues to be shown correctly (and you can see from the fontfamily line that the size is correctly.

v1.0.0 OSX

**Comment by bjorn** [comment]
Indeed, this happens on each platform when the font chooser dialog is used instead of changing the values directly in the property browser. It is because the font chooser dialog always sets the point size and not the pixel size. I'll need to find a workaround for this, probably converting the point size to a pixel size after the dialog is closed.
