### ISSUE TITLE
Inherited object type properties are not saved

### ISSUE THREAD

**Issue by mikeandtherest** [bjorn/tiled#1609]
I have created a Wall object type which has one property Thickness with the default value of 16. and then I have an actual object in the map called W1, which is of type Wall. In the left panel, under Custom Properties I can see the inherited property (Thickness: 16).

The problem is that when I save (in a .tmx file) or export (in a .json file), the inherited property is not saved in the file. So no Thickness property in the W1 json object.
Now, if I overwrite the property in the object's custom properties, and assign let's say 18 to it, when saving or exporting, the property is there in the file.

Is this an intended behavior?

**Comment by bjorn** [comment]
This is intended, because the value is only relevant for saving when you changed it from its default. This way, when you ever would decide to change the default value, all objects where you did not override this value will be automatically "adjusted", whereas when each value would have been copied into each instance, then all those values would somehow need to be updated, and an additional mechanism would need to be introduced to store that a value was overridden.

The idea is also, that if you need to, you can load the default values from the `objecttypes.xml` file. Though this file is currently not linked from the map file (issue #228).

**Comment by mikeandtherest** [comment]
Sorry but this makes absolutely no sense for me. If Tiled allows us to create an "object class" (i.e. the object type), having some properties and it also allows us to assign default values to those properties, then it should also save them in the file for the objects of that type.

Like in my example, I make an object type Wall with a prop Thickness of 16, and then I'll have maybe 1000 objects of that type. Basically what you're saying is that one should go and overwrite the Thickness property of all those 1000 Wall objects in order to have them in the file, which is a lot of redundant work.

So it's OK to have the possibility of overwriting the default prop values, but in many scenarios is way more important to be able to save the default values in the files, especially if you work with a huge number of objects of the same type.

I hope all this makes sense, thanks.

**Comment by bjorn** [comment]
For me it does not make sense to duplicate the same information all over the place. Each object already stores its type, and each type already stores all its default properties. So there is no reason for each object to also store all the default properties, since they can be simply loaded from the file storing the default properties for each type. Only when the value has been customized for a certain object does it make sense to store this changed value on the object.

**Comment by mikeandtherest** [comment]
Indeed that's another way of getting the needed props. I wonder if there are any future plans for saving the types data in the map file itself (or in the json file export)? In my case at least, it would be very helpful to have all data in the same file. Thanks again.

**Comment by bjorn** [comment]
> Indeed that's another way of getting the needed props. I wonder if there are any future plans for saving the types data in the map file itself (or in the json file export)?

So that is what issue #228 is about. Though for now I was planning to just include a reference to the `objecttypes.xml` file, it would of course also be an option to actually embed the types in the map file, but I would only consider this as an export option.
