### ISSUE TITLE
Information about the currently selected tile is no longer available

### ISSUE THREAD

**Issue by jppresents** [bjorn/tiled#1615]
While editing a map, in previous versions of tiled the properties for the currently selected tile were displayed. This included the index information for the tile.

Since this is no longer the case (tile properties are now only displayed when switching to edit tileset-view) it would be nice if the index of the currently selected tile could be displayed somewhere.

**Comment by bjorn** [comment]
Fixed in change 45de3db05f64842f625696ec69c2db3eae7c3d18 by making all information visible as read-only in the Properties view. The change will be included in Tiled 1.0.2.

[On the forum](http://discourse.mapeditor.org/t/how-to-display-tileset-properties-in-tiled-1-0/2493) people also indicated the usefulness of showing these properties.

Thanks for the feedback!
