### ISSUE TITLE
How to compile it on Win10?

### ISSUE THREAD

**Issue by Mactarvish** [bjorn/tiled#1656]
When I type qmke trying to build it, it tells me :Project ERROR: Use the tiled.qbs project file instead
However, how to use the qbs to build it ?

**Comment by bjorn** [comment]
Qbs ships with Qt Creator, so generally if you installed Qt you also have Qbs. By default it will be in `C:\Qt\Tools\QtCreator\bin`.

When you use Qbs outside of Qt Creator, it does require some initial setup regarding the compiler and Qt version it will use. See:

http://doc.qt.io/qbs/configuring.html
http://doc.qt.io/qbs/qt-versions.html

Generally, the easiest way is to compile from Qt Creator by opening the `tiled.qbs` file, since it will configure Qbs automatically based on the kits, which are automatically configured based on your system and installed Qt versions. It also immediately gives you a nice IDE to start making improvements to Tiled! :-)

**Comment by Mactarvish** [comment]
Thank you, but while I tried to run tiled.qbs using Qt Creator, it errors: 
error: import qbs.Environment not found
What should I do now?

**Comment by bjorn** [comment]
Apparently you're running a version of Qbs older than 1.6. You should upgrade (I'm not sure which version of Qt Creator this comes down to, but I would recommend just using the latest stable version).

**Comment by Mactarvish** [comment]
I solved it. Thank you very much.
