### ISSUE TITLE
Display flip/rotation bits in infobar

### ISSUE THREAD

**Issue by tomcashman** [bjorn/tiled#1707]
The bottom infobar (see image) currently shows the tile ID for the hovered tile on a layer. It would be good if it also showed the flip/rotation bits.

![tiledbits](https://user-images.githubusercontent.com/1745420/29741413-cf237792-8a6c-11e7-82bd-569a127f4400.png)

**Comment by bjorn** [comment]
Yeah, that could be useful. To avoid it taking too much space, maybe each bit should just have a letter associated with it, like V, H and D? So it would show as "51, 45 [1762 V,H] for a tile flipped both horizontally and vertically?

**Comment by tomcashman** [comment]
Yeah that'd be perfect.

**Comment by bjorn** [comment]
I hope it's fine to include this addition in a new snapshot next week, because I [just published one](https://thorbjorn.itch.io/tiled/devlog/8687/tiled-103-released-and-updated-snapshots-11-alpha2).

Here's a screenshot of how it looks:

![selection_201](https://user-images.githubusercontent.com/531764/29823646-93874be0-8ccf-11e7-9bf0-92b94bff3e8e.png)

**Comment by tomcashman** [comment]
No problem!
