### ISSUE TITLE
Automapping not working with my maps

### ISSUE THREAD

**Issue by drhayes** [bjorn/tiled#1713]
[bug.zip](https://github.com/bjorn/tiled/files/1260834/bug.zip)

Here's a link to my description: http://discourse.mapeditor.org/t/automapping-not-working-anymore/2683?u=drhayes

Here are the contents of the attached file:

* `assets/levels/test.tmx` Automapping works in this file.
* `assets/levels/runner1.tmx` Automapping does not work in this file.
* `assets/levels/rules.txt` Rules file.
* `assets/tiledrules/stone.tmx` The tilemap that includes the transformations.

Let me know if you need more detail!

EDIT: Whoops, actually attached the file this time.

**Comment by ketanhwr** [comment]
> Here are the contents of the attached file:

Which attached file..?

**Comment by drhayes** [comment]
Argh, file attached in the original comment.

**Comment by bjorn** [comment]
@drhayes Would it be possible to add all the images? I can't see what's supposed to be going on without all those stone tiles. If they're secret maybe you could e-mail them to me instead.

**Comment by drhayes** [comment]
Sure, here are the tiles I'm using:
[tiles.zip](https://github.com/bjorn/tiled/files/1281931/tiles.zip)

**Comment by bjorn** [comment]
I could not reproduce this issue with Tiled 1.0.1, 1.0.2 or 1.0.3, but I did notice that on `master` the rules are no longer working. Since you said on the forum that it broke for you with version 1.0.2, can you please verify your version and maybe tell me where you downloaded it from, so we can find out if you're in fact using a version compiled from `master` (like a development snapshot) or whether I need to do something else to reproduce the issue on 1.0.2?

It would be nice if you could still provide also `entities.tsx` and `collision.tsx`, but it appears anyway that it can apply the rules also when those files failed to load (it will just create missing tile markers).

I don't have time to debug the issue now anymore, but I'll aim to look into it soon.

**Comment by drhayes** [comment]
Yup, definitely version 1.0.2, downloaded from itch.io via mapeditor.org. Thanks for looking at this issue. I'll update to 1.0.3 via the itch.io app, see if I see the bug anymore.

In my own testing, I'm *pretty* sure it had something to do with my map having an additional tile or two vs. the rules tileset. In my further testing, that's the only difference I can find between the maps where automapping works and the ones where it doesn't.

I've included `entities.tsx` and `collision.tsx`, just in case.
[tilesets.zip](https://github.com/bjorn/tiled/files/1283340/tilesets.zip)

**Comment by bjorn** [comment]
> In my own testing, I'm pretty sure it had something to do with my map having an additional tile or two vs. the rules tileset. In my further testing, that's the only difference I can find between the maps where automapping works and the ones where it doesn't.

Ok, so that part is actually _not_ related to the Tiled version, but to the map having an additional file. When I look at your map `text.tmx` I see that it includes two tilesets called "tiles", but the second one includes an additional tile `stoneBackgroundTiles0.png`. This makes that tileset different from the tileset in the rules map `stone.tmx`, so when you place tiles from there the rules do not work.

This this issue of tilesets being slightly different only occurs when using _embedded tilesets_, and I would hence suggest to use an external tileset also for the "tiles" tileset. That way the rules and the map can both refer to this external tileset file, and when you add another tile the rules will keep working.

However, on the `master` branch (and thus the snapshot builds) I can't get the rules to work with either tileset, so I still need to look into what's going on there.

**Comment by bjorn** [comment]
For ease of use I'm uploading the provided archives as a single bundle:

[assets.zip](https://github.com/bjorn/tiled/files/1295681/assets.zip)
