### ISSUE TITLE
Tool Shortcut keys get disabled when in "Tabbed" Mode

### ISSUE THREAD

**Issue by Archeia** [bjorn/tiled#1718]
**The Issue:**
While mapping, press Tab and then press R/B/E/F. For some reason, the keys are disabled during this mode. However, if I press Tab again and use any of the R/B/E/F shortcut keys, they will work again.

**How the issue can reproduced**

- Open Tiled and "set up a map"
- Click a layer
- Press Tab to hide the other windows.
- Try pressing any of the tool shortcut keys.

**What behavior you expected instead**

- I expected the tools to work on "full screen mode"

**What actually happened**

- Nothing. Shortcut keys like H (highlight layer on/off) works though!

**Tiled version, operating system, etc. if possibly relevant.**

- Version 2017.08.29. The one in itch.io

**Video Replicating the Issue:**
https://www.youtube.com/watch?v=Xb2OmHGl7a4
In the video, you can see that I'm pressing the shortcut keys as the icons are updating. Once I hit tab it doesn't work. But H key work.

**Comment by bjorn** [comment]
Hmm, this happens because the shortcuts are automatically taken care of by Qt by setting them on the tool bar actions. But when the tool bar is hidden, which happens in the "Tab" mode as well, those shortcuts get disabled.

I think there are two reasonable ways of resolving this issue:

* Instantiating QShortcut instances for the tools that remain active even when the tool bar is hidden.
* Adding the tools to the menu, which would keep the shortcuts active also when the tool bar is hidden.

Thanks for the report!

**Comment by Archeia** [comment]
I think tools to remain active than adding in the tools menu would be a lot better. It's mostly because it's easier to reach where you need the less lists there are 💃

**Comment by bjorn** [comment]
I've pushed a change using QShortcut for now, since this could potentially go into a 1.0.4 release (if this happens, probably not). On `master` I will consider adding a new "Tools" menu (which, just to be clear, would also make sure the shortcuts stay working).
