### ISSUE TITLE
Rightclick on tab to close tabs

### ISSUE THREAD

**Issue by issy123** [bjorn/tiled#1720]
- close other tabs
- close all tabs
- close all left to this tab
- close all right to this tab

**Comment by bjorn** [comment]
At least "Close All Tabs" is already in "File -> Close All (Ctrl+Shift+W)", so I see no point in adding that one.

I see both Chromium and Firefox only have "Close Tabs to the Right" and not a "to the Left" version. If even such tab-heavy applications don't have it it makes me think there isn't enough demand to worry about that one in Tiled.

So I guess adding these should be enough:

* Close Other Tabs
* Close Tabs to the Right

Or have you personally been missing the other ones?

I also think we should add middle-click for closing a tab.

**Comment by EJlol** [comment]
Some programs with a tabbar also support opening a new tab. For instance in Firefox you can use the middle-click to open a new tab, and in notepad++ you can double click to open a new tab. Chrome and Edge only has a button in the tabbar, and Paint.net doesn't support opening a new tab in the tabbar at all. 

I'm not sure how usefull or confusing (since there are maps and tilesets in the tabbar) a feature like this would be for Tiled, but you might also look into that.

**Comment by bjorn** [comment]
> I'm not sure how useful or confusing (since there are maps and tilesets in the tabbar) a feature like this would be for Tiled, but you might also look into that.

Indeed, such an action would either have to pop up a dialog for creating a new map or tileset, or the tab would need to show some kind of "start page" similar to what Tiled currently shows when nothing is open. But I think such functionality wouldn't be very useful.
