### ISSUE TITLE
Can't remove object by shortcut key : Delete

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#1744]
macOS 10.12 ,  Tiled 1.0.3

**Comment by bjorn** [comment]
Will have to try to reproduce it and see if I can find a fix. Just wondering, but where do you have the focus, in the objects list or in the map view? Or it doesn't matter? Also, did you try to use Backspace instead of Delete?

**Comment by satu0king** [comment]
I am on a mac, I was able to delete both objects with the Backspace key and Delete Key (fn+Backspace). This worked in the object list and map view.

**Comment by finscn** [comment]
<img width="850" alt="2017-10-10 3 13 02" src="https://user-images.githubusercontent.com/288367/31354421-00ad1226-acfc-11e7-8b9f-137dd1a41314.png">

I select the object(a rect object)  in object-layer

**Comment by bjorn** [comment]
I've finally ordered a more recent Mac Mini (the one I have from 2009 has become unbearable, new one is from 2011) - when it arrives I will try it out as well, though for now the package went missing in action...

It could of course matter where the focus is. But since @satu0king reports it working with focus on map view as well as objects list, I wonder what else could be causing this.

**Comment by bjorn** [comment]
I tried it with Tiled 1.2.2 on macOS (built against Qt 5.6) and was unable to reproduce this issue. Please let me know if it still happens again (and also let me know then, if it still happens in the latest development snapshot, built against Qt 5.12).
