### ISSUE TITLE
[SUGGESTION] About origin of isometric map.

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#1745]
Now,  in normal isometric , the origin is the first tile's  top-middle  ( the red point in top image ),
in staggered isometric, the origin is the first tile's  top-left  ( the blue point in bottom image).

There are different ways to define the origin.

I hope there is  only one way ,  e.g. both  use the first tile's  top-middle (the red point).

<img width="383" alt="2017-09-17 10 38 12" src="https://user-images.githubusercontent.com/288367/30517545-a17b6d0a-9b28-11e7-8070-cdbc1ef4150a.png">

**Comment by bjorn** [comment]
I think it makes sense if you include the X and Y axes:

<img width="383" alt="origin-isometric-staggered" src="https://user-images.githubusercontent.com/531764/59191190-191dc680-8b7f-11e9-9fa3-bf81c8a1fe1a.png">

The staggered isometric origin would arguably get less consistent when we move it to the top corner of the first tile. The only real alternative I'd consider would be to use the center of the fist tile, so that any positive coordinate is never occupying some gap at the border. But that would be somewhat inconsistent with the "bounding rect" or the grid.

In the end the position of the origin is somewhat arbitrary, and for compatibility reasons it would not be a good idea to change it now.
