### ISSUE TITLE
Object's gid is wrong if flipped horizontally, when exporting as json

### ISSUE THREAD

**Issue by Knight52** [bjorn/tiled#1750]
I mean, object in object layer. Not tiles.

I flipped the object horizontally, then export as json file. The flipping properties aren't there at all, and the object's exported gid went from 2398 to 2147486046.

Tiled 1.0.3. Windows 10

**Comment by bjorn** [comment]
This `gid` contains the bits used for flipping, just like it does in the TMX map format. See the section about [tile flipping](http://doc.mapeditor.org/en/latest/reference/tmx-map-format/#tile-flipping).

Since the higher bits are used for flipping, the numbers become huge. When we clean up the JSON map format in a backwards-incompatible way, I will consider avoiding the use of bitflags here.
