### ISSUE TITLE
new Wang tiles interface is painful. Please create a wang-builder panel.

### ISSUE THREAD

**Issue by nobody-special666** [bjorn/tiled#1757]
The current interface is extremely inefficient and searching for the correct permutation in a list is aweful.
If you have 2 corners and 2 edges then there are 256 permutations.
I would suggest a builder panel, where you can toggle the correct corner and edge values you desire.

Thank you for this wonderful new feature and for Tiled.

**Comment by bjorn** [comment]
> The current interface is extremely inefficient and searching for the correct permutation in a list is aweful.
> If you have 2 corners and 2 edges then there are 256 permutations.

Yes, because that list can quickly get huge, there is a "Colors" view in addition to the "Patterns" view, where it is easier to select and paint with a specific color to mark your tiles. Did you try this?

Of course, there are still improvements to be made. Maybe you'd like to describe your "building panel" suggestion in a little more detail, best even with a mock-up or sketch, because I'm not sure if I understand exactly what you mean.

> Thank you for this wonderful new feature and for Tiled.

You're welcome! This feature is mostly the work of @Bdtrotte, who worked on it this summer as part of the Google Summer of Code. That is unfortunately over now, but we're still looking for feedback and I will try to make some improvements before releasing Tiled 1.1.

Thanks for trying it out!

**Comment by nobody-special666** [comment]
Thank you, yes the colors tab is perfect. :)
