### ISSUE TITLE
Resizing a tileset image doesn't reset the XML properties stored in TSX file

### ISSUE THREAD

**Issue by mikest34** [bjorn/tiled#1758]
Steps to recreate

- create a new tileset from existing image
- import tileset to map
- increase the height of the tileset image
- replace the image in folder where tileset saved
- XML property "tilecount" on "tileset" will not have updated
- XML property "height" on "image" will not have updated

verified on Tiled 1.0.3 on OSX

**Comment by bjorn** [comment]
You mean that after replacing the image, the tileset was actually reloaded and the tiles were available in Tiled, but the TSX file wasn't updated? There are two things to note here:

* Tiled does not by itself save a file. If you want those values in the TSX file to be updated you will have to at least save the TSX file. Do the values update when you explicitly save the file after replacing the image?

* Tiled does not need the `tilecount` and `height` properties in the TSX file to be updated in order for the tileset (and maps using it) to be loaded correctly. This is because those properties are merely hints (that only represent the state when the file was saved), and Tiled should deal with the fact that the tileset may have changed size since then.

Did you run into any problems due to these properties not being updated?

**Comment by mikest34** [comment]
Hey, thanks for the response. I did not try saving the Tileset file in Tiled. I'll see if that resolves it when I get a chance. I guess I assumed that the Tileset was being updated because, as you said, Tiled seemed to not have any issue with the update to the external file. The issue is that the Tiled2Unity plugin seems to depend on these values for created their meshes. The problem was visible in Unity with the wrong tile (or portion of a tile) being displayed.

It seems like if Tiled creates these files, then maybe it should maintain them when it notices the file has changed because external programs are referencing them. Now that I know about the problem it's no big deal but others might waste a lot of time trying to figure out what was going wrong.

It's possible that an issue needs to be opened with Tiled2Unity but I am guessing he considers these XML files as an API (of sorts) describing the current state of the map and tilesets.

**Comment by bjorn** [comment]
@Seanba Do you know whether Tiled2Unity needs these properties to be up-to-date?

Since Tiled currently has no auto-save and the affected external tileset may also not be open "explicitly" (it could just be loaded because a map referenced it), it is not immediately obvious to me what would be the best way to ensure these properties reflect the last state seen by Tiled.

**Comment by Seanba** [comment]
Hi there, @bjorn. Sorry for the really late response but I try to notify users when such properties are out of date in SuperTiled2Unity so that they can go back back to Tiled and force a save.

**Comment by bjorn** [comment]
@Seanba Ah, no problem. I'll close this old issue since I think generally these values should update, as long as you re-save the file and apart from the bug you've reported at #2072.
