### ISSUE TITLE
Testing wang brush: it doesn't seem to allow painting like the terrain brush

### ISSUE THREAD

**Issue by nobody-special666** [bjorn/tiled#1776]
The terrain brush lets you easily paint grass over the water.
 
![image](https://user-images.githubusercontent.com/901271/31333490-4911026e-acb8-11e7-8f79-c15ba0a7405b.png)

I setup wang colors for the isometric_grass_and_water.tsx 
![image](https://user-images.githubusercontent.com/901271/31333153-fa2ece20-acb6-11e7-97bf-a1073560d3d9.png)

But I cannot paint grass over the water. 
![image](https://user-images.githubusercontent.com/901271/31333646-e11fdf76-acb8-11e7-9aed-2e212bad5096.png)

The documentation for the wang brush is a little unclear but it claims the wang brush should
work similar to the terrain brush, which would be extremely powerful but it doesn't seem to work.
I tried painting by edge or corner, holding Control or not, but nothing seems to work.
Am I using the tool wrong or misunderstanding what it's supposed to do?

So far it only seems to allow painting random grass over grass tiles and random water over water tiles.

**Comment by bjorn** [comment]
First of all, note that in the Tileset properties, you can specify that the tileset orientation is isometric and adjust the grid width and height so that it will render the overlay properly.

But, indeed the Wang Brush works a little different than the Terrain Brush, in that when the attempted edit can't be made using the available tiles, it renders a red marker and does not change the map. The Terrain Brush instead will attempt to modify a larger area of the map in order to make the edit work.

Nevertheless, the Wang Brush should really be able to make the edit you were trying to do, since that set is complete. So I think you may not have the Wang tiles defined correctly. The `desert.tmx` example map has Wang tiles set up for example, and they work for me. Another thing that may cause such problems is when you somehow managed to have two tilesets.

**Comment by bjorn** [comment]
For testing purposes I've defined the Wang set for the isometric grass and water example.

**Comment by nobody-special666** [comment]
Thank you. I see now that i was incorrectly using an edge count of 2 instead of 1.

**Comment by bjorn** [comment]
Ah, right, I hadn't noticed that. When you set it up like that and use the Wang Brush, it will be trying to change just the corners or just the sides, while for it to find any matching tiles it would need to change them together.
