### ISSUE TITLE
[GMX-Exporter] Add 1000000 to layer depth of tiles

### ISSUE THREAD

**Issue by TrunXGIT** [bjorn/tiled#1814]
In GameMaker 0 is the standard depth value for new objects.
The standard depth value for a new tile layer is 1000000.

So it's quite common to use values between -1000 to 1000 to order your objects.
Values around 1000000 for background elements and huge negative numbers for foreground elements.

Tiled exports it's tile layers at the depth of 1, 2, 3... so basically the same depth values the objects in a GM-Project are usually using.

Simple solution: Add 1000000 to the depth on export.

**Comment by bjorn** [comment]
Interesting suggestion. It sounds like it would indeed be good to start counting at 1000000 then.

Note that in the meantime you can set a custom `integer` property called `depth` on your layers, and Tiled will then export those layers with that depth instead of using the layer index. Seems like I missed this property in [the documentation](http://doc.mapeditor.org/en/latest/manual/export/#gamemaker-studio-1-4). The property already existed since Tiled 0.18.

**Comment by bjorn** [comment]
This has now been implemented and will be included in the next development snapshot.

> In GameMaker 0 is the standard depth value for new objects.

While I could see the depth in GameMaker for tiles indeed defaults to 1000000, I did not see any depth setting for objects. Also I don't see a "depth" attribute for instances in the room XML file. What are you referring to here?

**Comment by TrunXGIT** [comment]
You can find the input field for "Depth" inside the object properties on the left side. Instances inherit the depth value from the object. You can overwrite it by changing the "depth" variable in the creation code.

**Comment by bjorn** [comment]
> You can find the input field for "Depth" inside the object properties on the left side. Instances inherit the depth value from the object. You can overwrite it by changing the "depth" variable in the creation code.

Ah, that explains why I couldn't find it. I was looking for it while placing instances, not while editing objects. Speaking of creation code, I should make sure to get around to #1768 soon.
