### ISSUE TITLE
Tiled keeps on crashing after recent pull

### ISSUE THREAD

**Issue by keshav2010** [bjorn/tiled#1819]
I recently pulled the repository so as to stay updated with it but it caused tiled to crash, Initially i thought its because i messed up somewhere but after bit more inspection, it seems like this code is causing the crash 

`auto documentManager = DocumentManager::instance();`
`connect(ui->openFileButton, &QPushButton::clicked,documentManager, static_cast<void(DocumentManager::*)()>(&DocumentManager::openFile));`

(tiled/src/noeditorwidget.cpp)

Upon deleting this piece of code, the program executes however when i undo changes so as to include this code back, the program again crashes.

**Comment by bjorn** [comment]
Oh gosh... this is due to #1818, where a change I suggested did not actually work but both the submitter as well as me have failed to test it...

The crash is due to infinite recursion as the DocumentManager tries to create a NoEditorWidget and the NoEditorWidget tries to make a DocumentManager... we'll need to avoid this mutual dependency.
