### ISSUE TITLE
Qbs Windows installer builds failing

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1820]
The Windows installer (MSI) file randomly fails to build since upgrading Qbs from 1.7 to 1.9 (I think it's also broken on 1.8). A fix was attempted (938bda37eced8f373b9b07464b7a98d9dd858e2b), but it doesn't work. Examples of failed builds:

* https://ci.appveyor.com/project/bjorn/tiled/build/1.0.2834/job/a55ks59a85v7mpy3 (`tengine.dll` wasn't linked yet)
* https://ci.appveyor.com/project/bjorn/tiled/build/1.0.2867/job/ybwqt1hcw2no0yso (`tiled.exe` wasn't linked yet)

Hopefully @jakepetroules will be able to help track down why the installer rule isn't properly waiting for the other products to be built.

An alternative solution could be to run the build twice, and only request the installer to be built the second time.

**Comment by jakepetroules** [comment]
Sorry, this was a simple error on my part. The `inputs` property of that Rule I gave you should be `inputsFromDependencies`. Basically, here's what happened: There were no artifacts tagged `installable` in the `installer` product defined in installer.qbs, so your Rule producing a wxi file never got invoked since it did not have any inputs (if a Rule has no inputs, it is skipped even when it would otherwise be invoked). When you change to inputsFromDependencies, the rule will be invoked because the product does indeed have dependencies on products which do produce artifacts tagged installable.

So, try making that change and reverting your https://github.com/bjorn/tiled/commit/b1e3331fcd6b319dcb9a4d2d0bdbb6d14118efbe workaround and let me know if the issue persists.

I also posted some inline comments on the original https://github.com/bjorn/tiled/commit/938bda37eced8f373b9b07464b7a98d9dd858e2b change.

**Comment by bjorn** [comment]
@jakepetroules Thanks a lot! I guess the distinction between `inputs` and `inputsFromDependencies` makes sense, but I don't know how I should have found out about this myself. :-/

**Comment by jakepetroules** [comment]
It _is_ documented: http://doc.qt.io/qbs/rule-item.html#rule-properties but I can see how it might be easy to miss.

If you have some feedback on how we might make the documentation clearer, please do open a bug report and let us know!

**Comment by bjorn** [comment]
> It is documented: http://doc.qt.io/qbs/rule-item.html#rule-properties but I can see how it might be easy to miss.

Yeah, the problem is you'd first have to know what you are looking for.

One improvement that could be made, is to refer to the `inputsFromDependencies` property from other places. For example to explicitly document that the `inputs` property only applies to _product-local_ files, and that you need to use `inputsFromDependencies` if you want to pull in inputs from other products.

Also, of course you need to integrate Qbs help into Qt Creator and make it available context-sensitive when editing Qbs files. :-)

**Comment by jakepetroules** [comment]
> Also, of course you need to integrate Qbs help into Qt Creator and make it available context-sensitive when editing Qbs files. :-)

This should already work in Qt Creator 4.4. Try hovering over 'Product' and pressing F1.

Also, I thought of a cleaner solution so you can remove the workaround added in 938bda3: https://codereview.qt-project.org/212573

**Comment by bjorn** [comment]
> This should already work in Qt Creator 4.4. Try hovering over 'Product' and pressing F1.

Ah, this it's working for me in 4.4.1 on Arch Linux. It has no Qbs help available in Help mode either. Might be a packaging issue then.

> Also, I thought of a cleaner solution so you can remove the workaround added in 938bda3: https://codereview.qt-project.org/212573

That looks like a nice solution indeed!
