### ISSUE TITLE
Keyboard shortcuts broken under wayland

### ISSUE THREAD

**Issue by kamstrup** [bjorn/tiled#1821]
Running Tiled 1.0.3 on Ubuntu 17.10 here. All keyboard shortcuts with the Ctrl modifier are broken. Ie. nothing happens.

I believe it must be related to this:
 * https://bugreports.qt.io/browse/QTBUG-54367

If true a rebuild against Qt 5.7.1 should be enough for a fix.

**Comment by bjorn** [comment]
From where did you install your Tiled? The Linux build available for Tiled 1.0.3 on itch.io was done against Qt 5.8 (don't know which patch version).

You could install the development snapshot, which ships with Qt 5.9.2.

**Comment by kamstrup** [comment]
I just compiled revision 105635783321215fb0b986358656bfc5ed468bbd (latest master) against Qt 5.9.3 and keyboard shortcuts are working fine again :+1: 

So I guess this boils down to a request for a new release built against latest Qt :-)

Thanks for an awesome product!!

**Comment by kamstrup** [comment]
I got Tiled 1.0.3 from itchio, the appimage version. I am not sure how to check which version of Qt it is compiled against

**Comment by bjorn** [comment]
> I just compiled revision 1056357 (latest master) against Qt 5.9.3 and keyboard shortcuts are working fine again

Nice. And even better, now you've got your build environment set up to make your own Tiled patches! :-)

> So I guess this boils down to a request for a new release built against latest Qt :-)

Did you try the snapshot available on itch? It should be pretty stable. However, building a new release isn't a bad idea since you're surely not the only Ubuntu 17.10 user affected by this... I'll see about doing this soon.

> Thanks for an awesome product!!

You're welcome!

> I got Tiled 1.0.3 from itchio, the appimage version. I am not sure how to check which version of Qt it is compiled against

Unfortunately there is no easy way. May be possible to examine the shipped Qt libs after extracting the AppImage. I should add the Qt version to the About dialog...

**Comment by bjorn** [comment]
Tiled 1.1.0 is now released and should not have this issue since it's built against Qt 5.9.2 (I should remember to update to Qt 5.9.3 for Tiled 1.1.1).
