### ISSUE TITLE
New format to export tiled map

### ISSUE THREAD

**Issue by Jass91** [bjorn/tiled#1822]
Hi, I was thinking, maybe you could add support to export tiled to a new format (ezm). I created a json structure to easily describe a map, I also created a lib to read and render an ezm map (ezm relies to "easy map") , I think it will be great if you add support to it.

If you wanna see an working example, please refer to:

https://github.com/Jass91/Ezm-Loader

**Comment by bjorn** [comment]
Hmm, your loader looks very similar to the JSON format already supported by Tiled, with the main differences being how tiles are referenced and how properties are stored. But are those differences really worth another map format?

Regarding the format of the properties, the way you're storing them would actually be the way I'd prefer to store them. But this could be done by just changing it it and raising the JSON format version.

I think the list of tiles should stay inside the tileset, but I do agree that storing them as a list rather than as an object with the tile IDs being the keys would be better. This is another thing that could be changed with a version upgrade.

Of course, changing the JSON format and incrementing the version leads to incompatibilities in existing libraries, but if the change makes sense and makes things easier then I don't expect anybody will really be annoyed that they need to adapt a bit of loading code.

**Comment by bjorn** [comment]
Oh btw, if I missed any other major differences please highlight them.

**Comment by Jass91** [comment]
You are right, I created it based on your format. I created it, becauae xtiled lib its not easy to render a map, so i have created my own parser e loader, as you can see. I really Love Tiled, so if de can export ezm with Tiled, se need Just 2 lines to see our map loaded on XNA. Thanks for your time

**Comment by bjorn** [comment]
Related to issue #1585.

**Comment by saeedakhter** [comment]
@Jass91 have a look at https://github.com/bjorn/tiled/pull/1868, it should be considerably easier to parse.

**Comment by Jass91** [comment]
I checked out, I have some doubts about it, for instance, if you use more than one tileset, how you identify the source tileset giving a tile id? I was looking for something more descriptive, semantical like the way I've proposed here [here](https://github.com/Jass91/Ezm-Loader)

**Comment by bjorn** [comment]
> if you use more than one tileset, how you identify the source tileset giving a tile id?

@Jass91 That would work the same way it did before. After clearing the flipping flags from the global tile ID stored in the tile layer, you find the tileset with the highest `firstgid` that is lower-or-equal than the global tile ID. Then you subtract the `firstgid` to get the local tile ID within the tileset.

Your approach of storing the tiles in their own array separately from the array of tilesets is simpler, but it does not work for external tilesets. Actually if you don't care about external tilesets, then I would not bother with storing "tile IDs" at all, since the tile layer could just refer to the tiles by their index in the tiles array.

Do you see any other issues that are not addressed by @saeedakhter's changes?

**Comment by Phlosioneer** [comment]
This can probably be closed, especially with the scripting API now able to add new map formats and modify existing formats.
