### ISSUE TITLE
Big image import results in a black image

### ISSUE THREAD

**Issue by sennewood** [bjorn/tiled#1843]
I added an image layer and imported a big image (6622x4685px @ 200dpi) and got this result:
![blackimage](https://user-images.githubusercontent.com/406414/34461899-c2f71904-ee37-11e7-9c51-0f8b48d4a78c.png)

When I use 120 dpi, the image will be shown correctly, but it's to small for my purpose and I doesn't found a resize option.

**Comment by bjorn** [comment]
Is this a screenshot of Tiled or of your game?

Did you enable OpenGL rendering, and if so, does it work properly when you disable it?

**Comment by sennewood** [comment]
It's from Tiled and deactivating OpenGL helped.
Thank you :)

**Comment by bjorn** [comment]
Right, so the problem was that the image was too large to fit on a texture (likely texture size limit is 4096x4096, but on some hardware it will be lower). There is no automatic splitting of the image in smaller pieces, so it failed to render entirely.

It is not a problem without OpenGL, since on the CPU the texture limit does not exist.

I consider fixing this issue in OpenGL mode out of scope for Tiled. If you want to use OpenGL, just make sure you don't go over the texture size limit. :-)
