### ISSUE TITLE
Offsetting map over map size on "infinite" mode loses data

### ISSUE THREAD

**Issue by Velocity-** [bjorn/tiled#1866]
When offsetting a map as a whole on "infinite" mode, offsetting outside the map bounds deletes the map data that would fall off instead of A) resizing the map or B) handling it in a way where map size is ignored.

Reproduction steps:
 - Create a new 100x100 infinite map
 - Create a couple tiles
 - Map -> Offset map...
 - Set x and y offsets to 1000
 - Notice map data is gone

Way around this issue is to go to map->resize, then resize the map to a large enough data set and then reposition the map.

Version: latest development snapshot from itch.io page (2018.01.23)

**Comment by ketanhwr** [comment]
Hmm this is strange.

**Comment by bjorn** [comment]
Well, it's because `TileLayer::offsetTiles` only writes within the boundaries it is given. We'll probably need to handle infinite maps specially here.

I also noticed the "Wrap" checkboxes always get disabled for infinite maps, which is not what we want, because it still makes sense to enable them in case you're offsetting within a selection.

I'll see if I can still include a fix for this in the Tiled 1.1.2 I am planning to do tomorrow.

**Comment by Velocity-** [comment]
Awesome job, @bjorn :)
