### ISSUE TITLE
Tileset contains wrong indices after deleting tiles from it

### ISSUE THREAD

**Issue by DerChrisIstDa** [bjorn/tiled#1869]
Help shows me Version is 1.1.1, but I downloaded newest version of Tiled 3 weeks ago.

How to reproduce: 
- create a tileset
- make a map using this tileset
- delete tiles from tileset, accept warnings
- save map using 'csv'
- in text editor, check the tileset and the map
In my case indices in tileset started at 2 (should be 0?) and indices in map started at 3.

**Comment by bjorn** [comment]
> Help shows me Version is 1.1.1, but I downloaded newest version of Tiled 3 weeks ago.

I don't understand the "but" here, because three weeks ago I had indeed just released Tiled 1.1.1. :-)

> delete tiles from tileset, accept warnings

What warnings are you accepting here? The ones telling you that you're removing tiles that are used by the map? That's fine.

> In my case indices in tileset started at 2 (should be 0?) and indices in map started at 3.

Deleting tiles does not change the tile IDs of other tiles in the tileset. That is mainly because a tileset can be shared between multiple maps, in which case shifting those other tile IDs would break all tile references in any other maps that use the tileset.

There is no way to get rid of the tile ID "gaps" left by removed tiles. In general this is not a problem. If you are worried about memory usage, you may just want to store your tiles in a map instead of an array (which is what Tiled does).
