### ISSUE TITLE
File Open dialog rendering black in Ubuntu 16.04

### ISSUE THREAD

**Issue by thoughton** [bjorn/tiled#1882]
Hi,

I'm a new Tiled user and also a new Ubuntu Linux user.

I've installed Tiled (v.1.1.2) via the Itch.io application (which I installed via its official PPA).

I've found that the File Open dialog window seems a bit broken: it's rendering mostly black, and some of the text (eg. when creating a new folder) looks corrupted. Please see the screenshot below:

![tiled_open_dialog_bug](https://user-images.githubusercontent.com/38389/36282625-a12b2d0c-1299-11e8-8d4f-9e9129c00d97.png)

Here's some system info:
```
OS: Ubuntu 16.04.3 LTS x86_64
Kernel: 4.4.0-112-generic
DE: GNOME
WM: GNOME Shell
WM Theme: Adwaita
Theme: Adwaita [GTK2/3]
Icons: Adwaita [GTK2/3]
```
The only major change I've made to the 16.04 LTS installation is to switch from the Unity desktop to GNOME (via the offiicial PPA).

Any help on how to fix this would be much appreciated. Thanks!

**Comment by bjorn** [comment]
Could you try whether it helps to use the latest development snapshot, which is built against Qt 5.9.4 instead of Qt 5.9.3? There's a small chance it might help. If not, I'll ask again after the development snapshots have been updated to Qt 5.10.1.

In general, it's the native GTK file dialog so I think there's likely nothing I can do about it from the Tiled side. Though you could try to switch from "Tiled Fusion" to the "Native" theme in the preferences (and let me know if matters anything).

**Comment by thoughton** [comment]
Hi @bjorn, thanks for the reply, sorry it's taken me a while to get back to you about this.

Some good news: I eventually solved my problem by building from source! (Using latest from Github master, built against qt 5.10.1 installed via linuxbrew.)

For the record, before building from source I did also try changing the theme in the preferences, and downloading latest binary release from Github, but neither of these worked.

I'll happily close this now, thanks! :+1:

**Comment by bjorn** [comment]
It's great that building Tiled yourself against Qt 5.10.1 installed with Linuxbrew (first time I heard of it) worked!

I've now also updated the Linux and Windows packages on itch.io to Qt 5.10 in the [latest development snapshot](https://thorbjorn.itch.io/tiled/devlog/26226/extend-and-join-polylines-with-ease). Could you try if that also resolves your problem? I think it may not since it could be a packaging issue rather than a bug that was fixed in Qt 5.10.

**Comment by thoughton** [comment]
Hi @bjorn, I finally got around to trying this, and now the itch.io version works fine for me too. Thanks very much! :)

**Comment by bjorn** [comment]
@thoughton Cool, thanks for trying it! So that means I should consider to upgrade to Qt 5.10 when I release a Tiled 1.1.4.
