### ISSUE TITLE
Editing Properties externally causes Error

### ISSUE THREAD

**Issue by phanxgames** [bjorn/tiled#1904]
**-     How the issue can be reproduced**

Create a new map with Base64/zlib compressed, add a property to the map or layer. 
Save the file to .tmx
Open the .tmx in notepad++ externally, edit the property value.
While Tiled is still open, it attempts a reload of the .tmx file and the error appears.

**-     What behavior you expected instead**

It should reload the .tmx properties back into Tiled without an error popping up.

**-     What actually happened**

An error appears, but it does seem to reload the properties, however as expected.

![tiled_bug](https://user-images.githubusercontent.com/5034306/37363249-ce23f242-26cd-11e8-8eb5-4bc1092cde15.png)

On repeated testing it appears to not always throw an error pop-up.

**-     Tiled version, operating system, etc. if possibly relevant.**

Windows 10, Tiled Version 1.1.3, 32-bit installed
I also reproduced with an old version 0.17

# ** * * * EDIT * * * **
I have narrowed it down to a conflict with Notepad++, this error does not appear when using standard Notepad...  We suspect it has to do with Notepad++ and the Tiled file watcher conflicting.

I have closed this issue.  Sorry to bother you.

**Comment by bjorn** [comment]
Don't just close the issue! I'm sure there is a way to make this work even when you're using Notepad++.

In fact, the problem here is that Tiled tries to reload the file as soon as it gets a change notification. This is wrong, since the program making modifications may not yet be done writing the file (as is likely the case here). To fix this, there should be a short delay before trying to reload the file, like maybe 250ms after the last file change notification (it should be a short delay for a human, but very long for a PC).

**Comment by bjorn** [comment]
I didn't test the change, but you should be able to edit your maps comfortably with Notepad++ now. The fix will be included in Tiled 1.4.
