### ISSUE TITLE
"Tiled Fusion" theme used by default, even though Breeze is available

### ISSUE THREAD

**Issue by Alexander-Wilms** [bjorn/tiled#1905]
I've installed Tiled from here: https://beta.flathub.org/apps/details/org.mapeditor.Tiled

As you can see here (https://github.com/flathub/org.mapeditor.Tiled/blob/master/org.mapeditor.Tiled.json), this package is built without any special options.

Since you [stated](https://github.com/bjorn/tiled/issues/786#issuecomment-58013905), that Tiled Fusion is only a fallback, I suspect it's a bug that "Standard" is not chosen, even though KDE's standard Breeze theme is available and works fine.

Fedora 27
Tiled Version 1.1.2
Qt 5.9

**Comment by bjorn** [comment]
> Since you stated, that Tiled Fusion is only a fallback, I suspect it's a bug that "Standard" is not chosen, even though KDE's standard Breeze theme is available and works fine.

Well, I stated that back in 2014 when there was no "Tiled Fusion" theme. The Fusion I referred to is the theme in Qt, which Qt uses as fallback.

Since then, I have made a customized theme based on Fusion which I called "Tiled Fusion" (released Aug. 2016), which is the default on Windows and Linux for Tiled. This is because I wanted to have a default theme that was more suitable for a graphical application like Tiled, where the native theme is often not suitable due to the use of very light colors and white backgrounds. "Tiled Fusion" also improves several aspects of the Qt Fusion theme to enhance the contrast, for example for tab bars and scroll bars.

If you prefer Breeze then just switch the style in Tiled preferences to "Native".

I wasn't aware somebody was maintaining a Flatpak of Tiled, btw. I tried it out shortly, though I am bothered by two things regarding this format:
* It installed additional runtimes, taking more than 1.5 GB drive space.
* When I launch the Flatpak version of Tiled, it takes almost two seconds to start, versus less than half a second for the native installed one.

Did you try using the AppImage that I'm providing, or was there some reason to prefer Flatpak?

**Comment by Alexander-Wilms** [comment]
> This is because I wanted to have a default theme that was more suitable for a graphical application like Tiled, where the native theme is often not suitable due to the use of very light colors and white backgrounds.

Ah, good to know.

I already have the runtime installed to run other Qt applications, so the size doesn't bother me. The 2s vs 0.5s are mentioned [here](https://blogs.gnome.org/alexl/2018/01/16/fixing-flatpak-startup-times/), as soon as one updates fontconfig on the host to version 2.13.0, that problem should be gone.

**Comment by bjorn** [comment]
> I already have the runtime installed to run other Qt applications, so the size doesn't bother me. The 2s vs 0.5s are mentioned here, as soon as one updates fontconfig on the host to version 2.13.0, that problem should be gone.

Hmm, while it does mention those timings, it also talks only about _first time startup_. I launched the Flatpak Tiled several times and it always takes almost 2 seconds for me. :-S
