### ISSUE TITLE
[JSON Format] Layers, does it need to be nested?

### ISSUE THREAD

**Issue by bitinn** [bjorn/tiled#1911]
Hi all,

I am wondering whether current decision to nest layers in TMX and JSON export are really necessary. Can it be a flatten array with some properties on each layer to indicate the group it belongs to, and to keep track of indexes? Similar to Tileset and Map's relationship.

Some pros and cons using a flatten array:

PROS

- Cyclic data can be hard to serialize: great serializers use a cache internally ([Json .Net](https://www.newtonsoft.com/json/help/html/PreserveObjectReferences.htm)), decent serializer use depth limit as cut-off ([Unity's JSON Serializer](https://docs.unity3d.com/Manual/script-Serialization.html)), homebrew serializer will probably fail or skip the cyclic reference.
- Flatten array is easier to model than nested data, at least *conceptually*.

CONS

- This require significant rework.
- Can't rely on natural layer order for rendering, need extra indexes to keep track of layer order.
- Break compatibility (though it's hard to tell how many existing libraries actually handle this correctly).

#1038 didn't get into why the nested data structure was chosen, maybe there are advantages of current format that I am not aware of.

**Comment by bjorn** [comment]
I don't understand the relevance of the PROS you're listing.

* Layers are hierarchical, but there are no arbitrary cyclic references, so this point doesn't apply.
* I find it conceptually easier to reason about a data structure when its representation matches its structure. Of course a simple array of layers was easier to model, but I think fitting a hierarchy of layers into an array introduces unnecessary complexity.

> #1038 didn't get into why the nested data structure was chosen, maybe there are advantages of current format that I am not aware of.

I considered avoiding the break in compatibility, but in the end went for a hierarchy because adjustments would have been required anyway since the grouping is not just visual but affects certain properties like locking, visibility and offset. Of course, if you're not using any of those properties in your game then it could have worked without changes.

Maybe I'm missing something and things could actually be simpler while keeping the layers in an array. Without a very good reason I think we shouldn't change it for the current TMX format, but I could keep it in mind for future format.

**Comment by bitinn** [comment]
Thx for the reply, I should have clarified:

By cyclic data, I really meant the data structure (the class/container) I need when I serialize the JSON.

For example, in C# you generally [serialize the JSON string into an object](https://docs.unity3d.com/ScriptReference/JsonUtility.FromJson.html), however, you need to define the class/struct that holds such data.

```
	[Serializable]
	public struct TiledMapLayer {
		public List<int> data;
		public int height;
		public int width;
		public string name;
		public float opacity;
		public string type;
		public bool visible;
		public int x;
		public int y;
		public List<TiledMapLayer> layers;
		public List<TiledProperty> properties;
	}
```

This class gets serializer into trouble, because it doesn't know when to stop (Unity's serializer doesn't support `null` when serializing, which means it will keep serializing until it reaches its depth limit).

But I understand where you are coming from now. Might be there is a better way to serialize JSON in C# that I am not aware of.

**Comment by bitinn** [comment]
OK maybe I just need custom serialization, I should just do:

```
	[Serializable]
	public struct TiledMapLayer {
		public List<int> data;
		public int height;
		public int width;
		public string name;
		public float opacity;
		public string type;
		public bool visible;
		public int x;
		public int y;
		public List<object> layers;
		public List<TiledProperty> properties;
	}
```

Then try to iterate layers that myself. I will look into this approach.

**Comment by bjorn** [comment]
At least with the changes made in #1868 things should be a little easier in Unity, but I see that @saeedakhter doesn't seem to be supporting the layer hierarchy yet in [his code](https://github.com/saeedakhter/TiledJsonUnity3d). I'm rather surprised by the limitations of this serializer, especially recursive data structures aren't so rare...

Thanks in any case for the clarification and I'm interested to hear about your solution once you've got it!

**Comment by bitinn** [comment]
@bjorn yeah that's why I asked about the daily build in that issue :)

The *solution* is basically don't let Unity serializer iterate down the field, by doing this:

```
	[Serializable]
	public struct TiledMapLayer {
		public List<object> layers;
	}
```

I will get a list of objects which I will manually cast to TiledMapLayer, and manually iterate down the chain until I have reached a `null` layers.
