### ISSUE TITLE
Tile properties are stored in <tile/> rather than <tile><objectgroup/></tile> since 1.1.0

### ISSUE THREAD

**Issue by grauw** [bjorn/tiled#1912]
Hi,

I upgraded from Tiled 1.0.3 to 1.1.3 recently, and I noticed that in the tile set editor, I could no longer see or edit the name and a few custom properties I had set on the tiles in my tile set.

Previously, the property editor showed amongst others a name field, and when saving to tmx an `<objectgroup name="...">` object would be created under its `<tile>` object, and the custom properties would be placed inside it.

As of Tiled 1.1.0, the property editor shows different default fields (without name), and custom properties are placed directly in the `<tile>` tag.

Now I could adjust my scripts and manually adjust my existing properties in the tmx file (using a custom property for name), but before I do that, is this a regression or an intentional change? I didn’t see this backwards incompatible change mentioned in the [1.1.0 release notes](https://github.com/bjorn/tiled/releases/tag/v1.1.0)…

(Note that I’m not expressing a preference, I don’t mind it either way. The new location even makes a little more sense perhaps. I was just puzzled where my settings went.)

**Comment by bjorn** [comment]
When you have the Tile Collision Editor open, then the Properties view used to display the properties of the implicit object group created for the selected tile in Tiled 1.0, rather than the properties of the tile itself. This caused much confusion, so in Tiled 1.1 I opted to never show the properties of this object group. Indeed a mention of this in the changelog would have been appropriate.

Would it help to automatically move any custom properties set on the object group to the tile? It could also create a custom name property when the object group was given one. If this sounds like a good idea I could patch that into Tiled 1.1.4.

**Comment by grauw** [comment]
For me it is not necessary, I can migrate my data manually now that I know it was an intentional change. But if you’re asking my opinion, yes for the sake of others who may be surprised by this (it puzzled me for quite a while) I do think it may be good to automatically migrate old properties. Also it’s a good excuse to mention the change in the changelog :).
