### ISSUE TITLE
Object type not being exported with JSON/JS

### ISSUE THREAD

**Issue by zenith-jacob** [bjorn/tiled#1919]
![image](https://user-images.githubusercontent.com/33549831/37983604-3257e774-31f4-11e8-9bb6-1c116bb57f84.png)

Create a TileSet with some objects.
Set a type to each object, ex. TYPE1, TYPE123
Create some objects on a TileMap
Export as JSON/JS:
![image](https://user-images.githubusercontent.com/33549831/37983612-3caa8704-31f4-11e8-8cac-508b898c6854.png)

Export as LUA (working, visible mappings):

![image](https://user-images.githubusercontent.com/33549831/37983625-431bc8aa-31f4-11e8-8819-87c7cb6ff0cc.png)

**Comment by bjorn** [comment]
Note that the type is displayed in gray when the object is selected, because it is inherited from the tile. If you change it, it would be displayed in black and it would _override_ the type set on the tile (changes to the type on the tile would no longer affect that object).

The JSON format is read/write, not just export, and writing out the type property would tell Tiled that this property was _overridden_, which is generally not what we want. The Lua format is different because it is an export-only format (though, you have showing a snippet of exported _tiles_ in the Lua format, and a snippet of exported _objects_ in the JSON format, so the comparison is not fair: in the JSON format, you'll find the type stored on the tiles as well).

That said, I realize it would be useful for many if the type was resolved when exporting the map. This is planned to be introduced as an export option and is covered by issue #1850.

**Comment by bjorn** [comment]
In Tiled 1.2, an option was added to resolve types (and properties) when exporting.
