### ISSUE TITLE
Using moveTilesetView to move tileset tabs around causes crash when closing tiled

### ISSUE THREAD

**Issue by kralle333** [bjorn/tiled#1934]
**Steps to show this:**
1. Open a map that uses multiple tilesets
2. Use moveTilesetView(0, 1) to move the left most tileset tab one to the right
3. Closing Tiled now causes a crash

**Thoughts:**
When tabs are moved around, onTabMoved is called, which also changes the indicies of mTilesets and mDocuments. This causes a crash when closing Tiled as the wrong indicies are now attempted to be removed/deleted. Commenting out  mTilesets.move(from, to) and mTilesetDocuments.move(from, to) seems to fix this bug, however I do not no the implications of doing so.

**Comment by bjorn** [comment]
I don't understand your step to "Use moveTilesetView(0, 1) to move the left most tileset tab one to the right". One can only perform such a step by modifying Tiled source code? What are you trying to do?

**Comment by kralle333** [comment]
Hi bjorn,

I would like to sort the tileset tabs, the example was just to show that moving one tab is enough to cause the crash. Isn't it also important that using the method will not cause Tiled to crash?

**Comment by bjorn** [comment]
> I would like to sort the tileset tabs, the example was just to show that moving one tab is enough to cause the crash. Isn't it also important that using the method will not cause Tiled to crash?

Right, but you can't just call any method and expect nothing to crash, especially private methods. This particular method is normally only used in response to changes in the `TilesetDocumentsFilterModel`, in order to maintain consistency between the model and the tileset views in the `TilesetDock`. If you start calling that method in any other case, you're creating an inconsistency where I'm not entirely surprised it's causing problems somewhere (like in `onTilesetRowsAboutToBeRemoved` as seen in your backtrace).

About sorting the tileset tabs, their order is based on the order of the tilesets in the `TilesetDocumentsFilterModel`, which sorts the tilesets by name. If you want to change the order manually, you'll probably want to disable sorting by removing the `sort(0)` call in its constructor and then implementing reordering in the `TilesetDocumentsModel`. Alternatively, you could try to change the `TilesetDock` to ignore the order of the tilesets in the model. What is your goal?

**Comment by bjorn** [comment]
Closing since it's an old issue that does not represent a problem with Tiled.
