### ISSUE TITLE
Website should enforce HTTPS

### ISSUE THREAD

**Issue by rogersachan** [bjorn/tiled#1935]
Since the site is hosted with Github Pages, wouldn't this be an easy change? I'm able to navigate to https://www.mapeditor.org/ already.

**Comment by bjorn** [comment]
Hmm, I wonder since when that works without warning. It used to only work for `.github.io` subdomains, since that is what the SSL certificate applied to. And this would generally cause browsers to issue a warning when used on a custom domain. I see now the certificate used is signed for www.mapeditor.org by Let's Encrypt. Do you know since when they're doing this?

In any case, I've now checked the "Enforce HTTPS" box, which seems to do the trick. :-)

**Comment by bjorn** [comment]
Btw, while it's good that it works for the site, I think it's more important to enable HTTPS for the forum at http://discourse.mapeditor.org, since it has authentication. They have [recently made this possible](https://blog.discourse.org/2018/04/https-by-default/), but there are probably some steps I need to take for the transition.

**Comment by bjorn** [comment]
Thanks to the Discourse team, https://discourse.mapeditor.org now also works and will soon be forced to HTTPS as well. I've adjusted all social login callbacks to use HTTPS.

**Comment by bjorn** [comment]
As of yesterday, the support for HTTPS on custom domains for GitHub Pages [is official](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). :-)
