### ISSUE TITLE
Terrain brush question in isometric-staggered

### ISSUE THREAD

**Issue by chenpangzi** [bjorn/tiled#1951]
I use examples isometric_grass_and_water.tmx, the terrain brush work good,
but when i change orientation to staggered, the brush is working wrong!
see this image, missing 2 tiled.
![tiledmap](https://user-images.githubusercontent.com/11433041/39984695-946996c8-578e-11e8-8e3c-6fbcd827ad71.png)

**Comment by bjorn** [comment]
First off, please decide where to post your question, be it [on the forum](https://discourse.mapeditor.org/t/terrain-brush-question-in-isometric-staggered/3205) or as a GitHub issue, rather than posting it in both places.

In any case, I believe this was working correctly at some point, but it evidently is broken now. I'll need to investigate what is going wrong here. Thanks for the report!

**Comment by bjorn** [comment]
Well, I broke this in change 01944e953aa2292bead56505130c656f201930d2, which makes an assumption about neighbor proximity that is not valid for staggered maps. I think expanding the maximum area processed by one tile will fix this up.
