### ISSUE TITLE
Blank <tile/> field in xml?

### ISSUE THREAD

**Issue by bsabiston** [bjorn/tiled#1963]
Hello I updated Tiled after years of using an old version.  My code importer crashed because the new files I save include blank tile fields.  What are these?  In the old .tmx files a tile field always had a "gid" tag, like this:
`<tile gid="6"/>`

Thanks
Bob

**Comment by bjorn** [comment]
Previous versions of Tiled used to write out the following for empty tiles (when using the deprecated "XML" format):
```xml
<tile gid="0"/>
```
But since Tiled 1.1, this has been simplified to:
```xml
<tile/>
```
Just to reduce file size a little bit (see issue #1716).

Since this was such a small change and the XML format is actually deprecated (it just wastes space for no benefit), I did not consider this important enough to mention in the [TMX changelog](http://doc.mapeditor.org/en/stable/reference/tmx-changelog/). I'm sorry to hear it caused your map loader to crash.

**Comment by bsabiston** [comment]
Thanks -- It is no big deal, I am adding to the software anyway.  I just wasn't sure what the blank tile fields indicated.
