### ISSUE TITLE
Crash with Ctrl+Z

### ISSUE THREAD

**Issue by elronsmith** [bjorn/tiled#1965]
Open tileset editor, select rectangle, click, move and dont push up press ctrl-z

![2018-06-24_20-47-42 1](https://user-images.githubusercontent.com/531764/42113114-733a2906-7bea-11e8-9eca-6cb2d5a3a4f5.png)

**Comment by bjorn** [comment]
Which version of Tiled are you using, and could you be a little more verbose on the steps to reproduce? I don't know what you mean with "select rectangle" or "don't push up". Ctrl+Z undoes a change, but which change did you actually make?

**Comment by elronsmith** [comment]
1.1.5 @bjorn 
Here is a video [https://yadi.sk/i/tb-qPEva3YLv4W](https://yadi.sk/i/tb-qPEva3YLv4W)

**Comment by bjorn** [comment]
I'm having trouble reproducing the crash even when trying to follow the operations shown in the video. Can you please tell me each step you're doing?

Also, could you please try if this issue is maybe already fixed in the latest development snapshot? You can find the snapshots among the downloads at https://thorbjorn.itch.io/tiled.

**Comment by elronsmith** [comment]
Snapshot 2018.06.27 crashed, [download new video](https://yadi.sk/i/S4ifzeBJ3Ybvqu)
I open tiled collision editor, added rectangle, clicked to Select Objects(S), edited borders 2 times, made mouseDown(), pressed ctrl+z, tiled crashed, made mouseUp().

**Comment by bjorn** [comment]
@elronsmith Thanks! I was able to reproduce it now. I did not understand previously that you were holding the mouse button down while doing the undo. Doing this, I could also reproduce the crash. I'll try to get this fixed soon.
