### ISSUE TITLE
Z order with layer

### ISSUE THREAD

**Issue by fs6tavu** [bjorn/tiled#1968]
I am building an isometric map with different layers: ground and walls.

This is the map with all the tiles I want but without those layers: 

![without_layers](https://user-images.githubusercontent.com/531764/42093890-4000adb2-7bae-11e8-909e-ecc797247e46.png)

When i put the walls blocks on a layer block I get this: 

![without_layers 1](https://user-images.githubusercontent.com/531764/42093904-46cb255a-7bae-11e8-9156-09a887cab1df.png)

The correction is very simple but i don't know where is it on the code.

In my game i display the tiles like this: 

```
for (int y = 0; y < map.Height; y++) 
    for (int x = 0; x < map.Width; x++) 
        foreach (TmxLayer layer in map.Layers)
            //DISPLAY TILE
```

And i get a map like in the first screen (what I want).

If I change like this:

```
foreach (TmxLayer layer in map.Layers)
    for (int y = 0; y < map.Height; y++) 
        for (int x = 0; x < map.Width; x++) 
            //DISPLAY TILE
```

I get the same problem like in tiled, the z-order isn't correct.

If you wont change the z order priority like i do in my game, can you at least explain where i can do it myself in order to easily create my world if it is possible?

Thank you for all your work.

**Comment by bjorn** [comment]
You could definitely write some code that iterates the layers like that, though it won't be completely trivial because the different layers are currently represented by different `TileLayerItem` instances, which render one after the other.

Probably the place to modify would be the relatively new `MapItem` class, where you could implement a rendering function that works the way you want (based on the single-layer rendering code you can find in `IsometricRenderer`), and then you would not instantiate `TileLayerItem`s at all. One problem is that tile layers would no longer interleave with other layer types, but that probably doesn't affect your project.

See issue #1274 for a discussion about adding this feature to Tiled in general.

**Comment by fs6tavu** [comment]
Thanks for your answer !
I will try that when I will have some time :)

**Comment by bjorn** [comment]
@fs6tavu No problem! Feel free to ask additional questions when they come up. I'll close this issue since we already had #1274 about this feature.
