### ISSUE TITLE
Object Types workflow is tedious

### ISSUE THREAD

**Issue by s-m-k** [bjorn/tiled#1987]
It seems that each time I change or add the type in Object Types I need to export it to a file and my co-developers have to import it.

Wouldn't it be better if we could just tell Tiled to use a particular file instead of a place somewhere in the user settings? The way it works now (being stored in user settings) doesn't make sense to me, since object types are, by the very definition, tied to the game project (i.e. they need to be handled by the version control system), not to the development environment.

Optimally, you could indicate the path to object types in the level file, that would allow people to edit levels for different projects at the same time.

Also, I don't think that the templates can be a good replacement for object types in my case. I find them kind of complementary: object types define default values for all properties (which are also read by my engine), templates are pre-configured instances/examples (there can be a few templates of a single object type). That way I can add new default values for all templates of a type at once without relying on hardcoding them inside the game code.

Also, colors! :)

**Comment by bjorn** [comment]
> Wouldn't it be better if we could just tell Tiled to use a particular file instead of a place somewhere in the user settings?

Actually, Tiled uses a particular file and it just happens to be in the user settings _by default_. But you can tell Tiled to use a file anywhere, including a file in your project. You do this in the Object Types Editor by selecting _File > Choose Object Types File..._ instead of the Import/Export actions.

The only thing stored in the preferences is the location of your object types file.

> Optimally, you could indicate the path to object types in the level file, that would allow people to edit levels for different projects at the same time.

While that is true, usually the object types are shared between all levels in a game. I'd like to add support for projects to Tiled, in which the object types will move into the project (or at least the path to the types file would). Project support is on the roadmap for Tiled 1.3.

> Also, I don't think that the templates can be a good replacement for object types in my case. I find them kind of complementary: object types define default values for all properties (which are also read by my engine), templates are pre-configured instances/examples (there can be a few templates of a single object type). That way I can add new default values for all templates of a type at once without relying on hardcoding them inside the game code.
> 
> Also, colors! :)

You're right, templates definitely don't quite replace object types, and actually work alongside. That said, I'm not entirely happy with the current setup, which mostly grew like this dynamically as features were added. I think it would be worth redoing both systems at some point to replace it with something simpler and more unified.

Mostly I'd like to better support entity-component systems that are popular since a while already. I think the current system with the different kinds of objects, object type definitions and templates feels complicated and in some cases limiting, though its features do cover most use-cases.

**Comment by s-m-k** [comment]
>Actually, Tiled uses a particular file and it just happens to be in the user settings by default. But you can tell Tiled to use a file anywhere, including a file in your project. You do this in the Object Types Editor by selecting File > Choose Object Types File... instead of the Import/Export actions.

Thanks for the tip. The only downside is that it still requires proper setup on all seats, but it will do as a temporary solution.

>While that is true, usually the object types are shared between all levels in a game. I'd like to add support for projects to Tiled, in which the object types will move into the project (or at least the path to the types file would). Project support is on the roadmap for Tiled 1.3.

Funnily enough, my initial though was "this program needs proper project support", but since it appeared to be way more work, I decided to propose storing the information in the level file instead. That said, I'm glad that the project support is planned to be implemented!

**Comment by bjorn** [comment]
Closing this since support for projects was added with [Tiled 1.4](https://www.mapeditor.org/2020/06/20/tiled-1-4-0-released.html). The reference to the object types file has been moved to the project properties. Hopefully the workflow is less tedious now. :-)
