### ISSUE TITLE
Loading tileset from image with spacing causes loss of last column

### ISSUE THREAD

**Issue by Noofbiz** [bjorn/tiled#1989]
Hello

I'm using Tiled map editor on macOS, and if I try to create a new tileset from an image, and the image has spacing between the tiles, sometimes (not every sprite sheet I used did this!) I got a tileset without any sprites on the right-most column of my sprite sheet. One sheet where that happens is here https://kenney.nl/assets/roguelike-indoors

Thanks!

**Comment by bjorn** [comment]
That's because the riles in the right-most column are missing one pixel (they are 15x16 whereas all the other tiles are 16x16). Tiled does not include incomplete tiles in the tileset.

If you zoom in on the tileset you can clearly see that actually there was meant to be one more pixel there, since as it is the outline is missing on the back of the piano for example. I think you should contact the author of the tileset about this.

**Comment by Noofbiz** [comment]
Thank you for the quick response! I'll let the tileset author know!
