### ISSUE TITLE
Text with default font size not initialized properly

### ISSUE THREAD

**Issue by IoriBranford** [bjorn/tiled#1994]
1. Create map with text object
1. Set font pixel size to 16, [the default](http://docs.mapeditor.org/en/stable/reference/tmx-map-format/?highlight=pixelsize#text)
  ![image](https://user-images.githubusercontent.com/7191895/44368665-7168c800-a488-11e8-98df-a9d603ff1352.png)
1. Copy and paste the text object

The new text's font size is not set properly.
![image](https://user-images.githubusercontent.com/7191895/44368621-43838380-a488-11e8-8570-9bfe2d51051d.png)
In the map file, the text object data is correct (include pixel size only if not 16).

The same happens to all size 16 text if you save, close and reopen the map.

**Comment by bjorn** [comment]
Thanks for the report! Turns out the pixel size ended up being not set at all when you had a text object with a non-default font family but the default pixel size.

I'm not sure if there will still be a Tiled 1.1.7, but at least the fix will be included in Tiled 1.2 Beta (the development snapshot which I'll release today).
