### ISSUE TITLE
BUG: Tilesets (even embeded ones) are being added to other maps!

### ISSUE THREAD

**Issue by phanxgames** [bjorn/tiled#2002]
I'm not entirely sure what this issue is, or if it has been fixed. But I have experienced it on version 1.1.4

Basically if I am editing Map_A with an external Tileset_A, and then open Map_B external Tileset_A will be in the tilesets window of Map_B, even though Map_B wasn't suppose to use Tileset_A.
It seems to be based on whatever is in my brush, if my Brush was still on Tileset_A, then it will be moved over into Map_B. But it may occur outside of this as well.
Keep in mind, I am opening up Map_B using the commandline, and not through the GUI.

What makes matters worse is that if I were to save Map_B, it will also add Tileset_A to its .tmx file, even though I never used it to map with.

Thanks!

**Comment by bjorn** [comment]
> Basically if I am editing Map_A with an external Tileset_A, and then open Map_B external Tileset_A will be in the tilesets window of Map_B, even though Map_B wasn't suppose to use Tileset_A.

Since Tiled 1.1, tilesets are added to the map automatically when you first use them on a map, and all loaded external tilesets are available on all maps. This was mainly done for convenience, though I understand it makes it harder to make sure you're not using a particular tileset.

> What makes matters worse is that if I were to save Map_B, it will also add Tileset_A to its .tmx file, even though I never used it to map with.

This should really only happen when you have actually used the tileset, though at the moment tilesets are not automatically removed from a map when they are no longer used. So when you accidentally placed a tile from a tileset you didn't intend to use, and then erase that tile again, the tileset is still part of the map. You can remove the tileset from the current map by clicking the small button for this below the tileset view.

I wanted to get rid of the manual management of the tilesets referred to by each map and the order in which they do so, because I considered this a tedious and unnecessary process. Instead, especially once Tiled supports projects, I thought it would be much nicer if the Tilesets view simply provides access to all tilesets in your project so you can use them on your maps at will. But maybe I'm wrong?

**Comment by phanxgames** [comment]
This feature "and all loaded external tilesets are available on all maps" is what I'm reporting. I do not like this functionality. And it breaks things for my workflow.  Could you please add a config option to disable. 

Thank you.

**Comment by phanxgames** [comment]
I wanted to update this slightly with an example of where this became an issue:
Background:
- We use Tiled to create tilesets. But using Raw sprite sheets, we create a map that is the size of our desired tileset, and we bring several Raw images together to create a single tileset to be used in our game.
- We can save the Tilesets as .tmx to allow us to easily modify the tilesets in the future, like a PSD in photoshop.
- We then export the Tilesets once completed as PNG. Love that feature.
- We then use these exported PNGs on our actual game maps.

What actually happened that was the issue:
- I was editing a Map as usual, love Tiled. I been using it since it was made in Java. You even been to my stream, you know how much I am a fan of your work.
- I needed to edit a tileset, because I needed to add an additional tile that I realized we were missing.
- I open up the tileset's .tmx to export as png.
- I then went back to my map I was editing: and got a path error correction dialog at the top of the map. 
- I believe I ignored the error.
- Found my new tile in my newly created tileset, added my additions, saved the map.
- Then found out that the RAW image from the tileset process was then saved to my map!
- But I didn't realize it was an issue until I imported it into my game.
- I did NOT use the RAW image on the map, its a completely different layout.

In conclusion:
- I use Tiled for "two projects" as once. You could consider it. The tileset project and the mapping project.
- Even still, adding the functionality of having tilesets get automatically imported into Maps would be undesirable, and is the control I do want. 
- This is how its worked all these years, and this recent change is breaking.
- We have ran into this issue in the last weeks without realizing what was going on, simply saying "Wow Tiled sure is more buggy lately."
- This idea just simply doesn't work well if you are working on several maps at once that you don't want the same Tilesets to be shared. 
- I don't believe its correct to assume that just because I am opening up several .tmx files at once they are connected in any way. Photoshop for example doesn't do this.

Ideas for solution:
- Can we have multiple "projects" open at once? Opening the maps from the commandline launches these maps in the same application.
- Can you have this feature be optional? Even if its something I can edit in a config file deep in the installation directory once. I would never want this feature.
- I can always just use Tiled version 1.0 since you say 1.1 is when you added this.

**Comment by phanxgames** [comment]
Just wanted to add:
I tested this with having just one image path incorrect and only one embeded tileset in the first map. And the error was reproducable.

**Comment by bjorn** [comment]
I really appreciate your feedback, @phanxgames! Unfortunately I think it's too late to reconsider the general behavior for Tiled 1.2, though of course I will try to reproduce the bug and see if I can fix it.

What I'm unclear about in the steps to reproduce is what change you are making in this step: "Now I open a second map, any map really. Make a small change. Save it.". If the small change means using the current tile stamp on that map, then indeed that will necessarily add the tileset referenced by your tile stamp to the map. But if it's a change that has nothing to do with that tileset, then there must be a bug.

Also, does this bug really only reproduce by starting with a tileset that has a broken image path? Cause that would at least limit exposure to the bug considerably.

> Would perhaps downgrading to version 1.0 solve this issue for us? If so, I will give it a try and let you know if the issue occurs even on that version.

Downgrading to Tiled 1.0 should definitely resolve this issue for you. Of course, I will do my best, probably for Tiled 1.3, to get to a workflow that suits you as well. I hope we can keep the automatic adding of tilesets, since it is also simply convenient to capture a brush on one map and use it on another, without first needing to make sure they both reference the needed tileset(s) (in Tiled 1.0, you could do this only using copy/paste, and paste would add those tilesets). But I can definitely see the downsides. Maybe it would help to also automatically remove tileset references (though that's problematic for embedded tilesets, due to possible loss of information), or to provide some way to pin certain tilesets for quickly accessing them. Or some toggle button in the Tilesets view to switch between "all loaded tilesets / tilesets in project" and "tilesets used by current map".

**Comment by bjorn** [comment]
I tried to reproduce the issue without success. Tried to carefully follow the steps twice but no tileset was getting added to the other map. I think we're missing something, so we need to make the steps more concrete. Can you provide an archive with the two map files that are involved? You can upload ZIP files here by dragging them into your comment.

**Comment by phanxgames** [comment]
I recreated the bug with the most simplest example of files following the steps.
Perhaps my steps aren't as clear as they should be.

But here are the files attached:
[tiled bug.zip](https://github.com/bjorn/tiled/files/2372226/tiled.bug.zip)

Steps:
- Open mapA.tmx
- Fix only the first embedded tileset error.
- Draw one additional tile to the map (from tileset1, also called tilesetA, its green)
- Save mapA.tmx and close it
- Open mapB.tmx in the same Tiled instance.
- Select a tile from the existing tileset from mapB (tileset2, its orange)
- Draw one tile to the map from that tileset
- Save mapB.tmx
- You will notice tileset1 (tilesetA titled) the green one is now embedded to mapB.tmx even tho I never used it on this map. (this the error)
- mapB.tmx was only supposed to have tilesetB (or tileset2)

**Comment by phanxgames** [comment]
Let me know if you want me to like record it or something.

**Comment by bjorn** [comment]
> I have tested it with Tiled version 1.1.4 and 1.1.6

It's late now so I'll try your latest instructions again tomorrow, but in the meantime, I realized you've only tested it with the current stable version of Tiled, whereas I have so far been trying to reproduce it with the latest development version. Could you please try if the issue still happens for you with the latest snapshot? It's version 2018.08.22 at https://thorbjorn.itch.io/tiled.

**Comment by bjorn** [comment]
@phanxgames With those instructions I could reproduce it, even in the latest development version. I'll have a look at what's going on!

**Comment by bjorn** [comment]
Alright, I found a problem in that previously selected stamps could end up affecting the list of tilesets scheduled to be added during painting, which was caused by the list not getting cleared when it should. I think that should resolve this problem, at least in this particular case.

The only way to get tilesets added should be to actually use those tilesets. So in the steps to reproduce, if you do not select an orange tile but paint with the still selected green tile, then the green tileset will still get added to the second map.

That should at least improve the behavior in Tiled 1.2. For Tiled 1.3 we can look into improving the workflow in general, which I think will come along with support for projects.
