### ISSUE TITLE
Missing Tile Layer Format Options When Making a New Map

### ISSUE THREAD

**Issue by AntumDeluge** [bjorn/tiled#2004]
System: **Windows 10 64-bit**
Tiled: **1.1.6 64-bit (installed via MSI)**

When creating a new map, the options for ***Tile layer format*** listed are ***CSV***, <I><b>Base64 (uncompressed)</i></b>, & <i><b>Base64 (zlib compressed)</i></b>. But for existing maps there are two additional options: ***XML*** & <i><b>Base64 (gzip compressed)</i></b>. Not sure if this is intentional, but why not list all supported formats in the ***New Map*** dialog?

*New map:*
![new_map-no_gzip](https://user-images.githubusercontent.com/3631473/45133265-25d14200-b149-11e8-8322-3aaf32d6d5fd.png)

*Existing map:*
![existing_map-gzip](https://user-images.githubusercontent.com/3631473/45133270-2bc72300-b149-11e8-9c50-a2cad405543b.png)

**Comment by bjorn** [comment]
The reason is that the "gzip" format is considered deprecated, since the "zlib" format is always better to use in this scenario. But for backwards compatibility, the "gzip" format is still supported.

As [Mark Adler himself wrote](https://stackoverflow.com/questions/20762094/how-are-zlib-gzip-and-zip-related-what-do-they-have-in-common-and-how-are-they/20765054#20765054):

> The main difference between zlib and gzip wrapping is that the zlib wrapping is more compact, six bytes vs. a minimum of 18 bytes for gzip, and the integrity check, Adler-32, runs faster than the CRC-32 that gzip uses.

Similarly, the XML format is also deprecated since it is very inefficient. If you need human-readable data it is likely always preferable to choose CSV for the layer data instead of XML. But again, purely for compatibility reasons it is still supported.

Do you personally have a use for either the gzip or XML layer data formats?

**Comment by AntumDeluge** [comment]
The reason I ask is because the [project that I am a part of](https://stendhalgame.org/) uses maps with gzip compression. I'm not sure at this point if our software supports zlib compressed maps as all the ones I have looked at are gzip compressed. I suppose I will have to test it.

I was helping another member create a new map, & they were confused at my instructions because they couldn't find the "gzip" option. After messing around with it, I discovered that after the map is created it could be changed. So I just thought it was strange that gzip compression is supported but not listed when creating a new map.

It just seems a bit trivial to me to not list it in the new map options when it is supported. Not a big deal though.

Thank you for responding promptly. :)

**Comment by bjorn** [comment]
> The reason I ask is because the project that I am a part of uses maps with gzip compression. I'm not sure at this point if our software supports zlib compressed maps as all the ones I have looked at are gzip compressed. I suppose I will have to test it.

Stendhal is such an old project, they started using the Java version of Tiled long before I rewrote it based on Qt. And Tiled Java never supported "zlib" compression, which is mostly because of an oversight since it's actually very easy to support.

I've added support for "zlib" compression to `libtiled-java` in commit 3371ebd4e31ea11d1e741099b2b8e53acd418978, and I expect any necessary change on your side to be similarly small.

I'll close this issue, since I would prefer not to bring those options back in the New Map dialog. Of course it would be trivial to have them, but the additional choices have been removed there because they do not add value, and would be only a source of confusion (like choosing between zlib or gzip) or frustration (like getting huge files that are slow to load with the seemingly sensible "XML" option).

**Comment by bjorn** [comment]
It's nice to hear Stendhal is still being worked on, btw! From 2004-2009 I worked on a similar project which was called The Mana World. It was the main driver for Tiled's development for quite a while. Right now I just don't have time for more projects, but I still hope to return to work on such a game again in the future.
