### ISSUE TITLE
Can't create Tileset from TGA file

### ISSUE THREAD

**Issue by rajivmg** [bjorn/tiled#2013]
I'm using Tiled version 1.2.0 x64(downloaded from itch.io) on Windows 10. When trying to create a new tileset following error message is shown:
_Error: Failed to load tileset  image 'Y:/xyz/area1.tga'_
PNG format works fine.

**Comment by bjorn** [comment]
Hmm, that's strange. I do ship the TGA plugin with the Windows installer. Can you check whether you have the `plugins\imageformats\qtga.dll` file in your installation folder?

**Comment by rajivmg** [comment]
Yes `qtga.dll` is there.

**Comment by rajivmg** [comment]
Also the image is RGBA.

**Comment by bjorn** [comment]
Hmm, can you upload the TGA? Did it work with older versions of Tiled?

**Comment by rajivmg** [comment]
I have to zip the TGA file to upload it here. It wasn't working in the previous version. I think the version number was 1.0.x .
[Tileset.zip](https://github.com/bjorn/tiled/files/2440618/Tileset.zip)

**Comment by rajivmg** [comment]
So today when I exported a PNG file as TGA using Gimp, it worked!  Problem arise only when I'm exporting TGA using Aseprite.

**Comment by bjorn** [comment]
I'm getting the same error when trying to use your uploaded TGA image on Linux. After digging a little further, I found that the Qt TGA handler [does not support compression](https://code.woboq.org/qt5/qtimageformats/src/plugins/imageformats/tga/qtgafile.h.html#151). If I export an image as TGA from GIMP, it will not load in Tiled when I enable the "RLE compression" checkbox.

I'm sure getting the Qt TGA image format plugin to support RLE compression could be fun little side project. :-)

**Comment by bjorn** [comment]
> The image I uploaded is not RLE compressed. It is strange that uncompressed Aseprite TGA export doesn't load, there might be bug in Qt TGA.

Hmm, then there must be some other unsupported feature. The Qt TGA support is very basic.

**Comment by ijacquez** [comment]
The image isn't compressed (byte 2 in the header), and is true color (RGBA).

Wild guess, but there's a weird quirk with TGA files where you can specify the origin. That is, byte 17 in the header determines where the origin is:
```#define TGA_IMAGE_ORIGIN_BOTTOM 0x00
#define TGA_IMAGE_ORIGIN_TOP    0x20
#define TGA_IMAGE_ORIGIN_LEFT   0x00
#define TGA_IMAGE_ORIGIN_RIGHT  0x10
#define TGA_IMAGE_ORIGIN_MASK   0x30
```

The file attached looks to be top-left.

Did you export with the origin changed?

**Comment by bjorn** [comment]
So @rajivmg found the issue, which was that the TGA files written by Aseprite were lacking the TGA v2.0 footer, causing Qt to [raise an error](https://code.woboq.org/qt5/qtimageformats/src/plugins/imageformats/tga/qtgafile.cpp.html#186) while trying to load the image.

@ijacquez Actually Qt TGA does at least support [having the origin at the top or bottom](https://code.woboq.org/qt5/qtimageformats/src/plugins/imageformats/tga/qtgafile.cpp.html#239). It doesn't support having it on the right, but a comment in the code says nobody does this, heh.

Since there's nothing that remains to do on Tiled I'm closing this issue. Thanks for your efforts!
