### ISSUE TITLE
JSON export saves incorrect tile data

### ISSUE THREAD

**Issue by yyyc514** [bjorn/tiled#2016]
The JSON includes some VERY large integers that I do not see in other export options (such as CSV). Just upgrading to v1.2 and this issue is still present.

<img width="905" alt="screen shot 2018-10-03 at 10 16 44 pm" src="https://user-images.githubusercontent.com/6473/46449449-1bab5f00-c75a-11e8-856b-ee449722de01.png">

![screen shot 2018-10-03 at 10 16 54 pm](https://user-images.githubusercontent.com/6473/46449450-1bab5f00-c75a-11e8-9910-cca1425eec45.png)

Thoughts?

**Comment by yyyc514** [comment]
Lua export seems to have same large int.  To me the CSV export is the "correct" one.

**Comment by EJlol** [comment]
These problably are rotated and/or flipped tiles.

See also:
http://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile-flipping

**Comment by yyyc514** [comment]
Yep.  Makes sense.  Closing issue.

**Comment by bjorn** [comment]
Right, the CSV plugin currently ignores the flipped state because I wasn't sure it made sense to support it for that format.

**Comment by yyyc514** [comment]
How do you see the CSV format being different than the others (in that it shouldn't get the flip bit)?

**Comment by bjorn** [comment]
> How do you see the CSV format being different than the others (in that it shouldn't get the flip bit)?

The original use-case for the CSV format was to allow export to Excel, and I thought having big numbers for flipped states would not be useful there. It also didn't work "automatically" since the inclusion of the flipped states is currently implemented in the `GidMapper` class, which is meant for working with multiple tilesets (something the CSV format also doesn't support). Lastly the CSV plugin supports specifying names for tiles, which are then used instead of the tile ID, and you can't add bit flags there.

But of course, in case no names are used there could be somebody who wants to read out flipped tiles from a CSV file. So far I have not heard about anybody missing that. If it should be added, it could take on a different form than by setting bitflags though (maybe appending `-`, `|` or `\` to the numbers/names?).

**Comment by yyyc514** [comment]
- gets you one flag easily enough and it'd work with JSON too I imagine.  Of course you could always just turn the numbers in JSON to strings and then whatever craziness you came up with would work - but you'd probably have to make it a different type of JSON so as not to break the existing formats.
