### ISSUE TITLE
JSON export changed between versions

### ISSUE THREAD

**Issue by Weedshaker** [bjorn/tiled#2058]
Hi,

why do we have different .json exports at version 1.1.7 and newest release?

![screenshot 2019-01-05 12-20-51](https://user-images.githubusercontent.com/10768924/51309016-c57dd580-1a43-11e9-86f0-92df2706eeb4.png)

And how can we still export the old way with a new version of tiled?

_PS: Our Designer does support you through Patreon..._

**Comment by Weedshaker** [comment]
Phaser 2/CE has had pixi.js as its rendering engine. Phaser, never really optimized the rendering of tiles. Thanks to @englercj, a pixi developer, has solved this problem with phaser-tiled, which makes Phaser 2/CE run large tilemaps with good performance. (basically it just doesn't render tiles which are out of bound/camera)

Phaser 3, just kinda got production ready and it now has its own rendering engine and uses matter.js, but this kinda makes it nearly impossible to migrate, especially far progressed projects, like ours. I don't know any numbers of how many people use the combination of Phaser2/CE with phaser-tiled. But according to the newsletter @Phaser, still the majority of game releases are Phaser2/CE, while the number of Phaser 3 games is growing, though. The export format change of Tiled 1.2, will effect them anyways... with or without phaser-tiled.

In this case, making it possible to still export the old way, would solve all issues, while updating game frameworks to accept the new format, will be more a barrel without a hole.
I assume that I am just part of the first wave of complains... probably a lot of people have relied on the JSON export and possibly a lot haven't yet updated their Tiled, although its already 2 month, but our designer (Leveldesigner), just ran into it now.

**Comment by englercj** [comment]
Hello! I indeed stopped working on [`phaser-tiled`](https://github.com/englercj/phaser-tiled) because it got to a point where it "just worked" for the popular versions of both libraries and I supported the feature set I was interested in having.

Later I made [`gl-tiled`](https://github.com/englercj/gl-tiled) which is a WebGL-only renderer for Tiled maps, but that was based on v1.0. 

Both of these projects are likely not to work with the latest version of Tiled JSON output, but I'm more than happen to merge PRs that fix them up if anyone was interested. I'm not currently working on a project that uses Tiled, but I may in the near future at which point I'd update `gl-tiled`, but not phaser-tiled (I don't use Phaser anymore).

**Comment by bjorn** [comment]
@englercj Thanks for dropping by! I checked out your `gl-tiled` demo and that's some awesome map rendering performance! I hope you'll continue work on it. :-)

@Weedshaker So, I've looked into multiple ways to still support the old format:

* Adding them to the JSON plugin as additional file formats.
* Adding an option to the Preferences to tell Tiled to use the old format.
* Adding another JSON plugin that uses the old format.

In the end I went for the last option, since I think it's the cleanest approach (less confusing the users with choices or options). The new "json1" plugin is disabled by default, so it won't bother those who don't need it. And those that do can disable the "json" plugin when enabling the "json1" plugin, so that the format can still be selected automatically based on the file extension without ambiguity.

I plan to release Tiled 1.2.2 tomorrow, which will include the `json1` plugin.

**Comment by Weedshaker** [comment]
Thank you very much for your effort. This has been super fast! Looking forward to test this on 1.2.2 tomorrow! Greetz

**Comment by bjorn** [comment]
Sorry, the build for macOS on Travis CI was broken and I spent the whole day fixing it, running into one problem after another. Now it's too late to make a release, and tomorrow I need to be back to work, so unless I find enough time in the evenings I may need to postpone the release till Tuesday next week. :/

**Comment by Weedshaker** [comment]
Easy, we all have to struggle at our paying day jobs. Thanks for the info, though and don't even dare to work on this in the evenings. Next Tuesday is more than soon enough!

**Comment by bjorn** [comment]
Hehe, thanks @Weedshaker! Unfortunately it's too late not to work on this in the evenings... Since the last builds have been running fine, I've pushed the `v1.2.2` tag and will test what has been uploaded tomorrow. Maybe I'll find some time to announce it anyway.

**Comment by Weedshaker** [comment]
Yes 1.2.2 works like a charm! THANK YOU!

_Below a little instruction for people who may read this post in the future._
**This is how you enable old style JSON export**:

1) Download Version >= 1.2.2
2) Click Edit/Preferences/Plugins and select libjson1.so
![screenshot_30_01_19__15_47](https://user-images.githubusercontent.com/10768924/51989655-c5e88880-24a7-11e9-96c1-2a500c75a115.png)
3) File/Export as JSON map files [Tiled 1.1]
![screenshot_30_01_19__15_48](https://user-images.githubusercontent.com/10768924/51989692-da2c8580-24a7-11e9-93e9-0095a1829b6f.png)
_(Note: this export option is available, as soon as you select the libjson1.so  plugin)_
