### ISSUE TITLE
After upgrading to version 1.2.1 float numbers were altered strangely

### ISSUE THREAD

**Issue by giliwerner** [bjorn/tiled#2066]
I used to have Tiled version 1.1.5 and recently updated to version 1.2.1, and since every float property I save on the map is being changed in the .tmx file in a strange manner.
For example,
0.2 is changed to 0.20000000000000001
0.4 is changed to 0.40000000000000002
0.35 is changed to 0.34999999999999998

I tried to upgrade to version 1.2.2, but this still occurs.
What is the reason for this change? Seems more like a bug than anything else... 
Can it be fixed?

(I am using a macOS 10.13.6)
Thanks

**Comment by bjorn** [comment]
This seems to be a problem related to Qt 5.6. Tiled 1.1.5 was built against Qt 5.10, but due to other issues (can't remember what anymore) and for backwards compatibility reasons, Tiled 1.1.6 and later are built against Qt 5.6.

The [latest development snapshot](https://thorbjorn.itch.io/tiled/devlog/65879/more-scriptable-development-snapshot) is built against Qt 5.9, which I plan to use for Tiled 1.3 as well. It seems the problem doesn't occur, so please try to use that one instead.

**Comment by giliwerner** [comment]
The latest snapshot 2019.01.30 completely solves the problem, thank you for the quick fix!
