### ISSUE TITLE
Being able to select Tile Objects that are inside a bigger Tile Object

### ISSUE THREAD

**Issue by darencius** [bjorn/tiled#2069]
Just like with shaped objects

![djfksdaf](https://user-images.githubusercontent.com/37813277/52438387-6dedf980-2b19-11e9-842e-b8e1c06030b3.PNG)

You can't currently do that with Tiled Objects, when a smaller Tile Objects is inside (overlapping) a bigger one, you can only select the latter (this only happens when they are _in the same layer_).

This makes it a bit annoying to work with them, I am forced to move all the smaller TileObjects to a separate layer.

**Comment by bjorn** [comment]
This works with shape objects because by default the objects are ordered by their Y coordinate, and shapes have their origin in the top-left. So in your screenshot, the bigger object sits below the smaller objects. Tile objects have their origin in the bottom-left, so in that case the Y coordinate of the bigger object is lower and as such it would sit on top.

There is no easy fix for that, but there are two ways to select objects that are below other objects:

* Hold Alt while left-clicking a selected object, and Tiled will select an object directly below that object, if there is one. You can repeat this action to even select objects that are below multiple other objects.

* Hold Alt while right-clicking, and an alternative context menu pops up, allowing you to select any of the objects at the clicked location.

These actions are documented in the manual at [Selecting and Deselecting](http://doc.mapeditor.org/en/stable/manual/objects/#selecting-and-deselecting).
