### ISSUE TITLE
Documentation for .world file is incorrect

### ISSUE THREAD

**Issue by RainingChain** [bjorn/tiled#2077]
In WorldManager::privateLoadWorld(), you expect each map in the JSON to have a "width" and "height" value. However, in the documentation, /tiled/docs/manual/worlds.rst, the JSON given as an example doesn't have a "width" and "height".

Without a "width" and "height", my pull request in its current state for tmxrasterizer for .world doesn't work.
Ideally, "width" and "height" would be computed from the actual .tmx file.

**Comment by RainingChain** [comment]
For my PR, I can easily calculate the correct map size in TmxRasterizer::renderWorld() instead of using `World::MapEntry::rect`. But I think it would be better if it was initialized properly in WorldManager::privateLoadWorld() in the first place, if it's acceptable performance-wise.

**Comment by bjorn** [comment]
> In `WorldManager::privateLoadWorld()`, you expect each map in the JSON to have a "width" and "height" value. However, in the documentation, /tiled/docs/manual/worlds.rst, the JSON given as an example doesn't have a "width" and "height".

Actually "width" and "height" properties are optional. They are explained in [the section about showing only the neighboring maps](http://doc.mapeditor.org/en/stable/manual/worlds/#showing-only-direct-neighbors). The defaults of 0 work fine when that setting is not used.

> But I think it would be better if it was initialized properly in WorldManager::privateLoadWorld() in the first place, if it's acceptable performance-wise.

Once loaded, the width and height of a map are known, but the worlds feature needs to know the size without loading each map. It can't be derived from the map size and tile size, because that only works for orthogonal maps.

**Comment by bjorn** [comment]
Closing this since I think the documentation is fine.

> Without a "width" and "height", my pull request in its current state for tmxrasterizer for .world doesn't work.
> Ideally, "width" and "height" would be computed from the actual .tmx file.

Let's look into that at the pull request #2067. :-)
