### ISSUE TITLE
Notification when custom property of file type cannot be resolved

### ISSUE THREAD

**Issue by Seanba** [bjorn/tiled#2080]
If a custom property references a file I would like some kind of notification if the user later moves or removes the file. I like the way Tiled handles this for when a tileset or texture dependency cannot be found so maybe custom properties can do that too?

Thanks as always. I remain a proud Tiled supporter. :)

**Comment by bjorn** [comment]
That's definitely a good idea. I'll see if it can be integrated with the "broken links widget", though in general I think Tiled really needs a better way to show errors and warnings.

**Comment by bjorn** [comment]
Well, that spawned quite a big amount of work, in a way.

Since I wasn't happy with the widget popping up when things fail to load, I'm trying to replace it. This ended up being the main thing I've been working on this month, but unfortunately it's not replaced yet.

However, there is now a new "Issues" view, and an Errors/Warnings counter in the status bar. With the above change, warnings are added to this view when there are custom file path properties pointing to files that do not exist. Double-clicking those warnings will in general select the relevant object, make sure the Properties view is visible and select the custom property. There are some edge-cases not implemented (like selection of terrains or having this work at all for properties on wang colors), but I don't expect many people to run into those.

![image](https://user-images.githubusercontent.com/531764/64160590-7f437e00-ce3c-11e9-95ab-9d07984f7d21.png)

Errors and warnings in the Issues view can also be reported from a script, where it is also possible to pass a callback function that is executed when the issue is activated.
