### ISSUE TITLE
Zooming in sometimes shifts focus away from zoomed area

### ISSUE THREAD

**Issue by sano98** [bjorn/tiled#2090]
When using mousewheel + STRG on the map-area (I'm not talking about the tileset editor as in #2039), sometimes the zoom focus is no longer on the area where the mouse cursor is.

But as in issue #2039, this is maybe best explained with a .gif:

![Tiled Zoom Off Detail](https://user-images.githubusercontent.com/8257477/54746511-9ebb5700-4bcc-11e9-80f0-c5d9d499a658.gif)

I've marked some colored areas which I want to zoom on.
Note how it works for the first two squares in the grey part of the map, but when I try to zoom onto the 3rd square in the blue part, the focus constantly shifts to some area above my actual zoom target.
I then manually scroll back down and zoom further, but again, zoom focus is not where the mouse cursor is.

I'm not yet sure about _what_ conditions cause the zoom to be off. I'm suspecting that it's somehow connected to the target zone being offset to the red-framed "normal" position of my map?

**Comment by bjorn** [comment]
> I'm not yet sure about _what_ conditions cause the zoom to be off. I'm suspecting that it's somehow connected to the target zone being offset to the red-framed "normal" position of my map?

Right, I suspect the same. Tiled sets a pretty large margin around the map that adjusts to the zoom level. But that means when zooming in, this margin gets smaller and can cause the view to scroll towards the map like is happening in your animation.

In your case, I think the fix would be for Tiled to take into account the layer offsets (which I guess you are using to put that layer outside of your map?), when calculating the map boundaries.

**Comment by sano98** [comment]
Hey Bjorn,
yes, you are correct: We use the layer offset to arrange a set of different floors for our buildings maps:

![VerticalSlice](https://user-images.githubusercontent.com/8257477/54913811-e48d5d80-4ef3-11e9-9672-8d034fb11588.PNG)

Only the rooftop is located "within" the map; all lower floors have a y-offset.
Usage of layer-offset seemed natural to me, as we export each single floor separately - or are we abusing the offset for something it was never designed for? 

Your idea for a fix sounds promising.

**Comment by faulknermano** [comment]
Reporting this here because I think the bug is the same even though the cause may be different.

## Problem
Zooming in on mouse cursor works between 5% up to 50% zoom. Beyond 50%, the zoom focus tends to go *upper-left* corner.

However, if the current view includes the upper-left corner of the map, then zooming works as expected

## Video
Please see this [video](http://faulknermano.com/pub/tiled/zoom_bug_2019_06_25_1.mp4)

- No offset applied to map.
- First part of video demonstrates zooming around the center of the map (i.e. upper-left corner of map is not visible). Notice it works when zooming between 5% to 50%.
- Second part of video demonstrates when zooming around the upper-left corner of map (corner is visible). Zooming to any zoom level works.
- This happens both with mouse wheel zoom or keyboard shortcut zoom.

---

Hope this helps. Thanks!

**Comment by bjorn** [comment]
@faulknermano A few questions since I've not seen this behavior: Does this happen consistently? Does it happen with all maps (or, can you attach yours so I can see if I can reproduce it with that one)? Did this happen with previous Tiled versions as well?

**Comment by faulknermano** [comment]
@bjorn It happens consistently. It happens on all maps, even a new default map of 32x32. I've just tried v1.2.3 and the bug is *not* present in that version. It is only present in v1.2.4.

**Comment by faulknermano** [comment]
Addition: I don't know if it matters, but I'm on a laptop at 1280x800 resolution.
