### ISSUE TITLE
Which objects should/shouldn't be rendered by rendering libraries?

### ISSUE THREAD

**Issue by DanTup** [bjorn/tiled#2122]
Some of the objects in the file formats have `visible` properties, and the docs say:

> Whether object is shown in editor.

I'm curious about the handling of these for a rendering library. If the flag is only intended to be used by the editor, then which objects should/shouldn't be drawn by a rendering library? Some of the example maps I saw had things like spawn points and NPC paths, which don't seem like they should be rendered. However there's also a text type, which seems like it is designed to be rendered.

Are there any guidelines on this? I plan to have a debug flag that will render all objects to aid debugging, but when this is off, I'm not exactly sure what should/shouldn't be rendered.

**Comment by bjorn** [comment]
Well, I guess there is no general rule on whether a certain object is supposed to be rendered in the game or not, since this depends on the game. Shape objects generally are not rendered in the game, but some games might do it. Tile objects generally are rendered in the game, but some games may use tile objects as an aid for placing stuff (like using an icon for "particle effect" or "ambient sound"). Text objects can be rendered as part of a UI, or can be used to just place comments.

Even regarding the visibility property, it is up to the game. My advice would be to make this property available to the game but not to use it by default to determine whether to render a certain object or layer. The same goes for the layer opacity. While games may use these properties, I think most often the opacity and visibility are changed to aid in editing the map. In that case, it would be annoying if you had to remember to reset the visibility / opacity before saving. Similarly, it would be annoying if you had to hide a "collision layer" before saving, to make sure it won't show up in the game.

So, what should be the guideline? Most importantly, that the rendering library should put the user in control, because there is little that can be decided about this in general.

**Comment by DanTup** [comment]
> I can imagine the above may be a little inconvenient, and that a separation between "visual" and "meta" objects would be helpful

Or perhaps a separate `visible` state for editor and game? You could then set it by default in the editor based on type (eg. if the user adds a polygon, default to `visibleInGame=false` but for text maybe `true`). It feels like it'd be much nicer to be able to encode this in the map to reduce the effort for the user to have the map render correctly once loaded with a library. Or maybe an enum (Hidden, VisibleInGame, VisibleInEditor, Visible)?

(FWIW - as may be obvious - I've never created any games using Tiled, it just seemed like an interesting project for hacking on Flutter. I'm not familiar with the process of going from a Tiled map to a game, so some of my ideas/questions might be a little misguided, so I appreciate all the helpful responses!)

**Comment by bjorn** [comment]
I don't think it's helpful to add another visibility boolean. It's generally pretty natural for a game to decide what should be rendered or not, such that it makes little sense to introduce a manual option for this.
