### ISSUE TITLE
JSON map export does not preserve tile properties when embedding tilesets

### ISSUE THREAD

**Issue by Themaister** [bjorn/tiled#2135]
I tried something like:

- Load a tilemap + tileset.
- Add some properties to one of the tiles
- Export tilemap w/ tileset embedding and tile properties do not appear in the JSON.

If I export the tileset on its own, the properties are exported. Are embedded tilesets "frozen" when they are imported into a tilemap somehow?

I stepped through MapToVariantConverter::toVariant for Tileset exports, and it's hitting the same code paths, but when embedding tilesets, the properties are not there for some reason.

**Comment by bjorn** [comment]
Hmm, I can't reproduce this issue (for me the property did appear in the exported json file). Which version of Tiled are you using and do you have any other export options enabled?

The process of preparing a map for export is implemented in `ExportHelper::prepareExportMap`. Tilesets go through `ExportHelper::prepareExportTileset`, but if just embedding of tilesets is enabled that just returns a clone of the tileset (which gets embedded because it will no longer have an associated file name).

**Comment by Themaister** [comment]
Thanks. I'll try to step through those and see what is going on ...

**Comment by Themaister** [comment]
Ok, figured it out. It seems the tilemap I was testing with somehow had a "local" version of the tileset which did not have the properties I set in the original tileset. Works as expected now.

**Comment by bjorn** [comment]
Ah, yeah the visualization in the UI of local vs. referenced tilesets could definitely be improved...
