### ISSUE TITLE
appdata.xml requires updating for flathub

### ISSUE THREAD

**Issue by Luke-Nukem** [bjorn/tiled#2150]
I recently tried updating the flathub distributed version and the build returns with:

```
builddir/files/share/appdata/org.mapeditor.Tiled.appdata.xml: FAILED:
• tag-invalid           : <metadata_license> is not valid [CC-BY-3.0 AND GPL-2.0]
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• tag-missing           : <release> required
```

[link](https://flathub.org/builds/#/builders/39/builds/635)

**Comment by bjorn** [comment]
This should suffice for content rating, according to filling in the form on [this site](https://hughsie.github.io/oars/generate.html):
```xml
  <content_rating type="oars-1.0" />
```
The `metadata_license` tag is the license of the `appdata.xml` file. It should choose one license. @TingPing, since you wrote this file, can you tell us which license you'd prefer?

I guess I'll look into adding `releases` and `release` section sometime in the next week, unless somebody else does it.

**Comment by TingPing** [comment]
`CC0-1.0`

**Comment by bjorn** [comment]
Alright, those issues should be fixed.

@Luke-Nukem Let me know how it goes next time you try to update the version distributed through FlatHub!

**Comment by Luke-Nukem** [comment]
Will do once a new release is tagged.
