### ISSUE TITLE
AutoMap feature segfaults Tiled on Ubuntu 18.10

### ISSUE THREAD

**Issue by DaVince** [bjorn/tiled#2157]
For some reason, Tiled closes with a Segmentation fault every time I try to use the AutoMap feature. This seems to happen on all versions for me: the Ubuntu-provided package, the latest pre-compiled version and when I compile from latest Git.

Running Tiled with gdb nets me the following message:
```gdb
Thread 1 "tiled" received signal SIGSEGV, Segmentation fault.
0x00005555557f69c1 in Tiled::TileLayerItem::syncWithTileLayer() ()
```

I'm running Ubuntu 18.10 on a Dell Latitude E6430.

I've attached the rule and automapping tmx as well as a test map:
[automap-crash.zip](https://github.com/bjorn/tiled/files/3390258/automap-crash.zip)

**Comment by JoaoBaptMG** [comment]
Were you using some of the features I introduced, like **OverflowBorder** and **WrapBorder**?

**Comment by bjorn** [comment]
Hmm, this is due to the use of group layers, which are not currently supported by the AutoMapping feature. But apparently it can even crash the application, if you have a group layer with the same name as a tile layer.

**Comment by bjorn** [comment]
I've pushed a fix for this crash, but it will not make the automapping rules work since nested layers are still unsupported. Maybe I can find some time to make it work in Tiled 1.3, but for now you'd have to take your input layers out of any group layers. Output layers will also be added at the top level.

To work around the problem in your local version, make sure you do not use the same name in the target map for layers that are tile layers in the rule map (the problem was caused by the group layer called "base").
