### ISSUE TITLE
Feature request: Find object/layer

### ISSUE THREAD

**Issue by JoeCreates** [bjorn/tiled#2162]
It would be very useful to be able to do a search for an object or layer by name or ID.

**Comment by bjorn** [comment]
This request duplicates #1467 and is implemented by #1566, but that PR is stuck on a bug that I still meant to look into. I'll have another look at that PR.

**Comment by bjorn** [comment]
@JoeCreates Object search by name or ID was implemented now, to be released in the next development snapshot (probably sometime next week).

The same is not possible for layers, but it wouldn't be hard to add a filter to the layers view as well. But do you really have that many layers that you need a search filter? (Well, I guess some people do...)

**Comment by JoeCreates** [comment]
I'm presently using tile layers to define game objects also. Basically I have objects in my world which are constructed out of tiles. I also use image layers to define reusable submaps (by exporting a map as an image then adding that to another map).

Crucially, I refer to the IDs of these sometimes in scripts. I might see a script trying to do something with the "tiled thing" with id x, and I don't know if it's an image layer, tile layer or object, because I'm treating them all as if they are objects. I'll see the id and I want to find that object quickly.

When we eventually get object reference fields I would similarly want to be able to assign tile layers, image layers, or groups (basically anything with a tiled id).

**Comment by bjorn** [comment]
> Crucially, I refer to the IDs of these sometimes in scripts. I might see a script trying to do something with the "tiled thing" with id x, and I don't know if it's an image layer, tile layer or object, because I'm treating them all as if they are objects. I'll see the id and I want to find that object quickly.

Hmm, but the IDs are only unique for each type of data. If you have three layers and three objects, they will both have IDs 1, 2 and 3. Does that not pose a problem?

> When we eventually get object reference fields I would similarly want to be able to assign tile layers, image layers, or groups (basically anything with a tiled id).

But when I implement object references, then it will probably only be able to refer to objects due to the above issue. If you want to refer to a layer, it would be a layer reference. Of course, it may make sense to unify all these types first, and I'm not entirely opposed to that, but I think this would be a huge change and likely not going to be backwards compatible.

**Comment by JoeCreates** [comment]
Are you sure they're not unique? I seem to have been incredibly lucky so far with not having any collisions if so. My layer IDs are huge even though I've not had many layers in the map and I have a couple of large maps and cross reference stuff all the time with no issue so far.

If true then it throws a bit of a spanner in the works for my current system. I could always add a prefix to the ids like t109, o345. A tiled reference field could maybe account for collisions by having an attribute or prefix to indicate the domain like this.

**Comment by bjorn** [comment]
> Are you sure they're not unique? I seem to have been incredibly lucky so far with not having any collisions if so. My layer IDs are huge even though I've not had many layers in the map and I have a couple of large maps and cross reference stuff all the time with no issue so far.

I'm sure about it. In [the TMX format](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#map), we have separate attributes for `nextobjectid` and `nextlayerid`, which simply count upwards.

I think your layer IDs likely got huge due to issue #2160.

> I could always add a prefix to the ids like t109, o345. A tiled reference field could maybe account for collisions by having an attribute or prefix to indicate the domain like this.

Doesn't sound like a bad idea! I'd probably go for a syntax like `object#20` and `layer#1`. Something to consider when implementing #707.
