### ISSUE TITLE
Disable alphanumeric sorting on Custom Properties

### ISSUE THREAD

**Issue by tdeeb** [bjorn/tiled#2164]
First off, I want to say that I've been using Tiled for almost a year now, and it's truly a pleasure to work with; thank you!

I'd like to see a way to disable alphanumeric sorting on an object's Custom Properties to keep the properties in the order you defined them. Here's an example of some existing properties on an object I'm using in an overworld map:
![Tiled Sorted Properties](https://user-images.githubusercontent.com/1388037/61597195-33a57f80-abc2-11e9-8db3-61ace2eeb9bd.png)

Due to the properties being sorted, I have to look around to find the "left", "up", "right", and "down" properties which relate to which levels this object leads to. With alphanumeric sorting disabled, I would be able to stack them all together and find and modify them more easily.

**Comment by EJlol** [comment]
In the mean time, as a work around you could prefix your properties for example: map_left, map_up, map_right, map_down.

**Comment by bjorn** [comment]
There is no easy way to show the properties in the order you defined them or to allow manual rearrangement of the properties, since they are stored in a sorted map data structure and not in a list. So I would also suggest to do like @EJlol suggested and prefix those properties with something meaningful like `exit.down` or `target.left`

One planned solution to grouping properties together is the ability to define custom compound types (#489). Within compound types, the order of the members would also be explicitly controllable.

**Comment by eishiya** [comment]
Custom property ordering came up again [on the forum](https://github.com/mapeditor/tiled/issues/2164).

@bjorn
> One planned solution to grouping properties together is the ability to define custom compound types (#489). Within compound types, the order of the members would also be explicitly controllable.

Looks like this didn't end up happening - class members are also in alphabetical order (I guess they're also a map? Which might also be the reason they're stored as a dictionary in JSON instead of like an array like other properties). Any plans to make at least the class property order controllable? My custom classes are currently a mess because the names match engine names and get sorted weird, and I'd prefer not to rename everything at this point ):

**Comment by akawana** [comment]
@bjorn 

I agree with the topic starter. It's serious when you work on a big project with dozens of custom properties. I also use numeric "prefixes" now, but it is terrible solution. 

Custom properties is the only way to connect map objects with code. We use them to assign quests, different type of behaviors' etc... 

Maybe there is a way to change the way they are stored in DB? Or maybe there is a way to assign hidden sorting key to them?
