### ISSUE TITLE
World regexp not follwing standard

### ISSUE THREAD

**Issue by JLoriault** [bjorn/tiled#2201]
its very clear that the regex pattern of a world file is not follwing standard regexp and I have fought with this for days. your documentation lacks explination of your modified format and only has a very cryptic example. either follow standard regexp or update the documentation please

**Comment by bjorn** [comment]
@JLoriault I understand the frustration of not getting something to work for days, but please try to be friendly to the people you're asking for help and who've developed the software you've chosen to use.

That said, I'm not aware of any way in which the regex pattern supported in the world file deviates from "standard regexp". If you could be a little more concrete about any differences then this could really help in finding out whether there's a useful note we could add to the documentation.

I've relying on `QRegularExpression`, which is a Qt class that [implements Perl-compatible regular expressions](https://doc.qt.io/qt-5/qregularexpression.html#introduction). Is that something that's not considered "standard regexp", or has the need for escaping characters due to the regular expression being inside of the JSON file caused you issues?

Finally, what did you consider cryptic about the example?

**Comment by JLoriault** [comment]
sorry wasn't trying to be rude english is not my native language. it may be the escaping I'm not sure but I know it doesn't seem to be matching on whole words ie (\w+)

according to an online tester it should be working but Tiled doesn't accept it

**Comment by JLoriault** [comment]
according to your example the following files:
[https://prnt.sc/pdwnpk](url)

should work with the following world file:

```
{
    "onlyShowAdjacentMaps": false,
    "patterns": [
        {
            "regexp": "*(\\w+) *(\\d+)-*(\\d+)\\.tmx",
            "multiplierX": 400,
            "multiplierY": 400,
            "offsetX": -400,
            "offsetY": -400
        }
    ],
    "type": "world"
}
```

but it refuses to load all 4 files and only loads the one I specifically open

**Comment by bjorn** [comment]
Alright, note that the parenthesis create a capture, and Tiled expects only two captures (the x and y coordinates). If you have more than two captures, it will not know which ones are the coordinates and refuses to use the pattern. So the fix should be to remove the parenthesis around `\\w+`.

I'll make sure that proper warnings will show when this happens in the next version of Tiled.

**Comment by briermay** [comment]
Ok I’ll try that later. I love tiled and the new supertiled2unity (although the docs are a little lacking) you have created awesome software just wish stuff like this was a little more documented

**Comment by briermay** [comment]
Heh apparently my phone is logged into my second account but thanks for the quick reply

**Comment by Seanba** [comment]
(SuperTiled2Unity guy here)

@briermay I hear you on the documentation. Personally, I find it the hardest part of a project to deliver on for something that is an on-the-side job. :\

**Comment by bjorn** [comment]
@Seanba Yeah, functionality and bug fixing always seems to trump documentation writing when time is short. I managed to develop the Tiled Manual only once I could spend some days on it, though it remains lacking on many areas as well.
