### ISSUE TITLE
What I'd love Tiled to become...

### ISSUE THREAD

**Issue by mrmalee** [bjorn/tiled#233]
I love Tiled, I think it's one of the best free tilebased map editors going around. However, since using it to build levels for 3 games now (and starting on a 4th) there are some things which are missing.

http://www.ogmoeditor.com/
http://chevyray.com/2012/01/making-levels-with-ogmo-editor-2/

The editor above is where I'd love Tiled to get to. Incorporating more of a "project" mentality, rather than scattered levels that have no relation to each other. Creating a game is a very evolving process for me, it's always changing. Sometimes I may need to completely re-work an enemy or object for it to work as I want. This is very frustrating in Tiled, there's no concept of "shared objects" or "templates". If I had 20 levels and in each of those levels were at least 100 enemies, and I had to change their properties, I would have to either edit xml or manually edit every object individually. That is an extremely tedious task and may result in a code side solution to avoid doing it. Which, imo, is not the way to create a game. 

I'd highly recommend downloading that editor and just seeing how you can create levels with it.

Now, while that editor is good, it lacks a lot of the stability and features of Tiled.
1. Tiled has a highly compressed tile format.
2. Tiled supports random painting / terrain.
3. Tiled has geometric objects
4. Better undo/redo (history)

I'm not trying to promote ogmo here at all or say it's better/worse. I'm just using it as a reference so that Tiled may adopt the same structure or at least head in that direction. In any case, I desperately need Tiled to evolve into something like this:
1. Project like structure (define top level layers, entity and object templates, tilesets, tiles...)
2. Ability to scale/flip/rotate any object.

I'd love to hear what other people think as well.

**Comment by downstroy** [comment]
just a comment (nearly 3 years later !!) on what has been said:

"But just a note about the thing about changing the stats of hundreds of enemies later on. This was not the way that feature was intended to be used. Basically Tiled expects you to define your enemies somewhere else, and then only have one custom variable on your object saying which of the enemies it is."


I think I understand the philosophy behind the custom properties of objects in the case of an enemy (as it is more "code-related" than 'map-related"), but as I have said in another issue ( #70 ), what about map-related stuff (typically platform, or as said in comments above: enemy path (like bats))

While I can handle all the logic of the platform/ enemy moving in code, and just have a name/ type to link to it, it is MUCH more convenient to define platform/ enemy path in the editor, because you visually see how many tiles the object needs to move, while in code it may be longer ( test an (X, Y) position, build and run, retest etc)

**Comment by atbigelow** [comment]
I think that stuff shouldn't exist in Tiled. However, having an easier and more powerful plugin system that would allow someone to customize Tiled to their team's needs would be more beneficial.

**Comment by toddcarnes** [comment]
I tend to agree with August, this stuff doesn't really belong in a map 
editor.

Todd

**Comment by bjorn** [comment]
We've come a long way since this issue was created, with many related features having been added in various Tiled releases (predefined object types #367, object templates #70, scaling/flipping/rotating of objects #11) and more will come in Tiled 1.4 (a project structure #1665, connections between objects #707).

That said, a big difference remains in that in Ogmo you start off with defining your project, the layers, custom properties and eventually each map, in Tiled it's each map that stores which layers it has. The main project-wide setting currently are the predefined object types. Another big difference is that in Ogmo many features can be turned off, like whether rotation or flipping should be enabled, and you can even do that per layer or per entity (though this may get tedious as well).

I've made sure the missing aspects that would be nice to have in Tiled are covered by more specific issues:

* Allow pre-defining the properties on other data types than objects (#1410)
* Allow disabling features to avoid using unsupported features (I've opened #2794 about this).

Please let me know if I've missed anything.
