### ISSUE TITLE
Save Tiled maps as any extension

### ISSUE THREAD

**Issue by LithiumToast** [bjorn/tiled#262]
In Tiled (0.8.1), I'm forced to save maps as the extension TMX. I would like to be able to save Tiled maps as any explicit typed extension. I would like it be the same for how someone would use Notepad to save a document; it defaults to the TXT extension (TMX in the case for Tiled) but still allows for anyone to save the document to any extension they so please.

Thanks!

**Comment by bjorn** [comment]
Tiled allows saving TMX files as both .tmx and .xml since a while. Hopefully .xml will work for you as well.

macOS is adding the extension automatically based on the selected file format as part of the native file dialog, so there isn't really a way to allow saving with any extension. Tiled would no longer be able to determine in which format you want to save the file.
