### ISSUE TITLE
UI buttons become darker each time you hover mouse pointer over them

### ISSUE THREAD

**Issue by gerchicov-bp** [bjorn/tiled#2667]

**Comment by bjorn** [comment]
Please tell me which Tiled version, which operating system and which theme settings you're using. Also, did this work as intended before? If so, which version was that?

**Comment by abrajam92** [comment]
Here, same problem with v1.3.0 on Mac OS 10.14.6, with the default theme and first use.

**Comment by bjorn** [comment]
Thanks for the additional information, @abrajam92! Tagging this as macOS-specific until someone reports this also happening on other platforms. The default theme on macOS is "Native". Could you try if it also happens when using "Tiled Fusion"?

I'll try if this issue can also be seen on macOS 10.13. I can't test on more recent versions.

**Comment by cgh20xx** [comment]
I have same Issue. macOS Catalina 10.15.1

**Comment by bjorn** [comment]
Unfortunately I can't reproduce this on macOS 10.13. Would somebody be able to provide a screenshot, or even better a short video capture of this problem? Would be useful to see the problem and also potentially to report the bug to the Qt framework, since this is unlikely to be a bug in Tiled.

**Comment by cgh20xx** [comment]
> Unfortunately I can't reproduce this on macOS 10.13. Would somebody be able to provide a screenshot, or even better a short video capture of this problem? Would be useful to see the problem and also potentially to report the bug to the Qt framework, since this is unlikely to be a bug in Tiled.

<img width="487" alt="截圖 2019-11-21 下午1 49 08" src="https://user-images.githubusercontent.com/3839869/69307633-2c70aa00-0c66-11ea-98ae-f2b882cb8b36.png">

**Comment by bjorn** [comment]
Alright, actually I do also see this issue on macOS 10.13, I just didn't realize the darker background only happens on the tools and then only for the selected one. Of course, that's because only selected buttons render this darker shade.

But, the root of the problem affects all buttons, and also causes for example icon shadows to become darker. It appears when a tool bar button is repainted, its background isn't. I doubt such a visible issue would affect a normal `QMainWindow` instance, but in Tiled there is a nested `QMainWindow` instance for each editor, which probably triggers the bug.

Note that the issue does not happen for floating tool bars, so you may want to float them for now. The issue also doesn't happen when you switch to the "Tiled Fusion" style in the Theme preferences.

**Comment by bjorn** [comment]
I noticed this issue is related to the use of a unified tool bar (it has a unified look along with the title bar). When I disable that the toolbar gets a gradient background and no longer has this bug.

However, disabling the unified tool bar triggers a different issue. Then the title bar appears to be slightly transparent but its blurred background is not updating when moving the window around. It only updates when resizing the window. It should be simply opaque. :-/

**Comment by Asparanc** [comment]
I can't reproduce this issue on macOS Catalina 10.15

**Comment by bjorn** [comment]
> I can't reproduce this issue on macOS Catalina 10.15

Did you potentially switch on OpenGL-accelerated rendering? Because since change f74edae689980602a9d658157dd70910bf289106 this will disable the unified title and tool bar, which appears to also fix the background rendering issue as mentioned in my previous comment.

I guess we should just disable the unified title and tool bar for now and also report this rendering issue in Qt. It's easier to live with a title bar that has a little bit broken transparency (which is another thing that should be reported as a Qt bug).

**Comment by Asparanc** [comment]
I can't reproduce it with and without OpenGL-accelerated rendering.

**Comment by bjorn** [comment]
> I can't reproduce it with and without OpenGL-accelerated rendering.

After disabling OpenGL-accelerated rendering, you would need to restart Tiled to see this issue again. Maybe that's why you couldn't reproduce it without OpenGL-accelerated rendering.

In any case, I've now entirely disabled the unified title bar and tool bar. I think it looks a bit ugly, but that's better than having these painting issues. There's still the alternative to switch the Tiled theme to "Tiled Fusion" in the Preferences, which may look better.
