### ISSUE TITLE
Problem with latest update

### ISSUE THREAD

**Issue by Rijackson** [bjorn/tiled#2668]
After the latest update:
![image](https://user-images.githubusercontent.com/22403551/68986032-5e5aba00-07e9-11ea-8d01-aff7cbf71a21.png)

**Comment by Rijackson** [comment]
I fixed it by uninstalling and then reinstalling, so you can close this.

**Comment by bjorn** [comment]
Yeah, that's what I was about to suggest. I think it happens when you switch from 32-bit to 64-bit without uninstalling first, but there may be other situations triggering this.

Unfortunately I have no idea how to prevent these issues. The error happens because binaries from different installers end up combined in the installation folder.

Thanks for reporting this, in any case!

**Comment by Rijackson** [comment]
I happened after an automatic update to the 64 bit version, so it's not a 32-bit vs 64 bit issue.
