### ISSUE TITLE
tiledquick packaging?

### ISSUE THREAD

**Issue by AMDmi3** [bjorn/tiled#2673]
Hi, I'm working on an update of FreeBSD port of tiled to 1.3.0 and it turns out that it now installs `tiledquick` binary, which is installed into `/opt` for some reason, and also fails to run:

```
% tiledquick
QQmlApplicationEngine failed to load component
qrc:/main.qml:6 module "Qt.labs.platform" is not installed
qrc:/main.qml:2 module "QtQuick.Controls" is not installed
qrc:/main.qml:6 module "Qt.labs.platform" is not installed
qrc:/main.qml:2 module "QtQuick.Controls" is not installed
```

Is it needed? Where should it be installed? Should it be fixed somehow?

**Comment by bjorn** [comment]
Hmm, I should probably look into disabling the installing and possibly also the compiling of this tool by default. It is not currently worth packaging properly because it's only a map viewer with very limited functionality.

That it installs to `/opt` seems to be because of the rules in `src/tiledquick/deployment.pri`, which was mostly intended to help with Android deployment. Since I use Qbs I never noticed this oddity in the qmake project. I would recommend you to switch to using Qbs for FreeBSD packaging as well.

In any case, I'll have a look at adjusting the project files. Thanks for raising this issue!

**Comment by AMDmi3** [comment]
> I should probably look into disabling the installing and possibly also the compiling of this tool by default

Got it, so I guess I'll disable it in `src/src.pro` for 1.3.0.

> I would recommend you to switch to using Qbs for FreeBSD packaging as well

Sorry, but I'd strongly prefer to stick with standard and supported (both upstream and by our existing build infrastructure) tools.

**Comment by bjorn** [comment]
> Got it, so I guess I'll disable it in `src/src.pro` for 1.3.0.

Yes, that's a good idea, along with the `tiledquickplugin` sub-project.

> Sorry, but I'd strongly prefer to stick with standard and supported (both upstream and by our existing build infrastructure) tools.

I totally understand, but keeping qmake working comes with a maintenance overhead for myself and a consistent stumbling block for any contributors. The only reason the qmake files are still there is because I use them to update the translation files (see #1484).

Maybe on the bright side for packaging, Qt has chosen to deprecate Qbs and to push for cmake instead. For now I love Qbs and am pretty sad about this decision, but it could mean that Tiled will build with cmake in the future.

**Comment by AMDmi3** [comment]
> I totally understand, but keeping qmake working comes with a maintenance overhead for myself and a consistent stumbling block for any contributors.

Totally understandable as well, but obs is likely going to be a similar block.

> but it could mean that Tiled will build with cmake in the future

That would be great!
