### ISSUE TITLE
Unable to export to Defold .collecition

### ISSUE THREAD

**Issue by piotrek-szczygiel** [bjorn/tiled#2677]
I read in patch notes that Tiled now support exporting to Defold .colleciton file.
Even though i enabled the Defold plugin, I can still only export to Defold .tilemap file format.

I use newest Tiled 1.31, and checked with all plugins enabled.

**Comment by bjorn** [comment]
It's because the list of files to ship with the Windows installer is manually maintained... sorry about that. I will make sure it ships in Tiled 1.3.2. In the meantime, it's shipping in the Windows 7-zip packages: https://update.mapeditor.org/snapshots-win/Tiled-2019.11.20-win64.7z

Thanks for bringing this up!
