### ISSUE TITLE
Proposing new TMX format

### ISSUE THREAD

**Issue by odys-z** [bjorn/tiled#2692]
The programming ability supported by game engine is limited by their logical extension. Take [Godot](https://godotengine.org/) for example, it's a nice game app IDE but still restricted programmers skill. So I have to consider switching to opensource tools chain.
The later way also has some draw backs. The first is if using opensource engine like libGDX, there is no comparable tools for level editing and many other functions. Tiled gives a very strong start point for implementing such tools.
To extend Tiled to be a 2D level editor, there are some thing we can learn from Godot. Considering libGDX function possibilities, here are some proposed TMX format extension:
1. Support tree structure of objects
2. Include sprite - animation tile is already supported by libGDX
3. Support physics shape's simple editing - let's start with box2d fixture 
4. Use a concept of object group, which can be linked in as external resources, like Godot's Scene. It's actually a group of objects and wrapped functions

**Comment by bjorn** [comment]
I very much agree with all of this. Even though "Tiled" started out as a pure tile map editor, ever since support for objects was introduced, first just rectangles and later images and polygons, Tiled has become usable as generic level editor for many games. However, to be really a generic level editor it is indeed missing some important features as well.

> Support tree structure of objects

Yes, I think that would make a big difference. See #572 and #2062.

> Include sprite - animation tile is already supported by libGDX

The tile animation editor should indeed be extended to support defining multiple animations, as needed for most sprites (see #986 and #1059).

> Support physics shape's simple editing - let's start with box2d fixture

Tiled already features all physics shapes in Box2D (rectangle, circle, polygon and polyline), which can be placed on the map or used in the Tile Collision Editor. What it lacks is a default set of physics properties as well as a convenient way to set up joints (maybe will be possible with #707).

> 4\. Use a concept of object group, which can be linked in as external resources, like Godot's Scene. It's actually a group of objects and wrapped functions

I think that's covered by object hierarchy in combination with object templates (see #1860).

Since there are already issues open for all proposed changes I'll close this one now. Feel free to add further comments, open additional issues or comment on the existing ones if you feel something is missing!

**Comment by odys-z** [comment]
Any plan about data format?

**Comment by bjorn** [comment]
> Any plan about data format?

Each of these features will need changes in the format, but let's consider those when we get around to implementing them. Feel free to help with that process!

**Comment by odys-z** [comment]
That must be a great tool with these new features!
