### ISSUE TITLE
Scripting API: Access other file loaders

### ISSUE THREAD

**Issue by Phlosioneer** [bjorn/tiled#2696]
Currently, if you want to create a plugin that loads a slightly modified .tsx or .tmx file, you have to re-write the entire file parsing algorithm yourself.

It would be very convenient and useful to be able to use another file loader, and then modify that afterwards. For example:

```js
tiled.registerTilesetFormat("My tsx", {
  name: "My TSX modifications",
  extension: "mytsx",

  read: function(filename) {
    // Load this file as if it was a ".tsx" file.
    return tiled.getTilesetFormat("tsx").read(filename);
  },

  write: function(tileset, filename) {
    for (var tile : tileset.tiles) {
      if (tile.width > 32 || tile.height > 32) {
        tile.type = "XL";
      }
    }
    
    // Save this file as if it was a ".tsx" file.
    tiled.getTilesetFormat("tsx").write(tileset, filename);
});
```

This would also help in situations where a custom file is transformed into a normal one: (assuming a command is setup to call `tar`)
```js
tiled.registerTileMapFormat("Archived", {
  name: "Archived Map",
  extension: "tar.gz",

  read: function(filename) {
    // Extract a .tsx file from the archive.
    tiled.executeCommand("unpackMapFromTar", true);
    // Continue with normal reading.
    return tiled.getTileMapFormat("tmx").read(filename);
  },

  write: function(map, filename) {
    // Do normal writing.
    tiled.getTileMapFormat("tmx").write(map, filename);
    // Copy it into the archive.
    tiled.executeCommand("repackMapIntoTar", true);
  }
});

// With a similar loader for tilesets
```

As the examples above show, the only added functions would be `tiled.getTileMapFormat(extension: string)` and `tiled.getTilesetFormat(extension: string)`

**Comment by Phlosioneer** [comment]
It would also be nice to provide `readFromString` and `writeToString` specifically for the native tileset/tilemap loaders. That way you could e.g. modify the XML and then load normally, without needing a temp file.

**Comment by bjorn** [comment]
I like the suggestion! Though I have to note, that in this snippet:
```js
write: function(tileset, filename) {
    for (var tile : tileset.tiles) {
      if (tile.width > 32 || tile.height > 32) {
        tile.type = "XL";
      }
    }
    
    // Save this file as if it was a ".tsx" file.
    tiled.getTilesetFormat("tsx").write(tileset, filename);
}
```
The `tileset` is actually read-only since changes to the tileset are not expected to be done by the writer.

We could consider changing that, either simply allowing the writer to change the asset or always passing a copy such that changes can be made but will not affect the original asset. Note that in case of exporting, the passed map or tileset will already be a potentially modified copy if any export options are enabled.

Alternatively, if you want to potentially modify an asset before saving it, you can connect to the `tiled.assetAboutToBeSaved` signal and modify the asset there.

**Comment by Phlosioneer** [comment]
For that particular snippet, assetAboutToBeSaved would work better, yeah. It was only intended as a mock-up of what the feature would look like, though. I'm much more interested in before-read and after-write modifications.

My exact use case: I'm taking a large number of static layers and pre-rendering them to a single image. Then the cached image is inserted into the TSX file, and then I set visible=false on the cached layers. However, I want to strip that cached image out before tiled loads the map, and I want to automatically generate the cached image when saving the map. (The layer visibility would be toggled accordingly.)

**Comment by Phlosioneer** [comment]
Hey, I'm working on this feature and I've run into an issue in the `read` function.

How do I return an EditableMap to JS from a C++ function called via JS?

I can construct a `std::unique_ptr<EditableMap>`, and I can return a pointer to it using `...->newQObject(editableMap.get())`. But I've gotta put the unique pointer somewhere, or else it'll be destroyed at the end of the function. But if I put it in an array somewhere, then how do I know when to delete it?

I'd really like to just have QJSEngine's garbage collector handle it. But how do I give it ownership?

**Comment by bjorn** [comment]
> How do I return an EditableMap to JS from a C++ function called via JS?

There is some special logic to determine object ownership, but if it doesn't do what you want then you can set it manually, as done by the `EditableManager`:

https://github.com/bjorn/tiled/blob/ee65109cfd0057a789c56cb1362c45b51e5f9a9b/src/tiled/editablemanager.cpp#L100

By default, if I remember correctly, ownership goes like this:

* QObject with parent is assumed owned by C++
* QObject without parent becomes owned by the JS engine, except when returned as the value of a property.

So the `EditableManager` sets ownership explicitly, because sometimes the editables it has created get returned as value of a property.
