### ISSUE TITLE
Inconsistent behavior for stamp and eraser

### ISSUE THREAD

**Issue by Phlosioneer** [bjorn/tiled#2719]
When opening a new map, the stamp tool will work immediately. But the erase tool will not work until you've selected a layer.

I *think* this behavior issue only applies to maps with exactly one layer (e.g. when creating a new map).

It's caused me confusion in the past, and someone else recently: https://discourse.mapeditor.org/t/very-newbie-eraser-tip/4271

**Comment by bjorn** [comment]
Problem is that `mSelectedLayers` is left empty by `MapDocument` constructor instead of being set to a list with `mCurrentLayer` if that value is not `nullptr`. The eraser applies to the selected layers.

The inconsistency happens because the stamp tool has some special logic applying to the "current layer", but really the "current layer" should always be a selected layer.
