### ISSUE TITLE
[JS] Accessing MapObject.layer causes debug assert error

### ISSUE THREAD

**Issue by Phlosioneer** [bjorn/tiled#2726]
To reproduce, open a map file, select an object, then enter `tiled.activeAsset.selectedObjects[0].layer` on a debug version of tiled. The distributed version of tiled does not have this error, so I assume it has debug assertions disabled.

`EditableMapObject::layer` calls `EditableManager::editableObjectGroup`, which has the line:

```c++
Q_ASSERT(!objectGroup->map());
```

https://github.com/bjorn/tiled/blob/eee64867a4639466171432e029bb8d3c241edaac/src/tiled/editablemanager.cpp#L106-L120

Which fails, because the object is part of a layer that is part of the map. I would fix this, but I'm unsure what this assert is here for. Is `mEditableLayers` only for detached layers?

~~On a related note, I think we need a test suite for scripting stuff. If I figure out how the current tests work, I might start working on that.~~ Opening separate issue.

**Comment by Phlosioneer** [comment]
Wait. That line is different from the copy of Master I have. Something weird has happened...

**Comment by Phlosioneer** [comment]
I just linked the wrong line. Updated the original post with the correct link.

**Comment by bjorn** [comment]
> Which fails, because the object is part of a layer that is part of the map. I would fix this, but I'm unsure what this assert is here for. Is `mEditableLayers` only for detached layers?

Hmm, when `EditableManager::editableObjectGroup` was introduced it was for object groups owned by a tile, which do not point to a map. However, in the same patch I already used the function in `EditableMapObject::layer` as well. And even if I hadn't, I do not remember why I asserted that there is no map.

I'm pretty sure the assertion can just be removed, since the behavior of the function is otherwise identical to `EditableManager::editableLayer`. The `static_cast` in `EditableMapObject::layer` can be removed as well.
