### ISSUE TITLE
Auto Tiling using Terrain not working well

### ISSUE THREAD

**Issue by mojoyup1528** [bjorn/tiled#2739]
I have followed tutorials on such, and at one point someone said it used to work, but now its algorithm seems random. 

Issue 1: After creating a terrain using 9 tiles, for example, The burshing of the terrain will generate a very messed up random set of the tiles, at times even erasing a tile completely. 

I outline it correctly during the terrain creation of the tileset, and the sizing is correct. Ive made tilesets many times before, so I know that part of it is correct. Its something about the algorithm.

**Comment by bjorn** [comment]
Can you provide some screenshots or the actual files, so that the problem may be reproducible?

**Comment by mojoyup1528** [comment]
Sure thing :) Ill attach what I can in a video if tht is ok. Will post on YT

**Comment by mojoyup1528** [comment]
The video is currently processing, but should be ready to view soon. I started with a new map. I ended up finding some of my issue while making the video :P. But still I believe I may be doing something wrong. TY so much for the help! If able you can comment either here (prob required) and/or my video if allowed in the settings. :)


LINK:[https://youtu.be/btyxP5IJIRI](url)

**Comment by mojoyup1528** [comment]
The part where I realize the issue I come across, is more towards the end. But, I tried to follow the best I could with what I read about :P

**Comment by bjorn** [comment]
Indeed, as you noticed with the grass tile, you have to make sure to mark all relevant tiles for the tool to work correctly. For transitions between two terrains, there are 2^4=16 possible transitions, but you've marked only 10 tiles. Most importantly, you've missed to mark the 4 tiles that have dirt at 3 of their corners, which are in the bottom-right of your tileset. Without those, the terrain tool will appear to produce "random" results in situations where it needs those corners.

The remaining 2 transition tiles do not seem to be present in the tileset, which would be tiles that have grass and dirt opposite of each other diagonally. However, in general the tool will work fine without those variations.

Note that your tileset has many other tiles that will not work with the terrain tool, because the terrain tool only works with the 4 corners of each tile and does not take the sides or middle into account.

**Comment by mojoyup1528** [comment]
Awesome ty. I knew I was messing something up :P. Ill give it a try now and it should work well :) I marked both bottom left and right sides (noting that those are the ones with 4 tiled that have the circle in the middle after marking them :)  ) And it does get rid of many of the randomness :) Works MUCH better now TY!
