### ISSUE TITLE
weird rotation values

### ISSUE THREAD

**Issue by mokalux** [bjorn/tiled#2775]
thank you for this great tile editor.
Tiled Map Editor
**Version** 2020.03.18
**OS**: windows 10 64bits

**steps to reproduce:**
-  create an object in the object layer, for example a rectangle or a sphere

**issues:**
- when you rotate the object from the bottom right anchor the full rotation doesn't go to 360 but to around 341.30!
- when you rotate the object from an anchor other than the bottom right the values are not the same!
- the above values change depending on the object type too!

Is this expected?

Thank you.

**Comment by bjorn** [comment]
What is the problem with the weird values? I guess from 341.30 it wraps back to -18.7? Or is something actually misbehaving?

In the end it shouldn't matter, but we could add a normalization step when using the rotation tool to make it use values from 0 to 360 to avoid confusion.

**Comment by mokalux** [comment]
> In the end it shouldn't matter, but we could add a normalization step when using the rotation tool to make it use values from 0 to 360 to avoid confusion.

The problem is the values are different depending on the anchor (for example it can go from 500 to 600 on the bottom left anchor). Normalization step from 0 to 360 would be good imho for all anchors.

Thanks for the reply.

**Comment by bjorn** [comment]
> The problem is the values are different depending on the anchor (for example it can go from 500 to 600 when rotating using the bottom left anchor). Normalization step from 0 to 360 would be good imho for all anchors.

I still wonder how these different values are causing any problems.

> * a minor bug when you rotate using the mouse and then set the rotation value in the properties panel by hand then the object changes position.

It's not a bug. When you use the rotation tool, it rotates around the anchor, which it places in the middle of all selected objects (though it can be dragged before rotating). This means the tool is moving your object as well as rotating it. When you change the rotation value in the Properties, you're changing just that, and the rotation is applied around the origin of the object (generally, bottom-left for tile objects and top-left for rectangles - though since Tiled 1.4 you can specify a different origin for tile objects and make them match rectangles for example).

**Comment by mokalux** [comment]
thank you for the explanation.
For the rotation values I think it's really weird, but that's ok. Do you have the exact values so I can normalize them by code please?
