### ISSUE TITLE
Compression level

### ISSUE THREAD

**Issue by fwsGonzo** [bjorn/tiled#2789]
Is there a difference in compression between the TMX (XML format) and JSON? I have a very fast JSON loader, and I can't say the same for XML, so do you have any experience regarding this? A quick test showed that the .json files were 28% larger than .tmx with default compression.

I also noticed that the JSON values are stored as:

```
                 "name":"objects",
                 "type":"bool",
                 "value":true
```
JSON already has these types implicitly, so it could be:
```
                 "objects": true
```
Where do I change this in the code?

**Comment by bjorn** [comment]
> Is there a difference in compression between the TMX (XML format) and JSON?

No. The compression affects only tile layer data, which in both formats is compressed using the chosen format and then base64 encoded.

> JSON already has these types implicitly

While it has the "bool" type, it does not have all the types currently supported in Tiled files (like "file", "object" and "color", some of which are not really new types but rather give a string or a number additional meaning).

Tiled used to store the values like that until version 1.1, but I changed it to the array in Tiled 1.2. It wouldn't have mattered much for size, because as of version 1.1 there was the following additional property:

```json
"propertytypes": {
    "objects": "bool"
}
```

But in any case, while we can't just remove some information, there is a lot we can do to reduce the file size:

* You can enable the "Minimize output" option in the Preferences, which in case of JSON removes all whitespace.
* You could change the code to leave out more properties when their value is the default value. If you'd like to modify Tiled you can do this by changing `src/libtiled/maptovariantconverter.cpp`. Though I'm not sure you'll see big results here.
* You could implement [your own format as an extension](http://doc.mapeditor.org/en/stable/reference/scripting/#script-registermapformat) that only writes out the parts you're interested in.

**Comment by fwsGonzo** [comment]
Thanks, and yes those are good points. As you noted the filesize was drastically lowered by minimizing the output (and it can be further lowered by compressing the file itself).

Cheers.
