### ISSUE TITLE
Can we export the correct Tile IDs for sake of user friendliness?

### ISSUE THREAD

**Issue by newbiemate** [bjorn/tiled#2790]
The map data in the **tmx file** has a list of tileset IDs like so:
```
"layers":[
        {
         "data":[62, 62, 62, 62, 62, 97, 98, 62, 62, 62, 62, 62, 62, 62],
```

But in the actual **tileset tsx** file, the ID does not map to the correct tile. It seems to be off by 1.

I read somewhere that there is a firstgrid global ID assigned to a tileset, and you have to do some kind of math to figure out the "true ID" of a tile. [Here is the closed ticket](https://github.com/bjorn/tiled/issues/2762)

This is not intuitive by default, when a user exports their data they expect the IDs to match 1:1, and should not have to do some kind of math to figure the correct tile from the tileset. Generally speaking, when dealing with IDs in exported data, users should not need to do external calculations to map to another relation containing that same ID, unless this is per the user's data model. If we take sql for example, you wouldn't want foreign keys to reference some other primary key with (primary_key + N) just out of the blue when exporting, when they expect foreign keys to equal primary key in another table.

Tiled can still using its method of ID tracking internally when the user is using the application, that's fine. But when exporting our data, can we **by default**, align the tile IDs in the tmx/tsx file, for sake of user friendliness? 

Just FYI, I am using JSON export functionality, not sure if the other export formats have the same issue as above.

**Comment by bjorn** [comment]
This is not possible in general since a map can use multiple tilesets, and the tiles in each tileset start counting from ID 0. Also, the first tileset starts at global ID 1 because the 0 is used to mean "empty cell".

While there are alternative methods, I don't think changing this is helpful at this point. It doesn't help to do a special case for single-tileset maps, since this will only complicate things further.
