### ISSUE TITLE
Better world pattern regex example?

### ISSUE THREAD

**Issue by krazyjakee** [bjorn/tiled#2800]
```
{
  "patterns": [
    {
      "regexp": "(.*).json",
      "multiplierX": 3840,
      "multiplierY": 2176,
      "offsetX": -3840,
      "offsetY": -2176
    }
  ],
  "type": "world"
}
```

I'm just trying to capture all json files in the current folder but it is not resolving any. The example regex is a bit convoluted to understand.

**Comment by bjorn** [comment]
Hmm, how could the example be improved? Most of the time, your pattern will need to look rather similar. Note that Tiled needs to know where in the world each map matched by the pattern is located. That's why it needs to capture two numbers (x and y). This is what the `(\\d+)` parts are doing. You should not capture anything else than the coordinates of the map.

If your maps are not using a naming pattern that determines the location of each map, then you need to add each map individually so that its location can be specified. In this case, I can really recommend installing the _snapshot_ release, which will soon become Tiled 1.4, since it includes a tool with which you can add maps to a world and drag them around.

**Comment by krazyjakee** [comment]
@bjorn oh shit that is awesome! I completely missed that the map names required a convention. I thought they would just pick them up based on the x/ys.

Thanks so much for the help and for enabling me to build my game.
