### ISSUE TITLE
Logic issue with flipped tiles

### ISSUE THREAD

**Issue by krazyjakee** [bjorn/tiled#2803]
Here's a code example in javascript based on [the docs](https://doc.mapeditor.org/fr/stable/reference/tmx-map-format/#tile-flipping).

https://jsfiddle.net/denka5zu/5/

Diagonal and vertical are working fine but horizontal never seems to be correctly calculated.

What is different to horizontal than the others?

**Comment by bjorn** [comment]
Due to [the way bitwise operators work in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators) (converting the numbers to signed 32-bit integers, then doing the bitwise operation and then converting them back to JavaScript numbers (doubles)) the result of `global_tile_id & flippedHorizontal` is `-2147483648` (since the horizontal flipping bit is the sign bit for signed 32-bit integers). This is why the `flipped_horizontally > 0` check always returns `false`.

A possible solution would be to just check `!= 0` instead of `> 0`.
