### ISSUE TITLE
Property of type "Object" same as property of type "integer" on Lua file

### ISSUE THREAD

**Issue by LarryFr** [bjorn/tiled#2812]
On an object, I've added a property of type "Object". I've selected another object to fill this property.

When I've exported the map as Lua file, I've discovered that the object property is only stored as the ID of the object. The issue is that we cannot determine if the property is an integer or an object.

Here the map pointing to the right object (no problem here) :
![TiledBug_2020-05-30 072409](https://user-images.githubusercontent.com/11402573/83326999-9f2a9580-a246-11ea-936c-721cfa38c1f8.png)

Here the export in Lua :
![TiledBug_2020-05-30 072600](https://user-images.githubusercontent.com/11402573/83327035-e0bb4080-a246-11ea-9fad-a1ae2e980761.png)

As you can see, I'm unable to make a difference between an integer and an object.

**How to reproduce :**
1. Create 2 objects
2. Add a property of type "Object" and select the other object
3. Add another property of type "Integer" and set the id of the other object
4. Export the map as Lua file

**What behaviour is expected :**
properties = {
    ["MySecondObject"] = { 
        type = "object",
        value = 2
    },
    ["MyInteger"] = {
        type = "integer",
        value = 2
    },

**Comment by bjorn** [comment]
> The issue is that we cannot determine if the property is an integer or an object.

Hmm, true, the Lua format does not include the type of the property. So you have the same problem with "file" properties, which look just like "string", and "float" looks just like "int" when it's non-fractional.

I'm curious though, why is it an issue?

The suggested expected behavior feels a little wasteful for the common case where the game does not care about or already knows the type of the property to expect. It is also problematic for backwards compatibility reasons.

Backwards compatibility will be less of an issue when we change just the way the object reference properties are stored. I'm considering storing them as follows:
```lua
properties = {
  ["MySecondObject"] = { id = 2 },
}
```
This would add the ability to include the "name" field, if not empty, to make it easier to see what object is referenced, and we could add a "map" or "file" field in the future, in case we ever support object references to objects in another file.

**Comment by LarryFr** [comment]
Thanks for your rapid answer.

I am trying to automate the opening of doors from an object on each map. A simple way to determine which item is impacted is to get the id of the item.
My code don't know which map is loaded and don't need to. It needs some objects of a specific type (notes, interactive, gap) and apply an action if it can find the correct informations into the object. That's why I need to check if the property is an object property or a simple integer property.

If you add the id (or whatever you think), it will be great and I could adjust my own library.

Regards
