### ISSUE TITLE
Select/draw/del/C&P in multiple layers

### ISSUE THREAD

**Issue by olmototis** [bjorn/tiled#282]
Hi, a little request:
 It'll be awesome if you could select multiple layers and work with all at the same. For example:

You select 3 layers, then make a tile selection, copy and paste. Each tile could be drawed on the same layer name, or maybe on the current selected layers, respecting the same order (or something like that).

I usually have zones drawed in 3/4 layers that I want to repeat in the map, and I have to C/P each layer.

Thank you very much, and sorry for my english :)
 (I don't know if this is the right place for doing requests, if not, delete it ;)

**Comment by saluk** [comment]
I really would like this feature. I have fairly complex trees in my scene, which end up being 4 or 5 layers deep. The only way to copy and paste trees around the map is to do it 5 times for every single tree. It's just not feasible. In my use case, most of the issues mentioned are not issues, as I am never copying from one map to another - only copying tiles I've drawn within a single map; and I never care about copying tiles and objects at the same time. The stamp brush is the only complex piece in that case.

No offense intended (thanks for the years of effort!), but it is sometimes sad to see features put on the back burner because doing them perfectly is difficult; when doing the most basic or imperfect version of the feature is actually 80% of what people want.

**Comment by nicloay** [comment]
is this possible to make copy/paste of all layers within one document? in this case should not be any problem. if user removed or add new layer, just show notification that selection in buffer would lost.

**Comment by bjorn** [comment]
@nicloay While this would avoid some of the issues, it does not make this an easy task since the stamp brush still needs to be adapted to handle multiple layers. It would also introduce a parallel copy/paste system which I'm not too fond of.

In general this is an issue I'd like to address, but I have to choose my priorities somehow. Due to the limited time I've had for Tiled development over the past two years, my priorities have been driven mainly by pull requests and sponsored features. And this feature is something nobody set out to address nor did anybody offer to pay for it. I hope that based on [support via Patreon](https://www.patreon.com/bjorn), I will soon be able to spend one full day per week on Tiled which would make time available for working on issues like these.

**Comment by ArmagonNo1** [comment]
Just wanted to echo the sentiments of others here. Being able to select multiple layers, dragging out a box and then being able to either move or copy the selection would be so helpful.

**Comment by Michael-Hamburger** [comment]
This would be extremely helpful when creating automapping rules.

**Comment by ericmuyser** [comment]
Pretty much the biggest thing that could be done to improve workflow/quality of maps.

**Comment by axboureau** [comment]
I also think it would be the greatest improvement to the usability of tiled currently.
Regarding the best way to do it, why not have a button to select from all layers?
Then the copy/paste would not have to be any different (at least from the user point of view).
Then for pasting, there could be 2 ways to handle it:
a) The tiles could be copied with their index and offset to the current layer, and pasting them would paste to the layer given by currentlayer+offset.

b) The tiles would be copied with their index and the layer name, and when pasting each selected tile would be pasted into the layer of the same name at the current location.
If it does not exist (because it is another map), then a layer of the same name is created.

a) is more consistent with the current system
b) is more useful
I think any of the two can work.

**Comment by Bobjt** [comment]
Bjorn, how is this coming along? Do we need a bounty to move up the priority (if so, how much is needed given scope of work?). If more than I can pony up, I'll try to organize a pool.

**Comment by bjorn** [comment]
@Bobjt Even with spending two full days on Tiled, I'm totally swamped by all kinds of things. I think currently this is mostly because of the Google Summer of Code mentoring, and of course there's the time spent on documentation recently (moving to a more powerful format and to enable translations). Other problems are that major patrons have asked me to spend time on thinks like loading resources from URLs and soon showing adjacent maps in the same view.

So, of course it's an option to collect up to $200/month, at which point I will promise to commit at least a full day/month to the issue until it is resolved. When things calm down I will eventually get around to it, but I can't promise a timeline.

Scope-wise, I think this feature opens op a big can of worms, so a rough estimate would be 2-4 days of work.

**Comment by Bobjt** [comment]
Thanks for the follow up and I've adjusted contribution. Though not sure how long I can maintain gold level, I rely on Tiled heavily and so there are few hesitations with chipping in commensurate to my investment in my own title. Now worries if it takes a while. I might drop down and come back later to try again depending on finances availability. Either way, I'll be around cheering from the sideline.👍 Keep up the good work.

**Comment by bjorn** [comment]
@Bobjt A major thanks for increasing your support so dramatically! Unfortunately for this month I don't have a day available anymore, but that means I'll be looking for 2 days in August to focus on this issue. I've mentioned this issue in the [latest development update](https://www.patreon.com/posts/13548812). Thanks for the encouragement as well!

**Comment by bjorn** [comment]
Started work on this today, but made slow progress so far. There is a new branch `wip/multi-layer`, where I've enabled multi-selection in the Layers view (5b3b1991b44ddab483cfd67aa50747886fb14713). In coming days I will see how this will affect various actions, especially painting and selection, but also grouping or moving up/down multiple layers for example.

**Comment by Bobjt** [comment]
So excited, Bjørn. While milling away in Tiled as many hours of the day as possible, I've been watching the lists for status. Really looking forward to this one. Cheers!

**Comment by bjorn** [comment]
@Bobjt I'm quite excited about improving this area of Tiled myself as well. Thanks again for your support and sorry for the delay in getting to this!

**Comment by bjorn** [comment]
I've posted a demonstration based on the above commit on YouTube:

https://www.youtube.com/watch?v=pu-yShBRCqM

Unfortunately I have committed to a few other improvements as well, but I aim to get back to working on this in the next weeks.

**Comment by Bobjt** [comment]
It's looking perfect! The application Stamps is natural as well, assuming it's opening the ability for multi-level stamps too (?). I look forward to checking it out!

**Comment by bjorn** [comment]
> It's looking perfect! The application Stamps is natural as well, assuming it's opening the ability for multi-level stamps too (?). I look forward to checking it out!

Yes, in the video I tried to demonstrate that multi-layer stamps can also be saved and restored in the Stamps view. For now you can check it out only by compiling yourself from the `wip/multi-layer` branch, but I expect to merge this in the development snapshots sometime next week.

**Comment by Bobjt** [comment]
Fantastic! Related to this but probably a separate feature, will we have the ability to copy/paste between two different map files as well? (I suppose in its rudimentary form, assuming both maps share the same layer names/structure?) These features couldn't be coming at a better time since I've redone my map format once again and will be rebuilding the final maps from scratch very soon.

**Comment by ericmuyser** [comment]
Oh my god. Not to take away from it, but... finally! I'm so excited!

**Comment by bjorn** [comment]
> Fantastic! Related to this but probably a separate feature, will we have the ability to copy/paste between two different map files as well? (I suppose in its rudimentary form, assuming both maps share the same layer names/structure?)

I still have to adjust the copy/paste code, but I don't consider that a separate feature. The way it would currently work, is if you paste multiple layers, they would change the active stamp as usual, and then when you try to paint it will automatically create any layers that it can't find. Layers are matched by name, so it depends on those being unique. I hope this will be fine, but feel free to suggest alternative behaviors / options.

> Oh my god. Not to take away from it, but... finally! I'm so excited. Thanks guys!

I definitely share your sentiment!

**Comment by Bobjt** [comment]
> Layers are matched by name, so it depends on those being unique. 
No problem. That's one caveat that is easy to work around.

**Comment by bjorn** [comment]
After spending another two days on this (mostly adjusting cut, copy, paste and delete), today I've merged the `wip/multi-layer` branch to `master` and released [a new development snapshot](https://thorbjorn.itch.io/tiled/devlog/24167/multi-layer-editing-and-other-stuff)! Let me know if you find any issues or things not working as expected!

Known incomplete stuff:

* Most actions in the Layers view still only work on one layer.
* The Bucket Fill and Shape Fill tools are not adjusted yet.

**Comment by Bobjt** [comment]
Tried this tonight (macOS snapshot) and it's absolutely perfect! I haven't worked with it yet, but sure passes fundamental tests. I can move around in chunks and, from map to map. It's all very intuitive as well. I'm jumping for joy at this lovely work! Thank you, Bjorn!!! 🙌🍾⭐️🎊

**Comment by Bobjt** [comment]
Bjorn, the one issue I found in the 14-2-18 build regards rotation of multiple layers ('y' and 'z' shortcuts). Not all layers in the current stamp appear to get rotated.

**Comment by Bobjt** [comment]
Jesus, @bjorn you're a regular wizard. BUT, that's why I chose you as my map tools engineer because I already knew that 👹 Hee hee hee. I was relieved to hear that some more patrons chipped in to help cover costs. Of the hold outs I think 1/3 can't afford (shucks), another third are stingy (blast!), and the  there's this third kind that simply aren't thinking. Anyway, this fix is epic. Rotating layered sections is going to vary map look so rapidly that it's simply monumental. Keep up the good work!

**Comment by bjorn** [comment]
Well, I'm not sure if a wizard would make [so many mistakes](https://github.com/bjorn/tiled/commit/9f9a259a6230d2267447d8966204ef1613d97479) to the same small class, but today I did get [multi-layer stamps to play nicely with the fill tools](https://github.com/bjorn/tiled/commit/1f82423283262932f72769ea44e1916ca3f7d361), while reducing code size. ^^

**Comment by bjorn** [comment]
Ah, the long tail of adding certain features to an existing project! All above changes are included in today's [new development snapshot](https://thorbjorn.itch.io/tiled/devlog/43780/export-options-and-polishing).

Still areas that could use improvement:

* Make "Merge Layer Down" work with multiple selected layers. Should not be that hard, just need to make sure to process selected layers in the right order.

* Make the "Offset Layer" tool apply the offset to all selected layers. Here we mostly need to avoid moving a layer along with any of its parent layers, since that would apply the offset twice.

**Comment by Bobjt** [comment]
Holy, wow, that's a lot of change propagation. But believe me, I'm the first guy to understand... No one should ever see the map editor I created, now retired. It's got more bugs than Pfizer has pills, and I'm flat-out ashamed of the UI - it's a disgrace...I look up to you massively my friend!

**Comment by bjorn** [comment]
Alright, now the "Merge Layer Down" action and "Offset Layer" tool also work on all selected layers. In addition, the Properties view now behaves more like you would expect when having multiple layers selected, applying changes to layer attributes and custom properties to all of them.

At the moment I'm not aware of more areas that need adjustment to multi-selection for layers, so I'm closing this issue!
