### ISSUE TITLE
Adding new tiles to tsx file causes tmx files that use the tsx file to have incorrect firstgid

### ISSUE THREAD

**Issue by jonpchin** [bjorn/tiled#2826]
When I add a new tile to a tsx file it causes any tmx file that uses that tsx file to have incorrect firstgid. The way I get around this problem is I open up the tmx with the wrong firstgid that uses the tsx file and I click Save button in Tiled. Tiled will then update the firstgid in the tmx to be correct. I have to open up each tmx file that used the tsx file that was recently added a tile and manually click the Save button to fix this issue.

Is there a quicker way to resolve this issue besides manually saving each tmx every time I add a new tile to a tsx file? This seems like a cache problem. I would expect Tiled to automatically update each tmx file that needs to be updated instead of me manually trying to save each tmx file.

 I attached some screenshots of the before and after of the tmx file that is saved. What is show in the screenshots are the only differences of the tmx file for the before and after save.

![first_gid_change](https://user-images.githubusercontent.com/11801014/84361312-7638c780-ab99-11ea-8980-b9984c0fbad5.PNG)
![second_gid_change_in_tmx](https://user-images.githubusercontent.com/11801014/84361313-76d15e00-ab99-11ea-95d8-3a5ad8fa879d.PNG)

**Comment by jonpchin** [comment]
I tried clicking the Save All button with all the tmx files opened in the Tiled editor but it doesn't do anything. Only manually saving each tmx file resolves the issue.

**Comment by bjorn** [comment]
> I have to open up each tmx file that used the tsx file that was recently added a tile and manually click the Save button to fix this issue.

Please tell me what the actual issue is that you're fixing, because I think it lies outside of Tiled. I realize that to update the `firstgid` of tilesets that come after the tileset that you're extending will only be increased when you're re-saving the map, but what I don't understand is why you need this `firstgid` value to be increased?

Just like Tiled can load your existing maps with lower `firstgid` value fine, so should your game or the library you're using to load those Tiled maps have no problems loading the map regardless of whether they have been re-saved with higher `firstgid` values.

The thing is, the `firstgid` exists exactly to handle this case. A tileset may be extended by adding more tiles, either by increasing the height of the tileset image or by adding tiles to an image collection tileset. But by virtue of the `firstgid`, Tiled can still unambiguously determine to which tileset each global tile ID refers because the map couldn't possibly be referencing tiles that were added to the tileset after the map was saved.

**Comment by jonpchin** [comment]
I need to subtract the firstgid from the tile id to get the new tile id of what I am searching for in the layer. When a tile is add to a tsx file, the tsx file the id is updated but the tmx does not reflect. 

As a quick work around for now I will not add new tiles to an existing tsx that is used by tmx files. I will create a new tsx. I will close this issue.

**Comment by bjorn** [comment]
> When a tile is add to a tsx file, the tsx file updates the tile id but the tmx does not reflect the change.

I'm confused by this. When you add a tile to a tsx file, that tile gets an ID. Is that what you mean with "updating" the ID? Why would the tmx file reflect this, given that it doesn't store the tiles?

I'll try to explain a bit more:

* Suppose a map was saved that used two tilesets, both with 4 tiles. The first tileset gets `firstgid` of 1 as usual, and second tileset gets `firstgid` of 5, since global tile ID 4 is the last tile from the first tileset at that time.

* Now you add a tile to the first tileset, it will get internal ID 4.

* Now, when loading the map, the first tileset has 5 tiles and the second tileset still has 4. The `firstgid` of the second tileset is still 5 since this file did not change.

* Suppose the map file refers to a tile with global tile ID 5. Even though you may think it could refer to the new tile added to the first tileset (since 5 - 1 = 4), it really can't, because the second tileset has `firstgid` of 5. This means that from global tile ID 5 and upwards (and until the next tileset's `firstgid`, when there would be any) the tiles refer to tiles from the second tileset.

* So global tile ID 5 is the first tile (with internal ID 0) in the second tileset (5 - 5 = 0).

This is why [the documentation](https://doc.mapeditor.org/en/latest/reference/tmx-map-format/#data) states:

> Whatever format you choose for your layer data, you will always end up with so called “global tile IDs” (gids). They are global, since they may refer to a tile from any of the tilesets used by the map. In order to find out from which tileset the tile is you need to find the tileset with the highest firstgid that is still lower or equal than the gid. The tilesets are always stored with increasing firstgids.

So really, if this isn't working without re-saving the map, then something may be broken about `tmxlite` or your code. I'd really recommend fixing that issue rather than working it around by creating new .tsx files.

**Comment by jonpchin** [comment]
Yes, that is what I meant by "updating" the ID". Sorry for the confusion there. I tried reproducing the bug again by adding tiles to the tsx and I cannot reproduce the bug. I am only sure of the fix is resaving the tmx file but I am not sure what causes the bug.
