### ISSUE TITLE
Unexpected "Unable to reload template file" message

### ISSUE THREAD

**Issue by Nightspeller** [bjorn/tiled#2836]
In Tiled 1.4, Windows 10, I got a message in 'Issues' section, see screenshot. 

Bjorn's comment on Discord: "Hmm, those are not template files, so no wonder it can't reload them."

New info from comment - the message appears every time I try to save (and autoexport) the map (or save the tileset) - no loading or dragging by me happens as far as I can say

![image](https://user-images.githubusercontent.com/2891745/85066585-467f5600-b17d-11ea-89e5-19e5e83d2c8a.png)

**Comment by bjorn** [comment]
Yeah, so, what I think that it happening, is that at some point it tried to load those files as an object template (maybe you dragged them somewhere?). This failed, because they are not a template. However, this still created a "failed to load" template instance that does cause the file to be watched for changes, and it tries to reload that template every time it is changed on disk. This is when it reports that error.

Fix may be to not try to load these files as templates in the first place.

**Comment by Nightspeller** [comment]
New info - the message appears every time I try to save (and autoexport) the map - no loading or dragging by me happens as far as I can say

**Comment by bjorn** [comment]
Yep, I can confirm this doesn't require dragging the file anywhere. I'll look into it this evening.
