### ISSUE TITLE
Add shortcuts to move cursor and select adjacent tiles

### ISSUE THREAD

**Issue by NinjaFighter** [bjorn/tiled#284]
I think that would be great to use arrow keys to move the cursor to the next cell (displacing it using the current tile size and zoom values).
This feature could be very useful if you are using a laptop without mouse or if you want to be more precise.

Could be great if you can use another keys (or another configuration (ctrl + arrows for example)) to select adjacent tiles in tileset's window.

If the program have this shortcuts, it can be capable to be used without mouse, or simply with touchpad buttons. This could be very useful to use tiled if you are using a laptop over your lap, or on another circumstances where is not confortable to use a mouse or touchpad.

**Comment by bjorn** [comment]
I'll close this issue since it's not something I ever expect to implement. I think the implementation would be complicated given that it would conflict with using those keys to move the view. Also, to be really effective a lot more work will be required on all the key handling.

Tiled could have some more shortcuts to make the keyboard more useful, but I think it will always rely very much on having a mouse connected as well.
