### ISSUE TITLE
Zstandard enabled by default on linux binary

### ISSUE THREAD

**Issue by alphaonex86** [bjorn/tiled#2850]
Hi,

Zstandard can be enabled by default on linux binary?

Cheers,

**Comment by bjorn** [comment]
It is already enabled by default for the AppImage that's published here on GitHub and on itch.io.

But it's not enabled by default for the snap, so I guess you're using that one? It seems [zstd 1.3.3 is available on Ubuntu 18.04](https://packages.ubuntu.com/bionic/libzstd-dev), so we could try to enable it based on that.

**Comment by bjorn** [comment]
Three things that need to be addressed for this:
* Add `libzstd-dev` to the `build-packages` and `libzstd1` to the `stage-packages` in `snap/snapcraft.yml`.
* Currently only the Qbs project file has an option to enable Zstandard, whereas the snap is built with qmake. So qmake project will need to be able to search for Zstandard and define `TILED_ZSTD_SUPPORT`, or snap needs to use Qbs.
* Currently, only a custom Zstandard build is supported, not a system-installed one.

**Comment by bjorn** [comment]
I'm closing this issue since I've pushed a change that should enable Zstandard in the snap and makes it possible to do so with a custom build by passing `SYSTEM_ZSTD=yes` to qmake on the command-line.

It is not enabled by default, however. To enable this by default, the project file would need to be modified to link to the library conditionally based on availability. If this is doable contributions are welcome.
