### ISSUE TITLE
"Recent Files" not working on 1.4.1, Ubuntu/Snap

### ISSUE THREAD

**Issue by bendmorris** [bjorn/tiled#2852]
* I have a laptop with 1.4.0 installed, running Ubuntu 20.04, installed Tiled from Snap. "Recent Files" works, and when opening Tiled, I'm automatically taken to my last open file, which is nice.

* On a second Ubuntu 20.04 laptop, with 1.4.1, also installed from Snap, "Recent Files" is grayed out and empty, and on startup, no file is opened. If I open and close files within this session, they'll show up in Recent Files, but this doesn't persist across app sessions.

**Comment by bjorn** [comment]
Hmm, I can't reproduce this problem with the 1.4.1 snap version on Ubuntu 20.04.

Do you have a project loaded? Without project, the recent files are stored in the session at `~/snap/tiled/current/.local/share/tiled/default.tiled-session`. If you do have a project loaded, the session file should be stored alongside it.

Can you check whether the recent files are written to this file as expected?

**Comment by bendmorris** [comment]
I do not have a project loaded, and I do have such a file, which looks correct, but it hasn't been written to since the 18th. Just confirmed that when opening/closing files in a Tiled session, that file is not overwritten.

**Comment by bjorn** [comment]
Hmm, does it help to move it aside? I wonder if it could be a permissions issue.

**Comment by bjorn** [comment]
Also, you can check which snap path Tiled is currently using by going into _Preferences > Plugins_ and then looking at the extensions path. In my case this is `/home/bjorn/snap/tiled/1825/.config/tiled/extensions`. This matches with `current`, which is a symlink to `1825`.

**Comment by bendmorris** [comment]
It's owned by my user, so that doesn't seem to be the problem...I tried deleting it and it was not regenerated.

The extension path is: ~/snap/tiled/1831/.config/tiled/extensions which seems correct and matches `current`.

**Comment by bjorn** [comment]
Alright, I noticed you're probably on edge channel and as such get the 1831 version, and then I tried with that version as well. While in fact they are built using the exact same commit, I could reproduce the issue in 1831.

But, it is not related to the version. The problem is in the `.config/mapeditor.org/tiled.conf` file, which stores the last session:
```
[Project]
LastSession=/home/bjorn/snap/tiled/1831/.local/share/tiled/default.tiled-session
```
Since the path of the last session ends up including the snap version (if it's the default session, as opposed to a project-associated session), it will actually try to write to the file associated with that specific snap version. I think file permissions are likely set up such that reading files for a different version is allowed but writing is not.

I guess the fix is to leave this setting on an empty path, in case the default session should be loaded.

**Comment by bendmorris** [comment]
Sorry, forgot to mention I'm on the edge channel - I've been enjoying some of the awesome 1.4 features for a while now and had forgotten :smiley:

It looks like updating that config to point to 1831 has resolved the issue for me, so it's a good enough workaround for now. Thanks for looking into it!
