### ISSUE TITLE
Can't find the templates view

### ISSUE THREAD

**Issue by Pordrack** [bjorn/tiled#2854]
Hello, I made some templates for my project, but I can't find the template view. I've tried using the "Views and toolbars" option but I only found a "Template editor" that could only open one template at a time. The documentation talks about the template view but never say how to open it. I'm on Tiled 1.4.1 on Windows 7, and tried going back to the default view but the template view still isnt here.

**Comment by Nightspeller** [comment]
I am also interested in that! But for now you can open Project view (View -> Views and Toolbars -> Project) and select your templates from there. Once you click the file with the template, it will be available for editing in Template editor and also place-able on the map.

**Comment by bjorn** [comment]
Hmm, yeah, the file system part of the Templates view got replaced by the interaction with the Project view, which is why I renamed the Templates view to Template Editor. Unfortunately I didn't get around to updating this part of the documentation yet, since it will be a bit of work to update all the animated pictures.

Please let me know if you feel the Project + Template Editor suits your workflow or whether you're missing something about the Templates view as it was in Tiled 1.3.

I'll leave this issue open as a reminder to update the documentation.

**Comment by Pordrack** [comment]
It fits my work flow pretty well, the only downside I found is the fact that a new toolbar on the left made the center window a little too tiny, but it's mostly due to the fact that I'm currently on a small laptop screen, I guess using a reguler 16/9 screen would solve the "problem", but anyway, being able to put the "project" toolbar in the same corner as the tilesets could be useful.

**Comment by bjorn** [comment]
@Pordrack The fact that you can't dock the Template Editor below the Projects view is something that I find annoying as well and hope to fix sometime. It's because that editor is currently embedded in the editor view whereas the Projects view is part of the top-level window.

In the meantime, note that you can also use Ctrl+P to open templates in the Template Editor (since Tiled 1.4.1), which may mean you can just close the Projects view.

**Comment by bjorn** [comment]
Documentation was updated in 70374b9da4c2908dd289067b580291a7643d94e0.
