### ISSUE TITLE
No images detected when adding new tileset

### ISSUE THREAD

**Issue by chrisspen** [bjorn/tiled#2855]
If I select New->New Tileset, and click the "Browse" button for Source, no images are shown in any directory, even ones I know contain jpg, png, tiff, gif images. From the many tutorials, I'm pretty sure these formats are supported. Has this changed? What image formats are supported by Tiled? Why aren't common image formats showing up in the image selector anymore?

**Comment by bjorn** [comment]
Please say which operating system you're on and which Tiled version you're using. Also, do I understand correctly that you have not used a previous version of Tiled that did work as expected?

Which formats are supported depends on how you have installed Tiled, but generally Tiled ships with support for all common formats like bmp, png, gif, jpeg, tif, webp, tga, svg, etc. What does the file type selector in the file dialog show in your case?

**Comment by chrisspen** [comment]
Not sure what happened, but I tried completely uninstalling it and then reinstalling from a PPA and that seems to have fixed it.

**Comment by chrisspen** [comment]
To be clear, the "AppImage" available on the website appears to be broken out of the box on Ubuntu 18.04. As far as I can tell, those don't really work on most operating systems. I'd recommend sticking to a package for Linux, since those clearly document dependencies, which AppImages don't.

**Comment by bjorn** [comment]
Hmm, which PPA provides an updated version of Tiled? I used to maintain my own at https://launchpad.net/~mapeditor.org/+archive/ubuntu/tiled but it's really outdated by now (even the tiled-daily, which is failing for some reason). Maybe I should look into updating that package, but in the meantime, on Ubuntu you can also install Tiled as a snap.

Btw, AppImage doesn't specify its dependencies because it's meant to have none. I'll have see about testing the AppImage on Ubuntu 18.04 to check this problem.

**Comment by chrisspen** [comment]
Yeah, that's the PPA I used. There's no tiled-daily package though, but the tiled package installed and works fine.

If the AppImage is supposed to be self-contained, then something's very wrong with the most recent one. It gives me a bunch of missing library errors like:

    ./Tiled-1.4.1-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by ./Tiled-1.4.1-x86_64.AppImage)
    ./Tiled-1.4.1-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by /tmp/.mount_Tiled-V7PprU/usr/bin/../lib/libtiled.so)

**Comment by bjorn** [comment]
> Yeah, that's the PPA I used. There's no tiled-daily package though, but the tiled package installed and works fine.

If you prefer to use an Ubuntu package, then it may be better to use [the one from universe](https://packages.ubuntu.com/bionic/tiled), which is rather more up-to-date than the one in my PPA. Of course you may be using that one already since it has a newer version than the package in the PPA.

> If the AppImage is supposed to be self-contained, then something's very wrong with the most recent one. It gives me a bunch of missing library errors like:

It appears that for some reason it's picking the wrong `libQt5Core.so.5`, since in this error it's referring to a file on your system. When I extract the AppImage using `./Tiled-1.4.1-x86_64.AppImage --appimage-extract` and then do `ldd ./squashfs-root/usr/bin/tiled`, it lists this library as:

```
libQt5Core.so.5 => /home/bjorn/Downloads/linux-64bit/./squashfs-root/usr/bin/../lib/libQt5Core.so.5 (0x00007fcc4dee9000)
```

Normally it picks up that library because of the RPATH set in the executable and the `libtiled.so`. Do you maybe happen to have `LD_LIBRARY_PATH` set? This could cause it to not pick up the right library since it is searched before the RPATH. Though at least on Ubuntu 20.04 this leads to a different error:

```
$ export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
$ ./Tiled-1.4.1-x86_64.AppImage 
./Tiled-1.4.1-x86_64.AppImage: symbol lookup error: ./Tiled-1.4.1-x86_64.AppImage: undefined symbol: _ZdlPvm, version Qt_5
```
