### ISSUE TITLE
A suggest about Object Types 

### ISSUE THREAD

**Issue by refox1** [bjorn/tiled#2872]
Hi , we are developing a 2D game with tiled.

Many troubles are found in Object Types,
If can add a description of the type in the custom Object Types , it will be much more convenient to use, 
in many cases, the type is represented by a number or enmu, and always need go back to the code to see what it is.

There is another problem,
Types with default values are not saved to the TMX file, although the file size is smaller, but it needs to be associate ”objecttypes.xml“. 
It's not a good design ,TMX does not describe itself, sometimes it's easy to make mistakes.

Best wishes .
Thank you very much.

**Comment by refox1** [comment]
by the way, it would be better if could add the list or popupenum,
now the custom Object Types is a little simple.

**Comment by bjorn** [comment]
> Many troubles are found in Object Types,
> If can add a description of the type in the custom Object Types , it will be much more convenient to use,
> in many cases, the type is represented by a number or enum, and always need go back to the code to see what it is.

Indeed there is currently no support for custom "enum" types. To make your map more descriptive, I would suggest to use a string instead of a number to set the value. Eventually we will add support for defining custom enums, this is covered by issue #1211. I agree adding a "description" field to the custom properties would also be nice.

> There is another problem,
> Types with default values are not saved to the TMX file, although the file size is smaller, but it needs to be associate ”objecttypes.xml“.
> It's not a good design ,TMX does not describe itself, sometimes it's easy to make mistakes.

This is because explicitly including the values counts as "overriding" of the default value, so when we'd explicitly save all the values for each object instance and then you change a default value (for an object type property, a tile property or a template property), this change would not apply to any of the already placed objects, which would generally get annoying.

However, you can export your map and "resolve" these properties. For this there is the export option "Resolve object types and properties" in _Preferences > General > Export Options_.

I'll close this issue because the enum feature is already covered.
