### ISSUE TITLE
File > Save All  doesn't save all

### ISSUE THREAD

**Issue by aganm** [bjorn/tiled#2873]
Whether I press Ctrl+S to quick save or click the menu button **File > Save All**, it doesn't save my project nor my world.

If I want to save changes done to my world or project, I have to go in their respective menus and save them separately.

I would like for 'Save All' or Ctrl+S to actually save all the modified files in the project, be that rule sets, world file or the project file itself.

**Comment by bjorn** [comment]
I agree Save All should also save modified worlds.

The project file itself is automatically saved each time the project is modified. Rule sets should already be covered by "Save All" because they're just maps (in case you mean Automapping rule maps).

**Comment by bjorn** [comment]
Saving of modified worlds when doing Save All got implemented in 38ac5f0df6b61b4b7c46e89d5686749e433baca7 and released with Tiled 1.4.2, so I'll close this issue.

If there's some problem with saving the project please do still let me know! As I said before, there should be no need to cover it with Save All since it should get saved automatically each time the project gets modified. There is no way to save the project manually, except for the "Save Project As..." action, which is only meant to be used if you want to save a new project.
