### ISSUE TITLE
Tilde is not starting on macos 11 (beta 3)

### ISSUE THREAD

**Issue by psyycker** [bjorn/tiled#2875]
Hi guys,

Tiled (both release and snapshot) is not starting on macos 11. It looks like it's doing a kind of a fork bomb as my computer runs out of memory and swap.
If you need any help/diagnostic from me, I'm happy helping solving this issue!

I know that macos 11 is still not released but 95% of the applications are working on it and also when it'll be release, a lot of people will update to the latest version as it's a very expected update. That's why I raised this issue so that I could potentially help getting Tilde ready when Big Sure is released!

**Comment by polycursegames** [comment]
Same issue as #2845

**Comment by bjorn** [comment]
@psyycker Thanks for the report but indeed one already existed about this problem. Any help with resolving it would be greatly appreciated! You could help by performing the following steps to dig into this problem:

* Compile a local version of Tiled against Qt 5.12.9 (used by the latest snapshot) and see if it exhibits the same problem. If it does, try to find out why or where it hangs (possibly running in the debugger and pausing when the problem occurs).

* Compile the same version of Tiled against Qt 5.15.0, preferably after verifying that the problem exists in Qt 5.12.9, to check if this is an issue in Qt that has been fixed in the meantime.

Please comment at #2845 if you can provide any help, or if you have further questions.
