### ISSUE TITLE
Weird behavior of custom export/import formats

### ISSUE THREAD

**Issue by sohomsahaun** [bjorn/tiled#2879]
## Issue
I expanded the example code provided in the documentation for [tiled.registerMapFormat](https://doc.mapeditor.org/en/stable/reference/scripting/#script-registermapformat), trying to create a custom export/import format. Here is the code for [plugin.js](https://pastebin.com/zEuiMaBn), placed in *C:/Users/User/AppData/Local/Tiled/extensions*.

&nbsp;

Following happens in the **custom format file**:
- When hovering over (not clicking) them, tiles disappear.
- When taken outside of the viewport, tiles disappear.
- Zooming in/out fixes the rendering.
- Can't place any tiles on top of them.

&nbsp;

![](https://user-images.githubusercontent.com/27750907/89112080-d3f1dd80-d47f-11ea-9020-b9f8b81f56f5.gif)

&nbsp;

## Reproducing steps
- Create and edit a `.tmx` file, and save it with the custom format.
- Restart Tiled. (Doesn't cause the issue unless Tiled is closed and opened again)
- Load the new custom format file.

&nbsp;

## Additional Information

I am on Windows, using Tiled v1.4.1.

**Comment by bjorn** [comment]
Turns out this is because you're not setting the size of the tile layer. It will still accept tiles, because for storing tiles the layer does not need a size (due to the support for infinite maps) but for fixed-size maps, the layer's size _is_ used for for interaction and culling. I realize this is a bit surprising, so I'm wondering about ways to make this more intuitive.

The short fix is to set each layer's size:
```js
        layer.width = m.width;
        layer.height = m.height;
```

On the API side, we could automatically set a tile layer's size to match the map's size when it gets added to a fixed-size map, maybe only when the layer's size is set to 0x0.

In general I'm not really happy with how this data is set up, but I'm not sure exactly how to change it. Essentially in Tiled each layer's size currently always matches the map size, so it might seem like a good idea to just remove it. But there are areas in the code where tile layers exist without a map and there is also the potential of supporting layers with a different size (and maybe even different tile size) than the map in the future.

**Comment by sohomsahaun** [comment]
Thanks for the response! It works as expected.
About the layer size, I believe what you suggested is a good solution. You could also check if a layer's size has been modified before adding it to a map. If not, default to the map size!
