### ISSUE TITLE
Tilesets disappear from tileset window when closed in main window rather than remaining available in tileset dropdown

### ISSUE THREAD

**Issue by milomedic** [bjorn/tiled#2886]
I use a lot of different tilesets at once, and it is a pain having to keep my tilesets open in order for them to be used to create maps. But this isn't the case with all tilesets; some of them remain available to be used even when the .tsx file is not open in Tiled.

How do I make all my created tilesets be options in the tilesets drop-down menu?

In this first screenshot, it shows the currently open tilesets.
![image](https://user-images.githubusercontent.com/69692928/90280819-8ee38900-de39-11ea-9798-b59f06896a32.png)

In this screenshot, it shows the tilesets available from the tileset dropdown menu. This has more tilesets than I have open. But if I close the ones that are open, those tilesets disappear from the tileset dropdown.
![image](https://user-images.githubusercontent.com/69692928/90280845-960a9700-de39-11ea-89e9-f15e6d3ceed9.png)

**Comment by bjorn** [comment]
The Tilesets view displays:

* All tilesets that are referenced by the map.
* In addition, all other currently open external tilesets (either directly opened, or referenced by another open map).

So to make sure the tilesets you want to use are always loaded, they should be added to the map. You can add a reference to an external tileset by choosing _Map > Add External Tileset..._

I'll look into adding a button to this action to the Tilesets view, to make this more discoverable. Also, maybe I'll reconsider the automatic showing of tilesets that are not currently part of the map, because may be confusing people more than it is helpful.

**Comment by milomedic** [comment]
That makes sense, but it remains a bit frustrating having to manually add a dozen or so tilesets every time I create a new map.

It would be nice to have a list of "permanent" tilesets that will be available for any new map.

**Comment by bjorn** [comment]
> That makes sense, but it remains a bit frustrating having to manually add a dozen or so tilesets every time I create a new map.

Note that you can add them all at once, provided you can select them all at once in the file dialog. You can also drag them from the Project view onto the Tilesets view (though one by one in this case, since there is no multi-selection in the Project view).

> It would be nice to have a list of "permanent" tilesets that will be available for any new map.

You could make a `newmap.tmx` "template" file which you open and Save As to start any new map, which contains your "permanent" tilesets.

But I guess it would be nice if there was a mode where it would simply allow selecting any tileset that is part of your project.
