### ISSUE TITLE
docs(tmx): which attributes does the format deprecates

### ISSUE THREAD

**Issue by johelegp** [bjorn/tiled#2890]
https://doc.mapeditor.org/en/stable/reference/tmx-map-format/ mentions
> Attributes or elements that are deprecated or unsupported by the current version of Tiled are formatted in italics.

Which of these are _also_ deprecated for the TMX Map Format itself?

Perhaps some separation of concerns is needed here. Consider \<image>:
> Note that it is not currently possible to use Tiled to create maps with embedded image data, even though the TMX format supports this.

But the attributes for embedded image are not in italics.

**Comment by bjorn** [comment]
> Which of these are _also_ deprecated for the TMX Map Format itself?

There is no distinction being made. In the end, the TMX format is defined by how Tiled writes and interprets it and the documentation is only putting this into words. It has some attributes or elements in italics because they have existed in the past.

> But the attributes for embedded image are not in italics.

Because this feature is currently not deprecated and at least partially supported. Tiled can read maps with embedded image data and can write embedded image data for individual tiles (this code should probably still be generalized so that it is supported for all `image` elements). But there is currently no way in the Tiled UI to save maps with image data embedded. I could imagine adding it as an export option, but it's rather low priority since there isn't much interest in embedding images.

**Comment by johelegp** [comment]
> In the end, the TMX format is defined by how Tiled writes and interprets it and the documentation is only putting this into words.

Oh, it's great to know that! Now I know how to better handle my implementation. Thank you. I guess this can be closed, although the documentation could do with this clarification.

**Comment by bjorn** [comment]
Alright, I tried to clarify the docs a bit, hope that helps. :-)

**Comment by johelegp** [comment]
Thank you. It does.
