### ISSUE TITLE
libtiled-java cannot write external tile source image

### ISSUE THREAD

**Issue by devnewton** [bjorn/tiled#370]
The TmxMapWriter class does not write the image source of a tile.

```java
   private void writeTile(Tile tile, XMLWriter w) throws IOException {
        w.startElement("tile");
        w.writeAttribute("id", tile.getId());

        writeProperties(tile.getProperties(), w);

        if (tile instanceof AnimatedTile)
            writeAnimation(((AnimatedTile)tile).getSprite(), w);

        w.endElement();
    }
```

**Comment by mikepthomas** [comment]
I added back basic functionality for this in pull request #1372:
https://github.com/bjorn/tiled/blob/master/util/java/libtiled-java/src/main/java/tiled/io/TMXMapWriter.java#L511
@bjorn, would you like me to re-instate the original code you mention above to close this?

**Comment by bjorn** [comment]
@mikepthomas No need. I think we can just close this issue then, right?

**Comment by mikepthomas** [comment]
The code I added is incomplete compared to what you have linked, It serves my purposes for the moment, however it does not allow embedded images and does not write out the buffered image to an external file (my files already existed)

**Comment by bjorn** [comment]
You could add back support for embedded images, which should be already supported by libtiled (C++) as well. However, it's low priority since this is a features that is still not supported in the Tiled interface and I'm also unconvinced that it is a meaningful thing to support.

Writing out images is not relevant, since I consider it wrong to support such a thing at this level. When embedded images are supported in the UI, then turning embedded images into externally linked images would be a separately implemented action.

Since your added code should anyway resolve the issue reported here, I'll close this now. Thanks! :-)
