### ISSUE TITLE
default object type for tile-objects

### ISSUE THREAD

**Issue by dmi7ry** [bjorn/tiled#432]
Please make object type for tile-objects... Maybe like this:

![default_object_type](https://f.cloud.github.com/assets/1731751/462211/b65154f0-b488-11e2-80fa-23285b9036cb.png)

not easy to establish the type of the object for each new tile-object on the map
P.S. sorry for google-translating

**Comment by bjorn** [comment]
Closed by 5ab9bb99360347e0846504b3f2a3e04924686c66.

A type is now associated with each tile, which is inherited by tile objects using that tile (without copying it, however you can override the type on the object). A "Change all" functionality does not exist, but I think it will be rarely needed. There could instead be added a quick way of selecting all objects using that tile, so that you can set or reset their type easily in the Properties view.
