### ISSUE TITLE
Auto-refresh of tileset files only works for 1 refresh

### ISSUE THREAD

**Issue by Romulas** [bjorn/tiled#44]
It happens only in photoshop (version doesnt seems to make difference), MSPaint is working fine.
Tested with png files. Restarting photoshop has no effect.

**Comment by fo-fo** [comment]
The cause of the issue is in FileSystemWatcher::onFileChanged() (in filesystemwatcher.cpp). When saving from Photoshop, mWatcher->files().contains(path) returns false, but QFile::exists(path) returns false also, so the file is not readded to the watcher.

Not sure what would be a proper way to fix it. One way might be to also watch the directory where the file is/was, and add the file back to the watcher if/when it reappears in the directory.

**Comment by bjorn** [comment]
Thanks for investigating this @fo-fo! At least this gives us a clue about why it is breaking with Photoshop and we can consider ways to fix it, but indeed it seems we have to start tracking the directories also.
