### ISSUE TITLE
Changing transparent color of a tileset image

### ISSUE THREAD

**Issue by kdougan** [bjorn/tiled#507]
Upon creating a tileset, there is the option to use a transparent color. Excellent feature. However, once the tileset is created, there is no way to later add said transparent color. An option to do use a transparent color after the fact would also be excellent. That is all.

**Comment by bennywhf** [comment]
Quick question: what if the transparent color is not "magic pink?" is it possible to add functionality that allows user to click on a part of the input image with the transparent color they wish to use?

**Comment by bjorn** [comment]
@bennywhf Sure, it's something I wanted to do for a long time already, but it hasn't been a very high priority since using a special color for transparency isn't very common anymore these days. For now, you'll just have to use a color picker in an image editor to determine which color to set in Tiled.

I've created issue #1173 to remember to add a color picker eventually.

**Comment by tbredin** [comment]
+1

**Comment by bjorn** [comment]
@tbredin Both the option to change the transparent color as well as to pick the color from the image have already been implemented. Did you add a +1 to let us know you're enjoying these features? :-)

**Comment by tbredin** [comment]
The commit says "The dialog can be opened via a small "Edit..." button in the tileset properties view." — maybe it's because I'm on mac but I can't see this button anywhere

Apologies if this is a really obvious question

**Comment by tbredin** [comment]
Ah, apologies, it was off the right of the panel scroll

**Comment by bjorn** [comment]
> Ah, apologies, it was off the right of the panel scroll

Alright, no problem and glad to hear you found it!

**Comment by NeoTechni** [comment]
Where is this option in Windows? I can't find it

I would suggest not locking the properties and letting us edit those. Even clicking it, then making us click a pixel in the image would be fine

**Comment by eishiya** [comment]
> Where is this option in Windows? I can't find it
> 
> I would suggest not locking the properties and letting us edit those. Even clicking it, then making us click a pixel in the image would be fine
Click the Image property's value (the filename) on the tileset, and an "Edit" button should appear.

All the tileset properties can be edited, the Image properties just have to be edited via the Edit dialog because that does some additional checks and provides a better UI.

I think it would be good if the Edit button appeared whenever you click on any part of the Image property, not just on its value. It's really easy to miss this feature currently. It's not intuitive that you have to click the file name to edit the tile size or spacing xP

**Comment by NeoTechni** [comment]
The value for transparency is greyed out and not editable

**Comment by NeoTechni** [comment]
" Even in the dialog that comes up?"

Oh I thought you meant the transparency color options in the properties
which is what I'm asking to be editable. The dialog worked, but this is
unintuitive. It should be the behavior we expect, maybe a specific button
or even right clicking the image

"Are you editing an Image Collection tileset, by any chance?"

No
