### ISSUE TITLE
Why images in the "collection of images tileset" are align at "left-bottom" ?

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#536]
like picture :
![2013-10-01 1 57 42](https://f.cloud.github.com/assets/288367/1243139/cb8c21c8-2a5e-11e3-86f7-25cd2cd86f5d.png)

I think align at  "left-top" or "center" is better.

And

Could supply "show grid in tileset-panel" ?

**Comment by bjorn** [comment]
Choosing the background color for the tileset-panel is issue #227.

**Comment by alaa-eddine** [comment]
Hi @bjorn , would it be possible to add a property for images on "collection of images" tileset to change their offsets ?
I know there is such possibility at tileset level, but it's not possible at image level.

this property makes sence when using collection of images with different sizes, especially in isometric maps, because the offset of the images is very important to have a correct Z order while rendering.

I saw in the exported format that each image have its own entry in the tileset, so it'll not break the export format if some properties are added.

**Comment by bjorn** [comment]
@alaa-eddine That feature is covered by issue #871.

**Comment by alaa-eddine** [comment]
perfect ! just tested and it's exactly what I needed :)

**Comment by bjorn** [comment]
Closing this issue since the original question was answered and the two other suggested features existed as separate issues.

Also regarding the bottom-left alignment, there is now a new "dynamic wrapping" mode in the Tilesets view, where the tiles will also get scaled up or down to make them all display at the same size. In this mode they are not aligned into one corner.
