### ISSUE TITLE
When want to add Image on object-layer, the mouse-pointer not change to "translucent-selected-image"

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#537]
When want to add Image on object-layer, the mouse-pointer not change to "translucent-selected-image".

in tile-layer edit mode,  the mouse point will changed to   translucent-selected-tile.

**Comment by bjorn** [comment]
This issue [came up on the forum](http://discourse.mapeditor.org/t/custom-properties-to-tiles-on-tile-layer/3069/11?u=bjorn) just now. I've decided to put this on the roadmap for Tiled 1.2.

**Comment by bjorn** [comment]
After simplifying memory management (bde9c3ac1395f9c30beaadb20a44bb74787ef5ae) and the set of virtual functions (7ff97ea0e6288853385c22c9b350837ef9cb016e) I've finally done a shot at implementing this functionality (3b8ba964fad7cc4b94da24960e756199651523a1).

Will be available in the next snapshot, but before I publish that I'd like to perform further testing, since I'm sure there are still some edge-cases I didn't deal with yet (like changing current layer or selected tile while hovering).
