### ISSUE TITLE
Command to auto-show/hide all palettes

### ISSUE THREAD

**Issue by benstahl** [bjorn/tiled#563]
Similar to the Adobe apps (which use the Tab key), press a key and all palettes, tool bar, and status bar disappear, leaving you with a large "clean" view of your tile map grid. Press again and the palettes re-appear. Not sure whether the "clean" map view should re-position itself to center itself up in the new space (but I suggest yes).

**Comment by erem2k** [comment]
Looks quite straightforward, anything else other than is adding shortcut performing this action needs to be done here?

**Comment by bjorn** [comment]
@erem2k I guess the action should be visible in the menu somewhere, it could go together with _View -> Full Screen_ (F11).

The main implementation work is probably to remember which docks were visible and to restore this state when the shortcut is used again. It could be done either manually or using `QMainWindow::restoreState`, not sure what will work better. Also it needs to be considered what should be done when the user has manually restored some docks, or maybe that should be disallowed. Disallowing is probably easiest (though I'm not sure how that would be done), because care should also be taken that when entering the mode and then closing Tiled, that you can still reopen Tiled either in regular mode, or still in "distraction free" mode and able to switch back to regular mode.

When in doubt about the behavior I tend to also look at other applications that already have similar functionality. They have usually already struggled with the same questions.

**Comment by erem2k** [comment]
@bjorn 
> View -> Full Screen (F11)

Wouldn't something like "Clear View" fit better? It's not supposed to expand window into full-screen mode judging from issue description

> Also it needs to be considered what should be done when the user has manually restored some docks, or maybe that should be disallowed

In Adobe apps, restoring docks is possible during "view" mode, and they remain after interface is turned back on again in addition to docks that were originally hidden. If dock had multiple tabs, was active and had tab open during "interface" mode and was restored during "view", the tab active in "view" mode remains, sort of expand and replace behavior. If app is closed while in "view", it opens back in "interface" mode - think I'll go with that idea

**Comment by bjorn** [comment]
> Yup, will stuff it there. What hotkey is it supposed to use, Tab like suggested?

Yes, I think Tab key and in general the behavior in Adobe apps will work fine.
