### ISSUE TITLE
Mark the start or end point of lines (and polygon)

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#601]
when I draw a line for doing something , eg. as an enemy's move path.
I want to know which is startpoint , which is end point in editor.

Thanks

**Comment by finscn** [comment]
Is this feature in the develope plan ?

**Comment by bjorn** [comment]
@finscn It could be, along with the 240 other issues of course. Unfortunately, I don't have much time for Tiled development anymore. If you want to help out, please consider supporting me financially at https://www.patreon.com/bjorn. Thanks!

**Comment by finscn** [comment]
Ok.  I've chosen $1 per month .   I'm a Chinese poor man (indie developer , no job) now.  I will give you more when my game could take money for me.

Thanks

**Comment by bjorn** [comment]
@finscn That's really appreciated!

**Comment by bjorn** [comment]
Hmm, I've done a quick implementation of this but I'm not comfortable pushing it into Tiled 0.12 at this point, since it affects the boundary offset. I'd like to revisit how objects are rendered and implement this properly after the Tiled 0.12 release.

In any case here's how I think this could look, with the dot marking the start point (which should also make clear what the end point is):

![selection_006](https://cloud.githubusercontent.com/assets/531764/7483127/c271b5f6-f37c-11e4-9e2f-c7484daf5879.png)

**Comment by finscn** [comment]
Thank you very much !!!!!!  love you & kiss you

**Comment by finscn** [comment]
One Suggestion :  @bjorn , I think   an arrow at end point    is  better than a circle at start point.  

![2015-05-06 2 44 52](https://cloud.githubusercontent.com/assets/288367/7488645/a40aae0a-f3ff-11e4-9b2b-385ef18e46a0.png)

**Comment by bjorn** [comment]
@finscn Hmm, I think I prefer the dot for the following reasons:

* It is easier to implement since it does not depend on the direction of the line and does not need special code to handle drawing it at different zoom levels.
* It can't be misinterpeted as a part of the shape.
* It looks cleaner and is hence more acceptable to have always on, whereas for the arrowheads I think I'd need to add an option to turn it off for those who don't need it.

I can see the problem with the ambiguity though...

**Comment by bjorn** [comment]
So, I went for the "simple" implementation (it still required change 1b82beda168222b434f6e3b0c3beadb2ac4e0a6d to be made first so I could expand the item's bounding rect for repainting without affecting its selection outline).

The reasons not go with the arrow are the same as in my previous comment. Hopefully it's a pretty rare case to have a polyline connected like that.

**Comment by finscn** [comment]
@bjorn  ,  Could you let this feature apply to  Polygon ? Thanks

**Comment by bjorn** [comment]
No problem, reopening this issue until I got around to it.

**Comment by bjorn** [comment]
In hindsight, I wonder if it would be better to mark this starting point only in "edit polyline/polygon" mode and not always. There was also a request to display the node indexes for all point, which could also be something for the edit mode. So anyways, possibility for improvement is still there as usual. :-)

**Comment by ridiculousRPG** [comment]
Just an idea: Maybe one could draw a second smaller circle that indicates the direction? Would this be easier than the arrow?

**Comment by bjorn** [comment]
@ridiculousRPG It would essentially have the same complexity (first issue) but it would probably avoid the visual issues regarding interpretation and noise.

Are you asking because you need this or just trying to help? I would personally prefer a somewhat more complete solution that is only used when the Edit Polygons tool is active.

**Comment by ridiculousRPG** [comment]
I just thought maybe it would be easier to draw than the arrow when I was reading the comments.

**Comment by ridiculousRPG** [comment]
I thought that the coordinates of the end of the first line segment should be available and drawing a smaller point like illustrated should be easy and solves the problem...
![test](https://cloud.githubusercontent.com/assets/1174531/8889139/3bb85656-32cd-11e5-98b0-597f36ea3b1b.png)

**Comment by finscn** [comment]
@bjorn , I think @ridiculousRPG 's suggestion about polygon  is good.

**Comment by bjorn** [comment]
@finscn I think issue #145 describes a better solution to that problem, which is at least less arbitrary and more generally useful.
