### ISSUE TITLE
Can't rename custom properties in Properties window

### ISSUE THREAD

**Issue by evrehuntera** [bjorn/tiled#772]
This is a problem I have found with the new Properties window in version 0.10.x

After using the Add Property button to add a custom property to an object, I can click on the Value and edit it, but I cannot click on the Property and edit it. I have to remove the custom property then add it again but type in the new name of the property.

The old properties window allowed editing of both the Property and Value.

**Comment by bjorn** [comment]
I'm closing this since the requested functionality was implemented by pull request #803 and has been out since Tiled 0.11.

It is not optimal since you need to click the rename button with the mouse, so eventually it would make sense to add a shortcut or to look into triggering the dialog by double-clicking the name.
