### ISSUE TITLE
Dark theme for night/fusion style

### ISSUE THREAD

**Issue by ghost** [bjorn/tiled#786]
As I have seen in [this file](https://github.com/bjorn/tiled/blob/master/src/tiled/main.cpp#L154), you are using Fusion as a theme. So for the night it would be nice if you add a dark style.

(UPDATE)
I have looked into Tiled and the bad thing is you aren't using Fusion as style (or?). It would be nice if you add this feature, because then the ui looks smoother.

**Comment by JoEschner** [comment]
I'd also really prefer a dark theme! Every program I use in my development-pipeline wears a dark theme and I really appreciate it. Especially when working on a very dark map, as I am currently doing, it would improove my workflow quiet a bit. Any news on this Issue?

**Comment by bjorn** [comment]
@JoEschner No news, but in order to get around to issues like this I have started a fundraiser on Patreon: https://www.patreon.com/bjorn. Any contribution would be appreciated and would eventually allow me to spend more time on Tiled again.

**Comment by bjorn** [comment]
I've made some progress on this issue today, based on the Fusion theme. Here's two screenshots showing different levels of darkness:

![-orthogonal-outside tmx tiled_100](https://cloud.githubusercontent.com/assets/531764/16386210/282090e0-3c90-11e6-90db-6adadd7b3602.png)

![-orthogonal-outside tmx tiled_101](https://cloud.githubusercontent.com/assets/531764/16386204/2130c4a8-3c90-11e6-8eb0-b8ef91c78820.png)

Apart from automatically calculating a color scheme based on a single "darkness" value, I've customized the scroll bar because the Fusion scroll bar has way too low contrast (though I'm not happy with it yet in the darker image). I'll likely try to customize some other elements as well to make them look a bit nicer and/or add more contrast (like the tabs and dock widgets). Also, I think the icons need adjustment.

**Comment by kheftel** [comment]
looking good!

**Comment by bjorn** [comment]
I've pushed an initial change (43f98c8b5e6485b85d55842854fc36b79d1707ad) that adds the plain Fusion theme as an option (without customized scrollbar seen above for now). When switching to the Fusion theme, the base color and highlight color can be configured:

![preferences tiled_102](https://cloud.githubusercontent.com/assets/531764/16545179/e22af048-4122-11e6-8ee1-461bcbdf26ed.png)

For a dark theme, the base color can simply be set to any dark color you like.

**Comment by bjorn** [comment]
I've pushed the new scroll bars to `master` now (d74b395c4b758702813decf328de3e440d656efb). I gave them even more contrast and tweaked the buttons:

![orthogonal-outside tmx tiled_104](https://cloud.githubusercontent.com/assets/531764/16546168/54d3dc3a-4142-11e6-8c9b-157720034ca7.png)

While there's still some tweaks I'd like to make, I'll close this issue now since the dark theme is available!

**Comment by bjorn** [comment]
Here's an updated screenshot with the latest changes:

![orthogonal-outside tmx tiled_111](https://cloud.githubusercontent.com/assets/531764/17094185/f4c6e888-524d-11e6-94c1-57b6a498c164.png)

Changes include:

* Giving list items a bit more space
* Subtle gradient added to tool bars
* Menu bar margins improved
* New tab bar

There are still some smaller changes needed to fix up the dark mode (when the base color is so dark that the text is rendered bright):

* [ ] The tab close button doesn't look nice in dark mode.
* [ ] The dock widget buttons look broken in dark mode
* [ ] Check box outline is almost invisible in dark mode (making it almost invisible when not checked)
* [ ] Group box outline is almost invisible in dark mode

**Comment by bjorn** [comment]
Final screenshot after all the above fixes:

![desert tmx tiled_113](https://cloud.githubusercontent.com/assets/531764/17668576/4198f5da-630a-11e6-83db-ebb3318ca03d.png)
