### ISSUE TITLE
Custom properties and templates

### ISSUE THREAD

**Issue by benjastudio** [bjorn/tiled#818]
Hello,

First I would like to thank author and contributors of the tiled project.

Then, I was looking for a quick way to set up properties of my objects, cause I'm using them a lot! 
Something like wich may add properties without editing them manually and also apply templates (a set of predefined properties).
So I created, 2 features enabling these actions.

What the (diry) code does:
Parse 2 xml files, one definiying custom properties and another for our custom templates: 
![xml](https://cloud.githubusercontent.com/assets/9527672/4880610/a3ccbd28-633d-11e4-8d4f-ac94274cbd35.png)

What it looks like in the UI:
![custom prop](https://cloud.githubusercontent.com/assets/9527672/4880616/b1ec0706-633d-11e4-9300-ad4db902c171.png)
![custom template](https://cloud.githubusercontent.com/assets/9527672/4880618/b407d1c8-633d-11e4-9110-f47bc8b582fc.png)

So for now I just changed abstractobjecttool.cpp/.h and changeproperties.cpp/.h files, the parsing of the xml file is done on the AbstractObjectTool::showContextMenu method, it's dirty but it works fine. Also, the disadvantage of this is that is not possible to assign shortcut to our custom templates or properties.

So I'm here to know if you're interested in adding this feature, and also knowing your suggestions about it and also where is the better place in the code to parse xml files..

Thank you

**Comment by bjorn** [comment]
I'll close this since this feature is now largely provided by [predefined custom properties](http://doc.mapeditor.org/en/latest/manual/custom-properties/#predefining-properties) and [object templates](http://doc.mapeditor.org/en/latest/manual/using-templates/).

I think the menu could be extended similar to the "Apply custom template", as a way to turn an existing object into an instance of a certain template, but we could also rely on the selection in the Templates view and avoid duplicating that as a menu hierarchy. I've opened #818 about this.

If you are still using Tiled, any feedback on the new object templates system would be very welcome!
