### ISSUE TITLE
Object type dropdown disappeared in the the object properties window

### ISSUE THREAD

**Issue by theor** [bjorn/tiled#823]
The object types defined or imported in the the preferences window used to be displayed as a dropdown in the object properties popup in 0.9.1:

![e2ce1807bba75fd873a801a5c268116cecec38490e](https://cloud.githubusercontent.com/assets/531764/13664816/9ab2997e-e6a9-11e5-9b98-a21726e0da7c.png)

Now it's a textbox with completion only in 0.10.2:

![e2ce1807bbba24f9c0dd31a688a9abe078384cbd0d](https://cloud.githubusercontent.com/assets/531764/13664827/a44eff22-e6a9-11e5-8ff7-a68229d02d67.png)

Which means, there's no easy way to see all the available options. Could it at least show all completions on an empty input ?

**Comment by flexelektro** [comment]
yes ! "subscribing".

**Comment by bjorn** [comment]
You're right, I would like to have this option as well certainly. Eventually I'll have another look into this to see whether I can turn it into an editable combo box instead of using a completer. I don't think I can easily trigger the popup on empty input. It closes automatically in that case and this is implemented in Qt.

**Comment by flexelektro** [comment]
even the old dropdown would be an improvement !

**Comment by bjorn** [comment]
Yes, the old dropdown was an editable combo box. But it's more complicated to place an editable combo box inside the property editor than it was to just put such a widget in a plain dialog.

**Comment by flexelektro** [comment]
ah okay. I haven't looked at the source at this point, so i have no clue .. :)
