### ISSUE TITLE
Use smart-pointers for shared data (e.g. Tilesets)

### ISSUE THREAD

**Issue by huge88** [bjorn/tiled#853]
Hello!

## Short description:
**Problem**: The shared data of Tileset-Objects has to be manually deleted when the last object using it gets deleted. Sooner or later such things are known to lead to memory leaks, segmentation faults, ...
**Solution**: Replace the normal pointers by appropriate SmartPointers (QSharedPointer, std::shared_ptr); If you consider this issue to be a problem, too, I would make a clone and start working on this issue
**Dependencies**: Considering the Lists of Objects that are stored at multiple places and the related casts I've seen so far, I'm afraid it could affect every single class inheriting Object, Object itself and all classes/functions using Object or an inherited class
**Amount of Work**: Hard to estimate, but I'm sure it's nothing to be done within a few hours
**Alternative Solution (not recommended as long-term-solution)**: Add a comment regarding this into all concerning classes, e.g. map.h

## Long description:
Taking a look into tmxviewer.cpp I recognized that tilesets belonging to a map have to be deleted manually because they are some kind of "shared data" within the program (what makes sense within the editor). But when first reading the comments within "map.h" I thought that deletion would be done by an instance of map because of one special part of the class description: "It also keeps track of the list of referenced tilesets." There's also no hint at the description of the destructor that this is necessary.

But from experience I know that this sooner or later will lead to memory leaks, segmentation faults, ... because some day someone won't delete it or someone not considering every dependency will delete something while some other function still needs it. (There's also the danger of double deletion, of course).

A first improvement, but not a good long term improvement, could be to add comments regarding this to the code. The better way in my opinion would be to replace the normal pointers through smart-pointers (QSharedPointer, std::shared_ptr). Due to the inheritance from the Object-class, classes using Lists of Objects that have to be cast in some cases and some other relations I've identified so far using the Qt-Creator refactoring tools, I'm afraid that will be a lot of work and it will influence many files and classes.
Replacing the current normal pointers with shared pointers will make it not only possible to remove currently explicit delete calls but will maybe even make the python plugin a little bit easier to maintain because some of the calls within this part are already working with QSharedPointer.

I know that this issue is currently maybe a minor one and that it will cause much work (I would be willing to clone the repo and do the work if you consider this issue as a big problem too) but I think in the long term it will help to avoid many minor, time consuming problems.

(I've also thought about whether it would be possible to use some kind of singleton-solution as virtual memmory manage unit, so instances using a tileset can tell that they are using some tileset and that this instance would delete unused tilesets but in the end this would be the same solution with some extra overhead.)

**Comment by bjorn** [comment]
Thanks for the long description of the problem and the offer to help out with it. I've been aware of this problem of course, and would definitely like to eventually see it resolved.

I've once tried to solve it by moving the base classes in libtiled over to QSharedData + QSharedDataPointer, I've just pushed this work to the `wip/shareddata` branch for reference. However, I aborted that attempt because it became a very large change and I think it affected performance. Actually this wasn't primarily related to this issue but mainly because I wanted to be able to have long-running operations (like painting the minimap) in a thread, at which point an implicitly shared copy becomes useful.

Within Tiled, the thing that keeps the Tileset instances alive is the TilesetManager and the MapDocument wrapping any open map makes sure that references to these tilesets are counted. This way there is generally no need to worry about tilesets getting deleted. Exceptions are some cases like the stamp memory on Ctrl+1-9, which needs to do deal with the tileset reference counting as well because a map might be closed and that could otherwise cause a tileset used by a saved stamp to be deleted.

You mention dealing with this on the Object level, but really this problem is limited to Tilesets, right? Maybe you can give an example of the "list of objects" you mention where it becomes necessary to reference count Object pointers.

The sharing of tilesets actually also leads to bugs in Tiled. It is currently only done for external tilesets, but when you "import" such a tileset to make it embedded in the map, it would need to clone it first to make sure it isn't shared with any other maps. This is currently not done, and it is a difficult process because it would mean updating all the relevant Tile pointers. But as a result, importing it in one map essentially makes it imported to all open maps using that tileset and then you have a shared embedded tileset that does not behave correctly regarding information displayed in the UI and undo/redo actions. This is something to consider apart from fixing the fragile memory management.

**Comment by huge88** [comment]
First of all, thanks for the information you gave. That's a lot I've to sort and check out first to gain a better understanding of the whole system.

You asked for one example why using shared pointers will even also affect the Object-Level or other functions using Object-Instances: Let's take a look at propertiesdock.cpp : In the function "static bool isExternal" there's a switch-case with a line containing
```
return static_cast<const Tileset*>(object)->isExternal();
```
Using shared pointers for tilesets would mean that there would be some need to write something like
```
return static_cast<const QSharedPointer<Tileset> >(object)->isExternal();
```
But this cast would only be possible if object would also be of some QSharedPointer<Object>-Type. In this single example it would maybe even be possible to say: "O.K. Just pass the pointer contained by the shared pointer to that function. It's done so fast and will be called in a context where no problems will occur." But personally I prefer solutions that are consistent and can be applied on everything. If I don't find such a solution I normally get the feeling of not having completly understood some important part of the problem.

I would like you to explain one thing you mentioned closer: Why did you decide to try resolving that problem by using QSharedData + QSharedDataPointer instead of weaker smart pointers? They are known to be very expensive (e.g. creating copies automatically on non-const access until the operation has finished). That would cause many small, memory expensive single copies. Shouldn't it be enough for e.g. painting to use QSharedPointer to ensure that everything is deleted properly and not too early during one run of "paint"? Painting is quite fast. If there's a change within even just a single tile and everything that can be seen would have to be repainted, it would be very hard to notice a lag. 

By the way: That leads me to another question that came to me (just for better understanding). Why is e.g. TileLayerItem derived from QGraphicsItem instead of QGraphicsItemGroup? Considering that a TileLayer consists of tiles (and every tile could be e.g. a QGraphicsPixmapItem (or QGraphicsItem for animted tiles) that would make sense to me. What is the feature I am not aware of that cannot be handled by doing so?

**Comment by bjorn** [comment]
> But personally I prefer solutions that are consistent and can be applied on everything. If I don't find such a solution I normally get the feeling of not having completely understood some important part of the problem.

Well, it is also important to use these mechanisms only where needed, in order to avoid unnecessary complexity and performance issues. Shared pointers are for dealing with object ownership and cleanup, and the `isExternal` function does not need to concern itself with this. In fact, the whole `propertiesdock.cpp` should not need to concern itself with the lifetime of the currently selected object. If the object gets deleted, there are mechanisms in place that make sure it is no longer the current object which causes it to no longer be referenced by the Properties dock. Apart from that, the tileset in this case would already be guaranteed to be kept alive by the map and it should not also be kept alive by the Properties dock.

> Why did you decide to try resolving that problem by using QSharedData + QSharedDataPointer instead of weaker smart pointers? They are known to be very expensive (e.g. creating copies automatically on non-const access until the operation has finished).

I tried using QSharedData because that's how most basic Qt classes work and it seemed comfortable to work with. To prevent needless creation of copies in the case of modifying something I was considering to use QExplicitlySharedDataPointer. But as I said the main reason was thread-safety in case of long-running threaded operations like drawing a minimap (or computing the potentially expensive brush previews for the Fill and Terrain tools in a thread), and you don't gain this by just using a shared pointer. Thread-safety is not a question of just instance lifetime, but you also need to keep the state of the instance consistent in the face of concurrent access.

> Why is e.g. TileLayerItem derived from QGraphicsItem instead of QGraphicsItemGroup? Considering that a TileLayer consists of tiles (and every tile could be e.g. a QGraphicsPixmapItem (or QGraphicsItem for animted tiles) that would make sense to me. What is the feature I am not aware of that cannot be handled by doing so?

Instantiating a QGraphicsPixmapItem for each tile would be very wasteful in terms of memory and CPU usage, and goes against the whole point of using tilemaps. Instead, the TileLayerItem only paints its visible (or newly exposed) area using the MapRenderer.

**Comment by bjorn** [comment]
Actually tilesets are now referenced using `QSharedPointer<Tileset>` (aliased to `SharedTileset`), so I'll close this issue. It helps dealing with tileset lifetime (so there is no more need to delete the tilesets explicitly when deleting a map), but reference counting in `TilesetManager` remains for now to keep track of which tilesets to watch for reload.

Also the problem of modifying a shared tileset when "importing" it to a map is still there, which is something I plan to deal with once I get around to allow editing of external tilesets.

**Comment by bjorn** [comment]
For reference, the relevant commits were:

* a3e77a39ba38c4047a200175c88ce888c3d79fec Use shared pointers for managing Tileset instance lifetime
* 14a68b6ae0a4148c0adb2d0f84089e4899d1f996 Added an internal weak pointer to Tileset class
