### ISSUE TITLE
Map resizing

### ISSUE THREAD

**Issue by T1mL3arn** [bjorn/tiled#863]
In Map->Resize Map I can change width and height, good. But why it is not possible to do with properties toolbar?

**Comment by bjorn** [comment]
It's mainly because resizing the map can be destructive. If you make the map smaller and then bigger again, the part that was removed can no longer be added back. The only way to get it back is via the undo system.

To enable undo, a copy of the old layers is kept around. As such it would also eat a lot of memory if you did a large amount of small resizes by changing the map width property.

The main thing I could imagine to make this more intuitive is to make the resize dialog accessible from the properties editor.

**Comment by T1mL3arn** [comment]
Anyway, map resizing is useful feature and doesn't matter where is the button for doing this.

**Comment by bjorn** [comment]
Ok, I'll close this issue then.
