### ISSUE TITLE
Tile collision editor click and drag not working.

### ISSUE THREAD

**Issue by valdrin-t** [bjorn/tiled#875]
Click and drag only works when you drag from top to down, or left to right. 

*When I try to drag from right to left nothing happens. 
*When I try to drag from down to up a default sized shape will appear.

Picture for demonstration: http://i.imgur.com/7pFJgY8.png

upper left square is drawn with left-right, up-down motion.

Upper right and lower left, are default sized -- they couldn't be resized.
Lower right 2 rectangles were done dragging in only 1 axis -- -x or +y from mouse starting point

**Comment by bjorn** [comment]
This is because the initial click sets the object position, and the dragging determines the size of the object. However, since objects are not allowed to have negative size dragging upwards or to the left keeps the object's size on 0. This results in some default size to be rendered (something I think needs to be changed, but it is meant to keep 0-sized objects workable).

It would of course be nice to support dragging in all directions, and just change the position of the object as well when necessary.

**Comment by bjorn** [comment]
This was one of the things fixed in Tiled 0.17 (I had opened a duplicate at #1300).
