### ISSUE TITLE
Tile Object AD flipping vs Object rotation

### ISSUE THREAD

**Issue by obiot** [bjorn/tiled#876]
As part of the 0.7.0/0.8.0 release (not sure which one it was), H/V/AD flipping of tiles were introduced setting flags in the tile id for both "regular tiles" but also when use with tile object.

As part of the 0.10 release, object rotation has been introduced, and I believe since then, the AD flag is then not set anymore when using Tile Object.

I could not find anywhere any mention of it, so is this intended (e.g. the new object rotation superseding the previous AD flipping flag), or is this a regression ?

**Comment by bjorn** [comment]
Hmm, in fact I'm pretty sure the AD flag is and was never used on tile objects. Only the H and V flags have been used in that context. Tile object rotation uses the degrees-based "rotation" attribute.

**Comment by obiot** [comment]
Hi Bjorn, then I suppose we could close this one, although some improvements would be nice to bring more consistencies between Tiles and Tile objects ?

**Comment by bjorn** [comment]
In theory the AD flipping flag could be used for tile objects, and I think Tiled will load/save and render it properly. However, from an editing perspective there is no reason to actually ever set this flag since objects can also be freely rotated, including 90-degree rotation steps possible with the AD flipping flag. I'm not sure if it would be any improvement if the editor would actually use both mechanisms, and I'm afraid it would only be more confusing to implement support for this in games.

I'll close this issue, though feel free to comment if I missed something or you still have concerns.
