### ISSUE TITLE
Fill tool not working properly for Hexagonal maps

### ISSUE THREAD

**Issue by rafaelvcaetano** [bjorn/tiled#883]
When using the fill tool on hexagonal maps where two tiles are only connected to each other non-horizontally (when offsetting odd rows), not all tiles are detected.

Here is an example: 
![bug](https://cloud.githubusercontent.com/assets/9086379/5993553/f18f25e0-aa4c-11e4-9c40-25acc817e29e.png)

Selected tiles are the ones in turquoise. The selection should extend to the tiles below.

**Comment by bjorn** [comment]
You're right of course, but this one is a little tricky to solve due to the neighbors being different than with a standard orthogonal or isometric tile grid.

Please consider [supporting me financially](https://www.patreon.com/bjorn). As it is now I would never get around to fixing such issues.

**Comment by gostay** [comment]
Hi!  I ran into this, too.  I've been a Tiled supporter on Patreon for just a few months.  My interest in Tiled currently is its Hex Map support.  I recognize that my small monthly contribution may not justify big chunks of work, bug please consider this a vote for a fix to this bug and improved support for hex maps in general.  Thanks!

**Comment by bjorn** [comment]
@gostay I really appreciate your support and will definitely look into a solution for this! Also, do let me know what else you think should be improved about the support for hex maps.

**Comment by bjorn** [comment]
Turned out this wasn't _that_ hard to fix for hexagonal maps. It did make the code a lot larger, but its basic workings could stay the same. :-)

Unfortunately, the same isn't the case for staggered isometric maps. They are now better supported as well, but a problem remains in that diagonal neighbors are considered connected (though, that's a valid filling mode I guess, it's just not consistent with the behavior for orthogonal maps).
