### ISSUE TITLE
Changing the sequence of objects

### ISSUE THREAD

**Issue by extremalex** [bjorn/tiled#888]
Hi guys,

Really miss the feature for changing the sequence of objects in the layer (and probably their id in this case) - similar to the changing the sequence of layers with the help of the arrows.

**Comment by bjorn** [comment]
> Really miss the feature for changing the sequence of objects in the layer (and probably their id in this case)

While reordering of the objects probably makes sense to add (though others may prefer them to be sorted by name or type I guess), it would definitely not affect their ID since those are meant to be used for stable references to particular objects on the map (though currently they are not used by Tiled yet).

**Comment by extremalex** [comment]
Yes, certainly feature of changing the order by some parameters (including parameters added by the user) will also be in demand.

**Comment by Tembac** [comment]
Any news about this?

I'm working to be able to use collection of images to create levels for HaxeFlixel using tiled. 
https://github.com/HaxeFlixel/flixel-addons/issues/210

But, I found that it is very uncomfortable to not be able to sort objects by depth on Tiled. 
I think it will be nice if we can have a depth variable on the objects of the object layer so we can choose what goes in the front and what goes in the back.

**Comment by bjorn** [comment]
@Tembac Actually you can already change the order of the objects, just not in the way requested on this issue. What you'll need to do to make reordering actions available is to choose "Manual" for the "Drawing Order" property of the object layer. Then, "raise" and "lower" actions are available in the context menu for selected objects.

The thing is that these actions work visually rather than by index, so you can only "raise" an object when there is another object on top, and it will be raised exactly as much as necessary to be on top of the other object. In contrast, this issue requests such actions to work on the object index like it does for the layer stack.

**Comment by Tembac** [comment]
Ahh, Thanks @bjorn! Didn't saw that.

**Comment by bjorn** [comment]
With the merging of #1384 and followup changes, this feature is now implemented and available in the development snapshots.
