### ISSUE TITLE
External tilesets in JSON maps

### ISSUE THREAD

**Issue by tcoxon** [bjorn/tiled#891]
When you save a map in the JSON format, external tilesets it uses are written out inside the JSON map file. It would be useful to us if these could be saved as a reference to the tileset file, same as the .tmx XML format so that we can add new tiles to these sets.

I have a related question - if new tiles are added to these external files, what happens when that tileset overlaps the firstgid of the next tileset?

If new tiles can't be added to existing tilesets, can they be copied from one "collection of images" tileset to another?

**Comment by bjorn** [comment]
> When you save a map in the JSON format, external tilesets it uses are written out inside the JSON map file. It would be useful to us if these could be saved as a reference to the tileset file, same as the .tmx XML format so that we can add new tiles to these sets.

It doesn't do that because generally it is unhelpful when a JSON map refers to an XML-based external tileset. Probably this case should be handled as requested in issue #801. I do agree this issue needs addressing because at the moment this renders external tilesets as a feature unusable for those using only the JSON format.

To simplify the workflow I'm considering to make "external tileset" the default and only support the embedded option as a special-case. But this requires some internal refactoring to support properly.

> I have a related question - if new tiles are added to these external files, what happens when that tileset overlaps the firstgid of the next tileset?
> 
> If new tiles can't be added to existing tilesets, can they be copied from one "collection of images" tileset to another?

It is no problem to add more tiles to external tilesets, because on older maps in which the firstgid of the next tileset would cause overlap with the extended tileset there can be no ambiguity regarding to which tile a global tile ID is referring since it can't possibly refer to tiles that did not exist yet when the map was saved.
