### ISSUE TITLE
Tiled crashes when exporting map as picture on Windows

### ISSUE THREAD

**Issue by Mondrian909** [bjorn/tiled#907]
hi there it my first time here so pls dont blame me doing sth wrong but i have got  a pretty annoying bug: as you can read in the title tiled crashes when i want to save/export the map (120x120 tiles ala 256x256 pixel) as an png image - pls can someone help me how i can fix this issue?

**Comment by Mondrian909** [comment]
it took a very long time to set up the map
....

**Comment by bjorn** [comment]
I'm really sorry you hit a crash on exporting your map as image. Depending on your map and tile size, it is a very memory-intensive operation and currently when it causes Tiled to run out of its memory limit, the program will crash.

You can calculate the amount of memory required to save your map 1:1 roughly as follows:

Image dimensions: 120 x 256 = 30720 pixels
32-bit image in memory:  (30720 x 30720 x 4) / (1024 x 1024) = 3600 MB

Some more memory will be required while saving the image, so let's say Tiled would need about 4 GB. This is not a problem for a 64-bit build of Tiled, but a 32-bit build of Tiled can't address that much memory (its limit is around 3 GB) and will crash. It would anyway take a very long time to save such an image and the result would be nearly impossible to work with, but of course I should try to make sure Tiled will not crash.

The real solution however, is to not save such a large image in the first place. I don't personally see why you would want to do this. You should instead zoom out until your map is a more reasonable size and make sure "use current zoom level" is checked in the Save As Image dialog.

Let's leave this issue open as a reminder for me to catch out of memory problems.

**Comment by Mondrian909** [comment]
is there no other chance to avoid this bug? i managed it to crop the map to 128x128 pixel for each tile but the program still crashes - also happy easterdays ^~^

**Comment by Mondrian909** [comment]
i also checked  "use current zoom level" in the save as dialog symbol. i need such a big file/map because th whole map is going to be "open-World" so it gets rendered completely in one piece and xou are right the same resolution would cause an filesize of about 30mb (with 128x128 tiles)

**Comment by bjorn** [comment]
30 MB? I mean since you're probably saving as PNG you can't really know the file size beforehand due to the variable compression rate. I was merely calculating the amount of memory required to store the uncompressed image, which would be 3.6 GB for such a huge map.

There is no way around this, and I really can't recommend this. There is no videocard that will be able to deal with a 30720 x 30720 texture for rendering. If you mean you're making an "open world" game then you should try to use the same technique as used by Tiled to render the map. Avoiding such huge memory usage is the whole point of using tile maps in the first place.

**Comment by Mondrian909** [comment]
![screensnip](https://cloud.githubusercontent.com/assets/11710282/6974113/236380ee-d990-11e4-96c1-7b68f1c37a2d.PNG)
well sry for the german UI but this is an example oft the resolution of the map as an png file;)

**Comment by Mondrian909** [comment]
P.S.: with 128x128 Tile resolution

**Comment by bjorn** [comment]
@Mondrian909 I'm not sure what you're trying to tell me with that example. It's still a way too big image to work with for common graphics cards.

**Comment by Mondrian909** [comment]
well it wanted to tell you the image is not that "big" - in the game i will zoom in for about 50%. The map is for an 2D GTA clone so it will be an openworld game. i use tiled only as an mapeditor/creator and it works pretty well . for the rest i use opengland eclipse - first tests with such an huge map resulted in about 100mb ram usage and , depending on the cpu, 3% to 35% cpu usage - i also have an gtx 970 - but i used the interated graphics. the size is not really a problem for later operations it could depend on the limitations of the program - but for an alpha its pretty good

**Comment by bjorn** [comment]
@Mondrian909 Well, if it somehow works with your tools go for it. I'm just saying it would be a lot more efficient to use a tile-based approach also when rendering and not just when creating your map.

For 32-bit version of Tiled, all I can do is try to make sure it does not crash when trying to save such a huge image. I can't make it actually work because it can't address enough memory for this.

You may be able to do it with a 64-bit version of Tiled. For some releases I've compiled this so you can check for example the 64-bit installer here: https://github.com/bjorn/tiled/releases/tag/v0.10.1

**Comment by Mondrian909** [comment]
Ok thx 👌
