### ISSUE TITLE
Properties value field moves typing cursor to end after any character entered (OSX)

### ISSUE THREAD

**Issue by stevetranby** [bjorn/tiled#908]
When I select any property to edit and then start typing into the box the cursor is always moved to the end of the string of text. This makes it so that replacing the entire contents is more efficient than adding 3 characters or replacing a few characters in the middle of the value string.

**Comment by bjorn** [comment]
Hmm, I can't reproduce this. Which version of Tiled are you using?

If you're not using a daily build, could you try one to see if the behavior is broken there too?

**Comment by stevetranby** [comment]
Tried with the release 0.11 for OS X.
Version v0.11.0-24-g1750300 OS X daily build.
Same, lemme share a video:
https://www.dropbox.com/s/ur8xnxdlvyivcwg/tiled-typing-issue-908.mov?dl=0

**Comment by bjorn** [comment]
Ah, I was testing with custom properties, not with the Type field. It seems to be pretty specific to the Type field since I can't reproduce it with the Name field either.

It may have something to do with the completer set on that property that is supposed to help typing previously defined object types. In any case, I'll remember to look into it.

**Comment by stevetranby** [comment]
Ah, I should've checked the other fields. I guess I mostly only modify the Type field. Thanks.
