### ISSUE TITLE
Feature Request: Save/Restore Window and Selection Info

### ISSUE THREAD

**Issue by stevetranby** [bjorn/tiled#909]
Feature request to save and restore various visual/editor info maybe into a meta data store with the path as key?? The currently selected layer, map position and zoom inside the main window, tile selected, window position, property pane sizes and positioning.

**Comment by bjorn** [comment]
Just a note, the following information is already persistent and restored on startup:

* List of open maps, their current zoom level and map position.
* Position and size of the main window, the dock widgets and dialog windows.

So what you're asking for is to add the following:

* Restoring the currently selected layer and selected tiles.
* Making the map-specific information persistent for any previously opened map, not just the ones that were open when Tiled was closed.

I think this makes a lot of sense. Only restoring the selected tiles may be a bit much, since this essentially requires storing a map given that there is no limit to the size of the selection.

**Comment by stevetranby** [comment]
Sounds good. Restore of previously selected tiles is not necessary. The only other thing is maybe the dock widgets reset on upgrade? I'll let you know if I find them reset in the future again.

Thanks.

**Comment by bjorn** [comment]
> The only other thing is maybe the dock widgets reset on upgrade? I'll let you know if I find them reset in the future again.

Right, please report it if they do, because that should not happen.

**Comment by stevetranby** [comment]
I don't believe I updated/replaced Tiled.app and the various dock widgets (layers, tilesets, etc) loaded up with compressed width again. I'll try to be more diligent in figuring out in what circumstances. This time was one where I loaded up multiple maps at once in OSX with 4 .tmx selected and using CMD+O to open.

p.s. what's the best way to get started learning the code base? Just follow the readme? Qt's main tutorial? Maybe I can fix or add trivial things along the way myself, and PR them? While learning Qt at the same time :)

**Comment by bjorn** [comment]
Right, the best way to get started is first of all to set things up so that you can run Tiled from Qt Creator. Then, you can just start exploring the source code at whatever area you're interested in. Qt Creator will help you navigate (F2 or Ctrl+Click jumps to definitions, Ctrl+Shift+U finds usages), and allows you to jump into context-sensitive Qt documentation with F1.

**Comment by stevetranby** [comment]
Hey thanks! Appreciate the tool and work you've done on this.

**Comment by bjorn** [comment]
> Hey thanks! Appreciate the tool and work you've done on this.

You're welcome! Have fun exploring the source code. :-)

**Comment by bjorn** [comment]
I'll close this issue, since the active layer is by now already restored on startup and making it restore also when opening maps after startup is part of issue #905 (and already implemented on the `wip/tilesetdocument` branch).
