### ISSUE TITLE
TileObject: y-pos wrong

### ISSUE THREAD

**Issue by iJ0N45** [bjorn/tiled#91]
http://imageshack.us/photo/my-images/543/objectbugypos.png/

when i place a tileObject ( object with an Image), the y-pos is to hight.
f.e. when i place a tileobject at (2,13), the pos is (2,14).

**Comment by mariogarranz** [comment]
I agree that depending on the game one may prefer the reference point to stay at the bottom left, top left, center...

So my opinion is it would be great to have a setting to switch this, like an anchor point you can set to any value from (0,0) to (1,1).

Right now I'm fixing it by code in the tile map loader, but well, it would improve the editor IMHO.

**Comment by MrJookie** [comment]
I just ran into the same. Really strange; object at 0,0 so its position should be 0,0 and now its 0,32. I am used to the start point top left corner, sad it is not the same in Tiled.

**Comment by atbigelow** [comment]
This behavior is documented but I feel like it could be improved slightly.

For those running into this, it's easy to detect: just see if the XML node has a "gid" attribute. In that case, slide your object up some and you're good.

**Comment by bjorn** [comment]
@atbigelow While that will work for most people, just note that in general you will need to take into account the rotation of the object in order to slide it in the right direction.

Since my last post from 2014, things are looking rather better in terms of having time for Tiled development thanks to [the support I receive on Patreon](https://www.patreon.com/bjorn). This means I will eventually get around to working on a solution for this inconsistency.

**Comment by solewalker** [comment]
Hope this issue gets some love soon, having a hard time implementing a consistent object (all kinds of) loader with rotation, flipping, and scaling. If I consider flipping then rotation gets messed up, if I consider rotation then flipping gets messed up because tiled is using different pivot for different functionality which is undesired to any engine.

**Comment by bjorn** [comment]
> If I consider flipping then rotation gets messed up, if I consider rotation then flipping gets messed up because tiled is using different pivot/anchor point for different functionality which is undesired considering most engines has single pivot support for all transformations.

Maybe it's easier if you consider the pivot Tiled uses is actually always the "position" or the object, and in that sense it is not inconsistent. The only thing that is inconsistent is where the object is rendered relative to its position, but that has nothing to do with the transformations that are applied to it.

Also, flipping, assuming you mean in the context of tile objects, only changes the texture coordinates, so it is also has nothing to do with the rotation.

**Comment by solewalker** [comment]
But in most the cases flipping is done by negative scaling, which has to do with pivot/anchor point. Right now I am offsetting position for flipping. Still, its kinda hack.

**Comment by hexus** [comment]
Workarounds I've found for this:

- Detecting a GID value and decrementing object height from the Y coordinate in game code
- Setting the Drawing Offset Y value of the tileset to the height of each tile, if you're not bothered about scale or rotation

I'm using the former just because it's less fiddly/manual.

**Comment by justgook** [comment]
any chance it will be fixed ? or accepted some change request (i can try dig inside and find out issue)..

**Comment by Geokureli** [comment]
I'm greatly infuriated by this issue, please resolve it

**Comment by Seanba** [comment]
(Please remember to be kind, guys)

"Fixing" this now would require me to refactor and rebuild my pipeline and tools. I'm not saying that should be the deciding factor but there has to be a number of other projects that have made their peace with this inconsistency a long time ago and would now read in TMX data incorrectly. Ultimately, I'll go with whatever Bjorn thinks is best - just give me a head's up first if it changes. :)

**Comment by Geokureli** [comment]
you can have a setting for the default origin on newly created objects, and when a project doesn't specify this it defaults to the bottom left.

but lets be real, this should have never been the way it is. it's inconsistent with other parts of tiled as well as every graphics engine that uses it.

**Comment by bjorn** [comment]
> but lets be real, this should have never been the way it is. it's inconsistent with other parts of tiled as well as every graphics engine that uses it.

@Geokureli As I've explained in my first comment, the current way made sense at the time because it was consistent with the way tiles are rendered on tile layers (where they are also bottom-left aligned in their cell). It was also the desired alignment at the time for the game I was involved with (which was top-down, in which case it makes sense to align sprites at the bottom).

> you can have a setting for the default origin on newly created objects(I.E. edge/corner anchor), and when a project file doesn't specify this for a tile object it defaults to the bottom left.

Yes, to resolve this problem without incompatibility problems there will need to be an additional alignment/origin option. Simply changing it as done in PR #1894 is not an option.

**Comment by Geokureli** [comment]
Not to mention an origin point would be super useful for objects you plan to rotate in-game.

And sorry for the tude, when I wrote that I thought it would come off as more lighthearted banter, but rereading it just now I should have rephrased

**Comment by bjorn** [comment]
After some thoughts on this at https://github.com/bjorn/tiled/issues/2136#issuecomment-500394363, the current plan forward is to introduce a "tile alignment" option on the tileset, which can be:

* **Unset** (the default, then it's BottomLeft for orthogonal maps and BottomCenter for tile objects on isometric maps, for compatibility reasons).
* **TopLeft**, **BottomLeft**, **BottomCenter**, **Center**... maybe more? Choice between completeness or limiting to common options to avoid coding for many never-used cases.

Once set, this alignment option would apply in any map orientation and for both tile layers and tile objects. And it would not only affect the default origin of the tiles in the tileset but also the corner to which the tile is aligned within its cell on a tile layer.

Now, an additional question is how this setting would work together with eventual support for setting individual tile origin, as well as how it works together with the existing tileset drawing offset. I have a hunch that it may be preferable that the individual tile origin defaults to the one based on the alignment + tile drawing offset, but when set would completely override those rather than adding an additional offset. Does this sound reasonable?

**Comment by igroglaz** [comment]
This sounds great! Can't wait to have this feature! :)

**Comment by PeterCassell92** [comment]
Also very keen to have the feature with alignment options.

**Comment by igroglaz** [comment]
Yes, it's very desirable feature. Without it I have to rename dozens of files every time I'm changing my locations :(((((

**Comment by mustii82** [comment]
Any News?

**Comment by Phlosioneer** [comment]
I'm working on this, as a good first-project in the tiled codebase.

I'm currently trying to decipher the code that draws tiles. The actual drawing of a tile is delayed for a while, so that multiple copies of a tile can all be drawn in one go. I'm trying to figure out how it saves the position it needs to draw for each saved tile.

So after I figure out this one function, it should be done and ready for PR.

**Comment by bjorn** [comment]
The referenced commit by @Phlosioneer was a good start, but a lot more work happened as part of PR #2698. In the end, there is a new "Object Alignment" option on the _Tileset_, which controls the alignment of tile objects using tiles from that tileset.

Essentially any alignment is supported, but I expect commonly people will put this property on "Top Left" to make the tile objects consistent with the other objects. Other useful options could be "Bottom", which centers the objects bottom-aligned and "Center", which is intuitive if you're rotating tile objects.

**Comment by 5310** [comment]
@bjorn Pardon the mention, but the new object-alignment feature isn't in the 1.3.2 release that was also published on the 20th, right?

**Comment by bjorn** [comment]
@5310 Tiled 1.3.2 was a bugfixing release. New features like the object alignment will come in Tiled 1.4.

But, you can already use them now by installing the build labeled **snapshot**, available on https://thorbjorn.itch.io/tiled. I release such development snapshots every few weeks, just keep in mind that sometimes a feature may still change and of course new bugs may be introduced (and any feedback on the changes is really appreciated, because it helps make sure 1.4 becomes a good release!).

**Comment by 5310** [comment]
I never realized there were snapshot builds on Itch! I was trying to compile it myself, but I think I have my Qt dependencies messed up. 

I'll move to the snapshot release immediately. Can take bugs and feature-changes for this project :]
