### ISSUE TITLE
Tiled Doesn't Load TMX If Files Have Been Moved.

### ISSUE THREAD

**Issue by Yinyamina** [bjorn/tiled#913]
I think there should be a way to respecify where tilesets are located in the event that you move them around for more organization. As it is now, Tiled says it can't find it and doesn't even bother to load or ask if you want to find it on your own. So I think an option such as this would be great!

**Comment by bjorn** [comment]
Definitelly. Your only option at the moment, is to either move the files back or to fix up the file references in the TMX file using a plain text editor.

**Comment by Yinyamina** [comment]
Didn't even know you could open a tmx in a text editor! Thanks. I'll edit them from there.

**Comment by njorthbiatr** [comment]
I ran into this issue too, it would be nice to at least have a prompt that lets you browse to the location.

We did eventually figure out that you could modify the directory in a text editor. But a less temporary solution is to store everything in folder on your C drive like C:\Tiled\. So long as the file names are all right, there shouldn't be any issues with portability.

**Comment by zekrom-vale** [comment]
Using absolute paths should help fix the problem when you move the .tmx files.  Still I don't know why it thinks the path is invalid but it is not displaying the file in the location.
Plus, when working with Starbound it is a hassle, you have to fix each file individually and it does not autofill the file name.

**Comment by bjorn** [comment]
> Using absolute paths should help fix the problem when you move the .tmx files.

You can't use absolute paths, since they are often different on each person's machine. In general the relative paths work just fine, but in the future Tiled will probably also support paths relative from a predefined "assets" location (or even multiple locations).

> Still I don't know why it thinks the path is invalid but it is not displaying the file in the location.
> Plus, when working with Starbound it is a hassle, you have to fix each file individually and it does not autofill the file name.

You're replying to an old issue that was resolved in Tiled 0.15. If you're having any issues or suggestions related to loading TMX files that have moved or refer to assets that have moved, please open a new issue about it with more details.
