### ISSUE TITLE
Multiple image tileset

### ISSUE THREAD

**Issue by YPetremann** [bjorn/tiled#917]
For now with latest release we can add a collection of images or an image as tileset, I think it would be interesting to have the possibility to add multiple tileset images inside a tileset, each would have the possibility to have custom tile size

**Comment by bjorn** [comment]
Well, this would require a change in the TMX format since the tile size is defined on the `tileset` element and not its `image` element. But I don't really see the point since you can just have multiple tilesets instead.

Why are you asking for this? Do you have tiny tileset images that you want to group together in a single tileset view? And if so, how do you expect them to appear?

**Comment by bjorn** [comment]
Closing this one since I think it would make things too complicated. The fact that tilesets can be either based on a single image or be a collection of images is already cause for some confusion and unhelpful behavior.
