### ISSUE TITLE
Lua Exporter: The backslash (\) gets doubled each time used in a string 

### ISSUE THREAD

**Issue by MadByteDE** [bjorn/tiled#933]
Lua escape sequences get malformed when added into a string in tiled. for example this line:
```lua
"Hello \n World"
```
In the tmx file the string is saved as expected. However in the lua export it magically got two backslashs what causes that my text won't get printed properly.
```lua
properties = {
            ["text"] = "Hello \\n World"
          }
```

**Comment by bjorn** [comment]
Well, if you want your text to be "Hello \n World", then it is necessary to escape the `\` in the output otherwise Lua would interpret your `\n` as a newline character. By escaping strings properly, Tiled makes sure that the string appears exactly as written in Tiled on the Lua side.

Unfortunately, it is at the moment impossible to put a newline in a property in Tiled. The only way to achieve this is to edit the TMX file in a text editor. In this case, Tiled will export it to Lua as `\n`.

Eventually I want to add a text area for editing multiline properties to the properties editor. This is covered by issue #205.

**Comment by MadByteDE** [comment]
> otherwise Lua would interpret your \n as a newline character
Thats exactly what I want it to do.

>Tiled makes sure that the string appears exactly as written in Tiled on the Lua side.
This isn't true.When typing "Hello \n World" in tiled I get "Hello \\n World" as output at the lua side.
This looks clearly like a bug to me. 

I don't need multiline support in Tiled. I just want to have the exact same line I typed exported to the lua file.

Maybe I just don't get what you wrote there. Sorry then. 
So you saying it is impossible to export the exact same line I type in tiled to lua ?

**Comment by bjorn** [comment]
> This isn't true.When typing "Hello \n World" in tiled I get "Hello \\n World" as output at the lua side. This looks clearly like a bug to me.

That's because you're reading the Lua code. When you would `print` the string from Lua to the console, it would output exactly like you wrote it in Tiled.

> I don't need multiline support in Tiled. I just want to have the exact same line I typed exported to the lua file.

That would easily lead to invalid Lua code if you're not careful with what you type. Most notably, users would be struggling to insert any special character like `\` or `"` into their values and would suddenly have to remember to escape these for the sake of the Lua export.

Really, if you want a newline character in the string, you probably need multiline support in Tiled.
