### ISSUE TITLE
Exported Flare Map Missing Object Layer Data

### ISSUE THREAD

**Issue by KaYBlitZ** [bjorn/tiled#935]
See title. Exporting tilemap as a flare map shows header and the tile layer, but the object layer is completely missing from the .txt file.

**Comment by bjorn** [comment]
From the `flareplugin.cpp`:
```c++
        if (ObjectGroup *group = layer->asObjectGroup()) {
            foreach (const MapObject *o, group->objects()) {
                if ((!o->type().isEmpty())) {
                    out << "[" << group->name() << "]\n";
```
The last check implies that the Flare map format will only write out objects if they have a type set. @stefanbeller is the main author of this plugin and probably had a reason for this.

Note that this plugin is only meant to be used to save/load maps for the [Flare](http://flarerpg.org/) game engine. It is missing a large amount of information that Tiled may save in its own XML-based map format. If you want to make sure everything is written out properly, use the TMX format. In case you're not using external tilesets, you can also use the JSON format (at least until #801 is closed).

I'll close this bug since supporting all Tiled features in the Flare map format is not planned. There is however the related issue #881 open about this, but it is very low priority since I find the benefits questionable.
