### ISSUE TITLE
Add an executable picker for setting up commands

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#942]
It would be convenient if a file picker would be available for finding the executable to execute for a command.

Requested at issue #940.

**Comment by ketanhwr** [comment]
@bjorn I'd like to work on this one now. What would you suggest regarding the UI? I am thinking something along the lines of how custom shortcuts were registered:

- Add a text edit above the QKeySequenceEdit and the user can enter the command there, instead of entering it in the CommandTreeView.
- Just above the Clear button, there will be another QPushButton which would be an option to select the file of an executable.

Does this UI seem fine?

**Comment by bjorn** [comment]
I think it makes sense to reorganize the UI a little rather than adding more widgets to the bottom, like in the screenshot I showed you [here](https://github.com/bjorn/tiled/issues/1456#issuecomment-283770968).

**Comment by ketanhwr** [comment]
So I'm trying the following:

![Screenshot](https://image.ibb.co/kjBaGF/Screenshot_from_2017_03_15_15_52_51.png "Screenshot")

The `CommandTreeView` will have only 1 column now, which will display the name of the column. The user can double click on `<new command>` to create a new command. The description is meant for Tool Tip text probably. The user can either enter the command directly, or browse by clicking on the `Browse...` button.

I've reduced the `CommandTreeView` to only column, because it would seem very odd to display all the data two times.

Is this alright?

**Comment by bjorn** [comment]
That's roughly what it should be, yes. A few points of feedback:

* I see no need to add a "Description" field at this point.
* Please move the "Enabled" checkbox back to the list view. You could move the check state into the Name column, as done with the list of plugins in the Preferences for example. Having it in the list is important because that's the only way to quickly see which commands are enabled.
* Please keep the read-only "Shortcut" column in the list view, for the reason why we put it there.
* The "Save map before executing" option can be moved where you have the "Enabled" checkbox. Of course, it should be changed to be stored for each command then.
* Please put a Spacer at the bottom of the vertical layout on the right, to make sure the items sit together instead of getting stretched out.

**Comment by ketanhwr** [comment]
Alright! :+1:

**Comment by ketanhwr** [comment]
So this is how it looks currently. I'll hopefully make a pull request by today.

![Command Dialog](https://image.ibb.co/iTdaiv/Screenshot_from_2017_03_15_17_42_20.png "Command Dialog")

I've added "Save Before Execute" unique to each command. Any other suggestions? :)

**Comment by bjorn** [comment]
> I've added "Save Before Execute" unique to each command. Any other suggestions? :)

I think it looks quite alright, though you shouldn't move the Close button into the vertical layout on the right. It should stay on its own line at the bottom.

**Comment by ketanhwr** [comment]
The Close button was previously like that only, but it looked very weird at that position since the "Save map before executing" check was moved. I tried a few positions for the close button, and found this one alright.

**Comment by bjorn** [comment]
Yes, it will waste some space on the left, but that is still the right place for it. The layout you showed is a little confusing because it's not immediately clear that the button closes the dialog, rather than just the right side of it.

**Comment by ketanhwr** [comment]
I think we should add "Execute in Terminal" option too. What do you think? If the user selects an executable like `echo` then the command won't be executed at all. What do you think?
