### ISSUE TITLE
Save as 'JSON minified'

### ISSUE THREAD

**Issue by Deathspike** [bjorn/tiled#944]
When saving a tiled map as JSON, the JSON file is written with quite a bit of spacing between elements. The spacing serves no real purpose and increases the file size of the tiled map. This is important when working a web related project, any increased file size decreases user experience due to a higher download time.

Please consider either:
- Saving files as JSON as minified by default
- Or, allowing a different file extension (.jsonm?) that is always minified after editing.
- Allowing a preference in the tiled map editor that switches on minification

**Comment by bjorn** [comment]
I'll consider this feature, but note that serving the file compressed will have a much bigger impact on reducing the download time than removing the whitespace. To avoid increasing CPU usage, it is also possible to precompress the file server-side. Compression is supported as part of the HTTP standard so should be transparent to the client.

Related to this is adding support for saving the tile layer data as binary compressed rather than as a JSON array, in the same way as is already done in the TMX format. This is covered by issue #343.

**Comment by Deathspike** [comment]
You are absolutely correct. However, most modern web servers are quite capable of compressing and caching the result by themselves (when configured appropriately). I'm just a bit on the absolute optimization side, and I even currently have a pipeline that copies and minifies the JSON files, but I'd love to get rid of that complexity.

**Comment by bjorn** [comment]
You may be interested to know that I just implemented #343.

**Comment by bjorn** [comment]
Also [requested on the forum](http://discourse.mapeditor.org/t/minify-json-export/2896).
