### ISSUE TITLE
Which site  is  the last version of tiled for mac ?

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#957]
https://github.com/bjorn/tiled/releases     or  http://tilemapkit.com/tiled/?C=N;O=D  ?

**Comment by bjorn** [comment]
They're currently essentially the same. However, your first link goes to a versioned release. Usually the releases are a bit more stable, and you most translations will have been updated.

In contrast, the second link points to daily builds. They are done automatically whenever I push new changes into the repository. This means translations for new or changed strings are missing and the changes may not have been tested very well yet.

My recommendation is to use the releases, and only use the daily builds when you either depend on or want to help with testing any of the changes made since the last release.

In the past, there have been very long times until I got around to making a new release (for Tiled 0.9 and 0.10 for example). Back then the daily builds would often be preferable because the previous release was so outdated and missing so many improvements. However, now that I have some more time for Tiled again thanks to patrons like yourself this should not happen anymore.
