### ISSUE TITLE
When moving the cursor quickly, 'Use automapping, when drawing into layers' does not work

### ISSUE THREAD

**Issue by Aedx** [bjorn/tiled#958]
When `Preferences -> Automapping -> Use Automapping, when drawing into layers` is checked, if one moves one's cursor quickly, the tile is not automapped. This could cause some problems, e.g. hiding one's collision layer in tiled and then falling through the floor in-game. This is especially problematic when utilising peripherals such as a graphics tablet.

A demonstration is as follows, where the brown tile marks are where I drew, and the black/pink tiles are for collision detection (and are placed where brown tiles are):

![](https://cloud.githubusercontent.com/assets/6864861/7751049/c88bb39c-ffcf-11e4-9b4b-a9d13e22c31d.png)

Note that I used the fill tool beneath the line which I drew, automapper appeared to work for this. The second image shows the result of manually selecting automapper.

![](https://cloud.githubusercontent.com/assets/6864861/7750585/f5a0a368-ffcc-11e4-8164-400022ed814b.png)

**Comment by bjorn** [comment]
Hmm, this seems to be because the `regionEdited` signal to which the automapping feature responds is emitted repeatedly with the same region, which happens because it's emitting the region of the brush preview, which does not get updated for each position when the mouse moves fast. I'll have to make sure the emitted region is correct somehow.

**Comment by bjorn** [comment]
This fix will be included in Tiled 0.12.3, which I plan to release in the next days.
