### ISSUE TITLE
Fresh install segfaults Debian 8

### ISSUE THREAD

**Issue by AliceGrey** [bjorn/tiled#960]
After reinstalling tiled it no longer runs. I get a segfault.
I've tried sudo apt-get remove --purge and building from source.

Here is the gdb output
<code>
Starting program: /usr/bin/tiled 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeba01700 (LWP 28435)]
[New Thread 0x7fffe9388700 (LWP 28436)]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bcedb0 in Tiled::Tileset::tileAt(int) const () from /usr/bin/../lib/tiled/libtiled.so.1
</code>

**Comment by bjorn** [comment]
What version of Tiled is this?

`tiled --version`

Can you try creating a backtrace again after installing debug symbols?

`apt-get install tiled-dbg`

If you want to be able to run your current version of Tiled, I think you'll have to put aside the configuration file to prevent it from loading the previous map(s) on startup:

`mv ~/.config/mapeditor.org/Tiled.conf ~`

(I intentionally instructed you to move it rather than delete it, cause I still need more information - like requested above, and possibly this file and the maps you had open if possible - in order to reproduce or fix this issue)

**Comment by AliceGrey** [comment]
This is version 0.10.1 from the debian repos. But it throws the same error with a self compiled version of 0.12.

This is with tiled-dbg installed
<code>
Starting program: /usr/bin/tiled 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeba01700 (LWP 2632)]
[New Thread 0x7fffe9388700 (LWP 2633)]
Program received signal SIGSEGV, Segmentation fault.
Tiled::Tileset::tileAt (this=0x91, id=-1862467837) at tileset.cpp:46
46	tileset.cpp: No such file or directory.
</code>

**Comment by AliceGrey** [comment]
Here is the last tmx file I had open: https://www.sendspace.com/file/d0xxtq
and the config file: https://www.sendspace.com/file/v3rjop

**Comment by bjorn** [comment]
Alright, you uncovered a bug in the map reader! It is caused by what appears to be an invalid tileset so fortunately I don't expect it to affect many people. The tileset in `level1.tmx` are:

```xml
 <tileset firstgid="67" name="coin" tilewidth="16" tileheight="32">
  <image source="code.png" width="77" height="11"/>
 </tileset>
 <tileset firstgid="67" name="envir6" tilewidth="16" tileheight="16">
  <image source="envir6.png" width="360" height="52"/>
 </tileset>
```

There's two problems here. First of all the first tileset should have a `firstgid` of 1, but instead it somehow starts at 67, which is the same as the second tileset. Secondly, no tiles can be cut from the first tileset since its tiles are 16x32 but the image is 77x11. This would explain why the next tileset has the same `firstgid`, but it does not explain yet why it is 67 rather than 1.

The crash happens when it tries to find a tile for the global ID 3, which does not exist because there is a gap between global ID 0 and global ID 67. Gaps like that are not expected, but I should adjust the map reader to report it as an error instead of crashing on it.

Do you have any idea how this file came to be like that? If you didn't edit it in a text editor, there may be a bug in the map writer as well.

**Comment by AliceGrey** [comment]
I opened it up in a text editor to copy some of my old stuff from another map. I must have done it wrong.

**Comment by bjorn** [comment]
@AliceGrey Alright, that's good to hear. That means that I probably just need to fix the map reader to not crash in this situation.

**Comment by toddcarnes** [comment]
I'm running Debian 8 myself and when I install version 0.10.1 from the repository and open the OP's supplied tmx file, I do not get a segfault. I get a messagebox opening and giving an error message. (screenshot attached)
![screenshot_2015-05-25_15-24-59](https://cloud.githubusercontent.com/assets/694039/7802792/5b51bf8a-02f2-11e5-9692-819712e0304f.png)

**Comment by AliceGrey** [comment]
@toddcannes that's because you haven't fully loaded the file. It's throwing an error because you don't have the coin texture. Add any texture to /home/todd/art/ and name it coin.PNG and it will segfault

**Comment by AliceGrey** [comment]
@toddcarnes sorry I'm on my phone. I meant code.png not coin.PNG.

**Comment by toddcarnes** [comment]
You're right I created code.png and envir6.png, then it did crash. :)

**Comment by toddcarnes** [comment]
OK, I got to build and it still crashed.
