### ISSUE TITLE
Add a script to easily compile Tiled under Windows

### ISSUE THREAD

**Issue by x-a-n-a-x** [bjorn/tiled#968]
Hello.

I have read https://github.com/bjorn/tiled/wiki/Contributing-to-Tiled and it's obvious that there are many steps to follow in order to successfully compile Tiled under Windows.

What I suggest is to create a .cmd (powershell) script that could:
- check if the OS has the correct compiler
- download all required DLL libraries 
- allow the user to "clean" the Tiled folder and this way, to remove all built and copied files
- compile the source code

Here is a good example for this script:
https://github.com/OpenRA/OpenRA/blob/bleed/make.cmd
https://github.com/OpenRA/OpenRA/blob/bleed/make.ps1 

This would really help contributors participate in the development, or at least, to test the latest changes.

**Comment by bjorn** [comment]
Hmm, if you focus on Windows and leave out the explanations, actually the steps to follow in order to compile Tiled on Windows should be trivial:

* Clone Tiled repository
* Install Qt - http://www.qt.io/download-open-source/
* Open `tiled.pro` in Qt Creator
* Select 'tiled' as the project to run (selector is right above run button) and press the run button

Now, I can't check at the moment whether there's anything else to pay attention to in this process, but I still think the steps are so easy that it does not really make sense to write some automation script for it.

**Comment by toddcarnes** [comment]
Actually, it's pretty simple to compile and run Tiled on Windows, 
especially if yo already have git and Qt installed. Just clone the 
repository ad compile in Qt Creator.

**Comment by x-a-n-a-x** [comment]
The goal of such script is to make things even easier..

**Comment by bjorn** [comment]
Really the script would not be able to automate the last two steps of the ones I listed, so the only thing it could "automatically" do is cloning the Tiled repository and installing Qt, if this was indeed possible to automate.

Cloning the repository on Windows is the easiest when installing [GitHub for Windows](https://windows.github.com/), which GitHub already directs you to automatically when you press their clone button on Windows. This means the only remaining step to automate is installing Qt. I just don't think wrapping up that installer in a script will make it much easier. At the same time, it may prevent you from going through steps that actually are good to go through because it teaches you something about Qt.

I think the main thing we're missing here is a short list of the minimum steps required to get Tiled running from source, like I've written above. The article-style getting started document we have now is probably just making things look more complicated than they are.

**Comment by x-a-n-a-x** [comment]
Can't it be possible to compile without installing the whole QT suite ? 

What I meant by creating this script is to only download the required DLLs, then to let the user type "build" (for example) and the script compiles in command line.. 

The idea is not to launch automatically QT Creator, then to open the project file (tiled.pro) and simulate a click on "run" button.. Doesn't the QT Suite provide command line tools and compilers ?

And btw, "GitHub for Windows" is the worst (windows) git client to advice. Please have a look at SmartGit instead (it's much faster and more stable). :-)

**Comment by bjorn** [comment]
> Can't it be possible to compile without installing the whole QT suite ?

Well, you could download the Qt library and MinGW compiler separately and compile from command-line, avoiding the need for Qt Creator. But I would guess most people compiling Tiled themselves would be interested in possibly changing the source, and the procedure to just install Qt and MinGW with the Qt installer is still easy enough.

> What I meant by creating this script is to only download the required DLLs, then to let the user type "build" (for example) and the script compiles in command line..

In this case, why wouldn't the user just download the daily build? It is updated within half an hour of pushing changes to the repository.

> And btw, "GitHub for Windows" is the worst (windows) git client to advice. Please have a look at SmartGit instead (it's much faster and more stable). :-)

I mentioned GitHub for Windows only because it is easy to use. I totally agree it is quite a bad git client, but mainly because it is lacking so much functionality. Personally I'm comfortable with git itself.

**Comment by toddcarnes** [comment]
You can always just run qmake from the command line, but I think most 
beginners do NOT want to use the command line.

The majority of Windows users don't like using the command line. After 
all, the whole point of Windows originally was to do away with that. :)

I think in most cases, it's probably easier/preferable to just use Qt 
Creator. Then things like the "clean" step you mentioned earlier are a 
simple as two clicks of a mouse button.

This is Bjorn's project and he'll do what he thinks is best, but I 
really don't see this as making anything "simpler" or "easier" for 
Windows users.

Todd

**Comment by x-a-n-a-x** [comment]
Oh, I didn't know you offered daily builds.. Nice.
It removes the need to compile the source code often just to test the latest features.

**Comment by bjorn** [comment]
Your report still caused me to do some cleaning on the [Contributing to Tiled](https://github.com/bjorn/tiled/wiki/Contributing-to-Tiled) wiki page. It's not as short as it could be, but it includes way less redundant or confusing text now. :-)

**Comment by toddcarnes** [comment]
On 05/31/2015 12:39 PM, Thorbjørn Lindeijer wrote:
>
> Your report still caused me to do some cleaning on the Contributing to 
> Tiled <https://github.com/bjorn/tiled/wiki/Contributing-to-Tiled> wiki 
> page. It's not as short as it could be, but it includes way less 
> redundant or confusing text now. :-)
>
>

If you're updating the wiki, you might want to recommend downloading 
"Visual Studio Community 2013" 
(https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx), 
instead of the outdated "Microsoft Visual Studio Express 2013 with 
Update 3 for Windows Desktop".

Todd

**Comment by bjorn** [comment]
> If you're updating the wiki, you might want to recommend downloading "Visual Studio Community 2013" (https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx), instead of the outdated "Microsoft Visual Studio Express 2013 with Update 3 for Windows Desktop".

If you're on Windows, please feel free to update and verify the necessary steps for installing the community edition. I do not have Windows installed so can't describe the required steps accurately.

Just note that this section is only for those who need Tiled to be compiled in 64-bit mode. For a 32-bit version of Tiled it is easier to go with the MinGW 4.9 included in the Qt installer.
