### ISSUE TITLE
Display object names

### ISSUE THREAD

**Issue by happyponyland** [bjorn/tiled#972]
I recently upgraded to 0.12.2 and found that the names of objects are no longer displayed (rectangles in my case). I wish there was a way to re-enable them (ideally an option under "View"). I wish there also was an option to prevent long object names from collapsing into ... and just display the full string regardless of object dimensions.

**Comment by bjorn** [comment]
Right, thanks for opening an issue about it. I had to remove the object names because they were interfering with the support for rotation and scaling, because the way they were implemented it affected the bounding box of the objects. It also just looked silly that the names were rotating along with the objects.

So yes, they will be back, and I'll try to make it better this time.

**Comment by rainChu** [comment]
While you're re-implementing it, would it be possible to add an option to change the name size and font in the preferences, or at least the minimum rendered size of the displayed name before it's clipped? ("Foobar" would become "Foob..." on a small object.) I have a lot of Rectangle objects, many of them are just points or 16px square, and the large font used previously would prevent a large name. But there were so many, I needed a name for each.

**Comment by bjorn** [comment]
@rainChu I don't plan to cut off the names at all actually.

Unfortunately I did not get around to this for Tiled 0.13, for which I'd like to announce the string freeze soon. So I'll be moving this to Tiled 0.14. But just get a daily build once this is done so you can provide feedback before it goes into a release.

**Comment by rainChu** [comment]
Sure thing, thanks!
