### ISSUE TITLE
Multiple terrain levels of detail

### ISSUE THREAD

**Issue by TristanBomb** [bjorn/tiled#974]
The current terrain system is extremely handy and a vast improvement over simple tile placement, but the current 16-state system (4 corners) doesn't give much room for details like U-shaped tiles. Perhaps a variable grid can be implemented: the default being 2x2 (current system), but can be altered to 3x3 (corners, edges, and middle; sufficient for pretty much everything) or higher. This would also allow for single-tile brushes that still connect to other terrain.

Of course, it's still pretty viable to just add the details by hand, and I'm sure such a suggestion wouldn't be too simple to implement.

**Comment by bjorn** [comment]
Even with the monthly [support on Patreon](https://www.patreon.com/bjorn?ty=h) allowing me to spend one full day a week on Tiled, it is currently unlikely that I would get around to supporting this use-case. That said, I would like to make improvements to the terrain tool at some point and this would be one possible improvement.

Unfortunately this amount of detail is not just making the implementation trickier, but it also raises some questions on how the editing should work I think. With 3x3 points of terrain on a single tile, the current way of painting the terrain onto the tiles will get rather fiddly. Also, you get into the situation where a huge amount of variations will never actually exist in the tileset.

That said, there seem to be ways of dealing with these things and it would definitely be an interesting topic to look into.

On a sidenote, I want to point out that even though the terrain tool is using 4 corners, it is not a 16-state system. This is because each of the 4 corners can be assigned any of up to 255 different terrain types. So with a byte per corner rather than a bit per corner, actually it's a 256^4 (or 2^32) state system. This allows it to handle tilesets like https://github.com/tales/sourceoftales/blob/master/tiles/terrain.png

**Comment by TristanBomb** [comment]
Okay, thanks.

**Comment by bjorn** [comment]
The "3x3" setup (except the middle, for now) is now supported by the Wang Brush using a "Mixed" Wang set. This improved Wang Brush is replacing the Terrain Brush in Tiled 1.5.
