### ISSUE TITLE
Add ability to resize objects with tile (gid) inside

### ISSUE THREAD

**Issue by Darky-Lucera** [bjorn/tiled#980]
I think it would be useful to resize (stretch to fit) the images/tiles/gids inside objects to the size of the object instead of the size of one tile.

Normally we use objects to place 'in game objects' like trees, coins or even mountains that have different sizes.

**Comment by bjorn** [comment]
Which version of Tiled are you using? Since Tiled 0.12, tile objects are rendered at the size of the object and not at the size of the tile, and they can be resized (stretched) as needed.

When you place new tile objects, their default size is still the size of the tile, but after that you can freely change the size independently of the tile size.

**Comment by Darky-Lucera** [comment]
Oops! Sorry. I thought that the last version was 0.11. I'm so outdated :(

**Comment by bjorn** [comment]
No problem. :-)
