### ISSUE TITLE
Tileset properties doesn't list margin and spacing

### ISSUE THREAD

**Issue by AMDmi3** [bjorn/tiled#997]
And actually more properties which are only available on tileset creation.

**Comment by bjorn** [comment]
Right, they could be added as read-only for now, until  #773 is implemented.

**Comment by bjorn** [comment]
@IMMZ Since you were looking for more things to do, maybe this would be something for you. Note that for now I'd prefer them to be just read-only, since before allowing the user to change them I want to reconsider the design a bit.

The complete list of missing properties is:

* Source Image
* Tile Size
* Margin
* Spacing
* Transparent Color (though you can skip this one, since it's covered by #983)

Also, please don't add these properties for the case of a 'Collection of Images' tileset, since in that case they're all irrelevant. You can recognize this case by whether the `Tileset::imageSource()` is an empty string.

**Comment by IMMZ** [comment]
@bjorn Implementation should add 5 properties to the properties dock for a tileset and all of them read-only?

**Comment by bjorn** [comment]
@IMMZ Yes, almost. It will be 4 properties once you skip the one I said you can skip. :-)

**Comment by IMMZ** [comment]
@bjorn Sorry, my fault :) Ok, I'll look at it this week.
